export interface Page<T> {
  count: number;
  page: number;
  next: boolean;
  data: T[];
}

export enum STATEMENT_GROUP {
  CONTACT = "CONTACT",
  SOCIAL_MEDIA_ACCOUNT = "SOCIAL_MEDIA_ACCOUNT",
  NFT_ACCOUNTS = "NFT_ACCOUNTS",
  SOCIAL_MEDIA_VERIFICATION_POST = "SOCIAL_MEDIA_VERIFICATION_POST",
  GENERAL = "GENERAL",
}

export enum STATEMENT_TYPE {
  X = "X",
  FACEBOOK = "FACEBOOK",
  LINKED_IN = "LINKED_IN",
  INSTAGRAM = "INSTAGRAM",
  TIK_TOK = "TIK_TOK",
  GITHUB = "GITHUB",
  REDDIT = "REDDIT",
  WEIBO = "WEIBO",
  SUBSTACK = "SUBSTACK",
  MEDIUM = "MEDIUM",
  MIRROR_XYZ = "MIRROR_XYZ",
  YOUTUBE = "YOUTUBE",
  DISCORD = "DISCORD",
  TELEGRAM = "TELEGRAM",
  WECHAT = "WECHAT",
  PHONE = "PHONE",
  EMAIL = "EMAIL",
  WEBSITE = "WEBSITE",
  LINK = "LINK",
  BIO = "BIO",
  SUPER_RARE = "SUPER_RARE",
  FOUNDATION = "FOUNDATION",
  MAKERS_PLACE = "MAKERS_PLACE",
  KNOWN_ORIGIN = "KNOWN_ORIGIN",
  PEPE_WTF = "PEPE_WTF",
  OPENSEA = "OPENSEA",
  ART_BLOCKS = "ART_BLOCKS",
  DECA_ART = "DECA_ART",
  ON_CYBER = "ON_CYBER",
  THE_LINE = "THE_LINE",
}

export const CAN_OPEN_STATEMENT: Record<STATEMENT_TYPE, boolean> = {
  [STATEMENT_TYPE.X]: true,
  [STATEMENT_TYPE.FACEBOOK]: true,
  [STATEMENT_TYPE.LINKED_IN]: true,
  [STATEMENT_TYPE.INSTAGRAM]: true,
  [STATEMENT_TYPE.TIK_TOK]: true,
  [STATEMENT_TYPE.GITHUB]: true,
  [STATEMENT_TYPE.REDDIT]: true,
  [STATEMENT_TYPE.WEIBO]: true,
  [STATEMENT_TYPE.SUBSTACK]: true,
  [STATEMENT_TYPE.MEDIUM]: true,
  [STATEMENT_TYPE.MIRROR_XYZ]: true,
  [STATEMENT_TYPE.YOUTUBE]: true,
  [STATEMENT_TYPE.DISCORD]: false,
  [STATEMENT_TYPE.TELEGRAM]: false,
  [STATEMENT_TYPE.WECHAT]: false,
  [STATEMENT_TYPE.PHONE]: false,
  [STATEMENT_TYPE.EMAIL]: false,
  [STATEMENT_TYPE.WEBSITE]: true,
  [STATEMENT_TYPE.LINK]: true,
  [STATEMENT_TYPE.BIO]: false,
  [STATEMENT_TYPE.SUPER_RARE]: true,
  [STATEMENT_TYPE.FOUNDATION]: true,
  [STATEMENT_TYPE.MAKERS_PLACE]: true,
  [STATEMENT_TYPE.KNOWN_ORIGIN]: true,
  [STATEMENT_TYPE.PEPE_WTF]: true,
  [STATEMENT_TYPE.OPENSEA]: true,
  [STATEMENT_TYPE.ART_BLOCKS]: true,
  [STATEMENT_TYPE.DECA_ART]: true,
  [STATEMENT_TYPE.ON_CYBER]: true,
  [STATEMENT_TYPE.THE_LINE]: true,
};

export const STATEMENT_TITLE: Record<STATEMENT_TYPE, string> = {
  [STATEMENT_TYPE.X]: "X",
  [STATEMENT_TYPE.FACEBOOK]: "Facebook",
  [STATEMENT_TYPE.LINKED_IN]: "LinkedIn",
  [STATEMENT_TYPE.INSTAGRAM]: "Instagram",
  [STATEMENT_TYPE.TIK_TOK]: "TikTok",
  [STATEMENT_TYPE.GITHUB]: "GitHub",
  [STATEMENT_TYPE.REDDIT]: "Reddit",
  [STATEMENT_TYPE.WEIBO]: "Weibo",
  [STATEMENT_TYPE.SUBSTACK]: "Substack",
  [STATEMENT_TYPE.MEDIUM]: "Medium",
  [STATEMENT_TYPE.MIRROR_XYZ]: "Mirror.xyz",
  [STATEMENT_TYPE.YOUTUBE]: "YouTube",
  [STATEMENT_TYPE.DISCORD]: "Discord",
  [STATEMENT_TYPE.TELEGRAM]: "Telegram",
  [STATEMENT_TYPE.WECHAT]: "WeChat",
  [STATEMENT_TYPE.PHONE]: "Phone",
  [STATEMENT_TYPE.EMAIL]: "Email",
  [STATEMENT_TYPE.WEBSITE]: "Website",
  [STATEMENT_TYPE.LINK]: "Link",
  [STATEMENT_TYPE.BIO]: "About",
  [STATEMENT_TYPE.SUPER_RARE]: "TODO",
  [STATEMENT_TYPE.FOUNDATION]: "TODO",
  [STATEMENT_TYPE.MAKERS_PLACE]: "TODO",
  [STATEMENT_TYPE.KNOWN_ORIGIN]: "TODO",
  [STATEMENT_TYPE.PEPE_WTF]: "TODO",
  [STATEMENT_TYPE.OPENSEA]: "TODO",
  [STATEMENT_TYPE.ART_BLOCKS]: "TODO",
  [STATEMENT_TYPE.DECA_ART]: "TODO",
  [STATEMENT_TYPE.ON_CYBER]: "TODO",
  [STATEMENT_TYPE.THE_LINE]: "TODO",
};

export const STATEMENT_INPUT_PLACEHOLDER: Record<STATEMENT_TYPE, string> = {
  [STATEMENT_TYPE.X]: "https://www.x.com/username",
  [STATEMENT_TYPE.FACEBOOK]: "https://www.facebook.com/username",
  [STATEMENT_TYPE.LINKED_IN]: "https://www.linkedin.com/username",
  [STATEMENT_TYPE.INSTAGRAM]: "https://www.instagram.com/username",
  [STATEMENT_TYPE.TIK_TOK]: "https://www.tiktok.com/@username",
  [STATEMENT_TYPE.GITHUB]: "https://www.github.com/username",
  [STATEMENT_TYPE.REDDIT]: "https://www.reddit.com/u/username",
  [STATEMENT_TYPE.WEIBO]: "https://www.weibo.com/username",
  [STATEMENT_TYPE.SUBSTACK]: "https://username.substack.com/",
  [STATEMENT_TYPE.MEDIUM]: "https://www.medium.com/@username",
  [STATEMENT_TYPE.MIRROR_XYZ]: "https://www.mirror.xyz/username",
  [STATEMENT_TYPE.YOUTUBE]: "https://www.youtube.com/username",
  [STATEMENT_TYPE.DISCORD]: "Discord username",
  [STATEMENT_TYPE.TELEGRAM]: "Telegram username",
  [STATEMENT_TYPE.WECHAT]: "WeChat username",
  [STATEMENT_TYPE.PHONE]: "Phone",
  [STATEMENT_TYPE.EMAIL]: "Email",
  [STATEMENT_TYPE.WEBSITE]: "Website (starting with http or https)",
  [STATEMENT_TYPE.LINK]: "Website (starting with http or https)",
  [STATEMENT_TYPE.BIO]: "About",
  [STATEMENT_TYPE.SUPER_RARE]: "TODO",
  [STATEMENT_TYPE.FOUNDATION]: "TODO",
  [STATEMENT_TYPE.MAKERS_PLACE]: "TODO",
  [STATEMENT_TYPE.KNOWN_ORIGIN]: "TODO",
  [STATEMENT_TYPE.PEPE_WTF]: "TODO",
  [STATEMENT_TYPE.OPENSEA]: "TODO",
  [STATEMENT_TYPE.ART_BLOCKS]: "TODO",
  [STATEMENT_TYPE.DECA_ART]: "TODO",
  [STATEMENT_TYPE.ON_CYBER]: "TODO",
  [STATEMENT_TYPE.THE_LINE]: "TODO",
};

export const STATEMENT_INPUT_INITIAL_VALUE: Record<STATEMENT_TYPE, string> = {
  [STATEMENT_TYPE.X]: "https://www.x.com/",
  [STATEMENT_TYPE.FACEBOOK]: "https://www.facebook.com/",
  [STATEMENT_TYPE.LINKED_IN]: "https://www.linkedin.com/in/",
  [STATEMENT_TYPE.INSTAGRAM]: "https://www.instagram.com/",
  [STATEMENT_TYPE.TIK_TOK]: "https://www.tiktok.com/@",
  [STATEMENT_TYPE.GITHUB]: "https://www.github.com/",
  [STATEMENT_TYPE.REDDIT]: "https://www.reddit.com/u/",
  [STATEMENT_TYPE.WEIBO]: "https://www.weibo.com/",
  [STATEMENT_TYPE.SUBSTACK]: "https://",
  [STATEMENT_TYPE.MEDIUM]: "https://www.medium.com/@",
  [STATEMENT_TYPE.MIRROR_XYZ]: "https://www.mirror.xyz/",
  [STATEMENT_TYPE.YOUTUBE]: "https://www.youtube.com/",
  [STATEMENT_TYPE.DISCORD]: "",
  [STATEMENT_TYPE.TELEGRAM]: "",
  [STATEMENT_TYPE.WECHAT]: "",
  [STATEMENT_TYPE.PHONE]: "",
  [STATEMENT_TYPE.EMAIL]: "",
  [STATEMENT_TYPE.WEBSITE]: "https://",
  [STATEMENT_TYPE.LINK]: "https://",
  [STATEMENT_TYPE.BIO]: "",
  [STATEMENT_TYPE.SUPER_RARE]: "TODO",
  [STATEMENT_TYPE.FOUNDATION]: "TODO",
  [STATEMENT_TYPE.MAKERS_PLACE]: "TODO",
  [STATEMENT_TYPE.KNOWN_ORIGIN]: "TODO",
  [STATEMENT_TYPE.PEPE_WTF]: "TODO",
  [STATEMENT_TYPE.OPENSEA]: "TODO",
  [STATEMENT_TYPE.ART_BLOCKS]: "TODO",
  [STATEMENT_TYPE.DECA_ART]: "TODO",
  [STATEMENT_TYPE.ON_CYBER]: "TODO",
  [STATEMENT_TYPE.THE_LINE]: "TODO",
};

export const SOCIAL_MEDIA_ACCOUNT_STATEMENT_TYPES = [
  STATEMENT_TYPE.X,
  STATEMENT_TYPE.FACEBOOK,
  STATEMENT_TYPE.LINKED_IN,
  STATEMENT_TYPE.INSTAGRAM,
  STATEMENT_TYPE.TIK_TOK,
  STATEMENT_TYPE.GITHUB,
  STATEMENT_TYPE.REDDIT,
  STATEMENT_TYPE.WEIBO,
  STATEMENT_TYPE.SUBSTACK,
  STATEMENT_TYPE.MEDIUM,
  STATEMENT_TYPE.MIRROR_XYZ,
  STATEMENT_TYPE.YOUTUBE,
] as const;

export type SOCIAL_MEDIA_ACCOUNT_STATEMENT_TYPE =
  (typeof SOCIAL_MEDIA_ACCOUNT_STATEMENT_TYPES)[number];

export const NFT_ACCOUNTS_STATEMENT_TYPES = [
  STATEMENT_TYPE.SUPER_RARE,
  STATEMENT_TYPE.FOUNDATION,
  STATEMENT_TYPE.MAKERS_PLACE,
  STATEMENT_TYPE.KNOWN_ORIGIN,
  STATEMENT_TYPE.PEPE_WTF,
  STATEMENT_TYPE.OPENSEA,
  STATEMENT_TYPE.ART_BLOCKS,
  STATEMENT_TYPE.DECA_ART,
  STATEMENT_TYPE.ON_CYBER,
  STATEMENT_TYPE.THE_LINE,
] as const;

export type NFT_ACCOUNTS_STATEMENT_TYPE =
  (typeof NFT_ACCOUNTS_STATEMENT_TYPES)[number];

export const CONTACT_STATEMENT_TYPES = [
  STATEMENT_TYPE.DISCORD,
  STATEMENT_TYPE.TELEGRAM,
  STATEMENT_TYPE.WECHAT,
  STATEMENT_TYPE.PHONE,
  STATEMENT_TYPE.EMAIL,
  STATEMENT_TYPE.WEBSITE,
] as const;

export type CONTACT_STATEMENT_TYPE = (typeof CONTACT_STATEMENT_TYPES)[number];

export const SOCIAL_MEDIA_VERIFICATION_POSTS_STATEMENT_TYPES = [
  STATEMENT_TYPE.LINK,
] as const;

export type SOCIAL_MEDIA_VERIFICATION_POSTS_STATEMENT_TYPE =
  (typeof SOCIAL_MEDIA_VERIFICATION_POSTS_STATEMENT_TYPES)[number];
