export enum STATEMENT_GROUP {
  CONTACT = "CONTACT",
  SOCIAL_MEDIA_ACCOUNT = "SOCIAL_MEDIA_ACCOUNT",
  SOCIAL_MEDIA_VERIFICATION_POST = "SOCIAL_MEDIA_VERIFICATION_POST",
}

export enum STATEMENT_TYPE {
  X = "X",
  FACEBOOK = "FACEBOOK",
  LINKED_IN = "LINKED_IN",
  INSTAGRAM = "INSTAGRAM",
  TIK_TOK = "TIK_TOK",
  GITHUB = "GITHUB",
  REDDIT = "REDDIT",
  WEIBO = "WEIBO",
  SUBSTACK = "SUBSTACK",
  MEDIUM = "MEDIUM",
  MIRROR_XYZ = "MIRROR_XYZ",
  YOUTUBE = "YOUTUBE",
  DISCORD = "DISCORD",
  TELEGRAM = "TELEGRAM",
  WECHAT = "WECHAT",
  PHONE = "PHONE",
  EMAIL = "EMAIL",
  WEBSITE = "WEBSITE",
  LINK = "LINK",
}

export const STATEMENT_TITLE: Record<STATEMENT_TYPE, string> = {
  [STATEMENT_TYPE.X]: "X",
  [STATEMENT_TYPE.FACEBOOK]: "Facebook",
  [STATEMENT_TYPE.LINKED_IN]: "LinkedIn",
  [STATEMENT_TYPE.INSTAGRAM]: "Instagram",
  [STATEMENT_TYPE.TIK_TOK]: "TikTok",
  [STATEMENT_TYPE.GITHUB]: "GitHub",
  [STATEMENT_TYPE.REDDIT]: "Reddit",
  [STATEMENT_TYPE.WEIBO]: "Weibo",
  [STATEMENT_TYPE.SUBSTACK]: "Substack",
  [STATEMENT_TYPE.MEDIUM]: "Medium",
  [STATEMENT_TYPE.MIRROR_XYZ]: "Mirror.xyz",
  [STATEMENT_TYPE.YOUTUBE]: "YouTube",
  [STATEMENT_TYPE.DISCORD]: "Discord",
  [STATEMENT_TYPE.TELEGRAM]: "Telegram",
  [STATEMENT_TYPE.WECHAT]: "WeChat",
  [STATEMENT_TYPE.PHONE]: "Phone",
  [STATEMENT_TYPE.EMAIL]: "Email",
  [STATEMENT_TYPE.WEBSITE]: "Website",
  [STATEMENT_TYPE.LINK]: "Link",
};

export const SOCIAL_MEDIA_ACCOUNT_STATEMENT_TYPES = [
  STATEMENT_TYPE.X,
  STATEMENT_TYPE.FACEBOOK,
  STATEMENT_TYPE.LINKED_IN,
  STATEMENT_TYPE.INSTAGRAM,
  STATEMENT_TYPE.TIK_TOK,
  STATEMENT_TYPE.GITHUB,
  STATEMENT_TYPE.REDDIT,
  STATEMENT_TYPE.WEIBO,
  STATEMENT_TYPE.SUBSTACK,
  STATEMENT_TYPE.MEDIUM,
  STATEMENT_TYPE.MIRROR_XYZ,
  STATEMENT_TYPE.YOUTUBE,
] as const;

export type SOCIAL_MEDIA_ACCOUNT_STATEMENT_TYPE =
  (typeof SOCIAL_MEDIA_ACCOUNT_STATEMENT_TYPES)[number];

export const CONTACT_STATEMENT_TYPES = [
  STATEMENT_TYPE.DISCORD,
  STATEMENT_TYPE.TELEGRAM,
  STATEMENT_TYPE.WECHAT,
  STATEMENT_TYPE.PHONE,
  STATEMENT_TYPE.EMAIL,
  STATEMENT_TYPE.WEBSITE,
] as const;

export type CONTACT_STATEMENT_TYPE = (typeof CONTACT_STATEMENT_TYPES)[number];

export const SOCIAL_MEDIA_VERIFICATION_POSTS_STATEMENT_TYPES = [
  STATEMENT_TYPE.LINK,
] as const;

export type SOCIAL_MEDIA_VERIFICATION_POSTS_STATEMENT_TYPE =
  (typeof SOCIAL_MEDIA_VERIFICATION_POSTS_STATEMENT_TYPES)[number];
