import { getRandomObjectId, isEthereumAddress, isAutoGeneratedHandle, truncateTextMiddle, formatNumber } from '../../helpers/AllowlistToolHelpers';

test('getRandomObjectId returns 24 hex chars', () => {
  const id = getRandomObjectId();
  expect(id).toMatch(/^[0-9a-f]{24}$/);
});

test('isEthereumAddress validates properly', () => {
  expect(isEthereumAddress('0x' + 'a'.repeat(40))).toBe(true);
  expect(isEthereumAddress('0x123')).toBe(false);
  expect(isEthereumAddress(123 as any)).toBe(false);
});

test('isAutoGeneratedHandle detects pattern', () => {
  const addr = '0x' + 'b'.repeat(40);
  expect(isAutoGeneratedHandle(`id-${addr}`)).toBe(true);
  expect(isAutoGeneratedHandle('id-notanaddress')).toBe(false);
  expect(isAutoGeneratedHandle('other')).toBe(false);
});

test('truncateTextMiddle shortens text', () => {
  expect(truncateTextMiddle('abcdef', 4)).toBe('a...');
  expect(truncateTextMiddle('short', 10)).toBe('short');
});

test('formatNumber formats with suffix', () => {
  expect(formatNumber(5)).toBe('5.000');
  expect(formatNumber(55)).toBe('55.00');
  expect(formatNumber(5555)).toBe('5555');
  expect(formatNumber(123456)).toBe('123.5k');
});
