version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 6
    versioning-strategy: "increase"
    labels:
      - "dependencies"
      - "dependabot"
    groups:
      dev-patch:
        dependency-type: "development"
        update-types:
          - "patch"
      dev-minor:
        dependency-type: "development"
        update-types:
          - "minor"
      runtime-patch:
        dependency-type: "production"
        update-types:
          - "patch"
      runtime-minor:
        dependency-type: "production"
        update-types:
          - "minor"
