export const EMOJI_MAP = [
  {
    id: "6529",
    name: "6529",
    category: "6529",
    emojis: [
      "6529black",
      "6529spin",
      "6529white",
      "bb",
      "chalice",
      "glasses1",
      "glasses2",
      "gm",
      "gm1",
      "gmeme",
      "gmrotate",
      "gmspin",
      "jumpmfer",
      "mfer",
      "om_electric",
      "om_freedom_roll",
      "om_glitch",
      "om_gm",
      "om_gm_lock",
      "om_gm_water",
      "om_seize",
      "om_velvet",
      "omblack",
      "omshake",
      "omspin",
      "omspiral",
      "omwhite",
      "punk",
      "punkshake",
      "sunshine",
      "sunshinerotate",
      "sunshinespin",
      "theroof",
    ].map((id) => ({
      id,
      name: id,
      keywords: id.replace(/_/g, " "),
      skins: [
        {
          src: `https://d3lqz0a4bldqgf.cloudfront.net/6529-emoji/${id}.webp`,
        },
      ],
    })),
  },
];
