export const DELEGATION_ABI = [
  { inputs: [], stateMutability: "nonpayable", type: "constructor" },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "from", type: "address" },
      {
        indexed: true,
        internalType: "address",
        name: "collectionAddress",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "delegationAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "useCase",
        type: "uint256",
      },
      { indexed: false, internalType: "bool", name: "allTokens", type: "bool" },
      {
        indexed: false,
        internalType: "uint256",
        name: "_tokenId",
        type: "uint256",
      },
    ],
    name: "RegisterDelegation",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "delegator",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "collectionAddress",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "delegationAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "useCase",
        type: "uint256",
      },
      { indexed: false, internalType: "bool", name: "allTokens", type: "bool" },
      {
        indexed: false,
        internalType: "uint256",
        name: "_tokenId",
        type: "uint256",
      },
    ],
    name: "RegisterDelegationUsingSubDelegation",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "from", type: "address" },
      {
        indexed: true,
        internalType: "address",
        name: "collectionAddress",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "delegationAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "useCase",
        type: "uint256",
      },
    ],
    name: "RevokeDelegation",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "delegator",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "collectionAddress",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "delegationAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "useCase",
        type: "uint256",
      },
    ],
    name: "RevokeDelegationUsingSubDelegation",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "from", type: "address" },
      {
        indexed: true,
        internalType: "address",
        name: "collectionAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "olddelegationAddress",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newdelegationAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "useCase",
        type: "uint256",
      },
      { indexed: false, internalType: "bool", name: "allTokens", type: "bool" },
      {
        indexed: false,
        internalType: "uint256",
        name: "_tokenId",
        type: "uint256",
      },
    ],
    name: "UpdateDelegation",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "_collectionAddresses",
        type: "address[]",
      },
      {
        internalType: "address[]",
        name: "_delegationAddresses",
        type: "address[]",
      },
      { internalType: "uint256[]", name: "_expiryDates", type: "uint256[]" },
      { internalType: "uint256[]", name: "_useCases", type: "uint256[]" },
      { internalType: "bool[]", name: "_allTokens", type: "bool[]" },
      { internalType: "uint256[]", name: "_tokenIds", type: "uint256[]" },
    ],
    name: "batchDelegations",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "_collectionAddresses",
        type: "address[]",
      },
      {
        internalType: "address[]",
        name: "_delegationAddresses",
        type: "address[]",
      },
      { internalType: "uint256[]", name: "_useCases", type: "uint256[]" },
    ],
    name: "batchRevocations",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_wallet1", type: "address" },
      { internalType: "address", name: "_wallet2", type: "address" },
      { internalType: "address", name: "_collectionAddress", type: "address" },
    ],
    name: "checkConsolidationStatus",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    name: "collectionLock",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    name: "collectionUsecaseLock",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    name: "collectionsRegisteredPerDelAdd",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    name: "collectionsRegisteredPerDelegator",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "", type: "bytes32" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    name: "delegationAddressHashes",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "", type: "bytes32" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    name: "delegatorHashes",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "", type: "bytes32" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    name: "globalDelegationHashes",
    outputs: [
      { internalType: "address", name: "delegatorAddress", type: "address" },
      { internalType: "address", name: "delegationAddress", type: "address" },
      { internalType: "uint256", name: "registeredDate", type: "uint256" },
      { internalType: "uint256", name: "expiryDate", type: "uint256" },
      { internalType: "bool", name: "allTokens", type: "bool" },
      { internalType: "uint256", name: "tokens", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "globalLock",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_collectionAddress", type: "address" },
      { internalType: "address", name: "_delegationAddress", type: "address" },
      { internalType: "uint256", name: "_expiryDate", type: "uint256" },
      { internalType: "uint256", name: "_useCase", type: "uint256" },
      { internalType: "bool", name: "_allTokens", type: "bool" },
      { internalType: "uint256", name: "_tokenId", type: "uint256" },
    ],
    name: "registerDelegationAddress",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_delegatorAddress", type: "address" },
      { internalType: "address", name: "_collectionAddress", type: "address" },
      { internalType: "address", name: "_delegationAddress", type: "address" },
      { internalType: "uint256", name: "_expiryDate", type: "uint256" },
      { internalType: "uint256", name: "_useCase", type: "uint256" },
      { internalType: "bool", name: "_allTokens", type: "bool" },
      { internalType: "uint256", name: "_tokenId", type: "uint256" },
    ],
    name: "registerDelegationAddressUsingSubDelegation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_delegatorAddress", type: "address" },
      { internalType: "address", name: "_collectionAddress", type: "address" },
      { internalType: "uint256", name: "_date", type: "uint256" },
      { internalType: "uint256", name: "_useCase", type: "uint256" },
    ],
    name: "retrieveActiveDelegations",
    outputs: [{ internalType: "address[]", name: "", type: "address[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_delegationAddress", type: "address" },
      { internalType: "address", name: "_collectionAddress", type: "address" },
      { internalType: "uint256", name: "_date", type: "uint256" },
      { internalType: "uint256", name: "_useCase", type: "uint256" },
    ],
    name: "retrieveActiveDelegators",
    outputs: [{ internalType: "address[]", name: "", type: "address[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_delegationAddress", type: "address" },
      { internalType: "uint256", name: "_useCase", type: "uint256" },
    ],
    name: "retrieveActiveHistoryPerDelegationAddress",
    outputs: [{ internalType: "address[]", name: "", type: "address[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_delegatorAddress", type: "address" },
      { internalType: "uint256", name: "_useCase", type: "uint256" },
    ],
    name: "retrieveActiveHistoryPerDelegator",
    outputs: [{ internalType: "address[]", name: "", type: "address[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_collectionAddress", type: "address" },
      { internalType: "address", name: "_delegationAddress", type: "address" },
    ],
    name: "retrieveCollectionLockStatus",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_collectionAddress", type: "address" },
      { internalType: "address", name: "_delegationAddress", type: "address" },
      { internalType: "uint256", name: "_useCase", type: "uint256" },
    ],
    name: "retrieveCollectionUseCaseLockStatus",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_collectionAddress", type: "address" },
      { internalType: "address", name: "_delegationAddress", type: "address" },
      { internalType: "uint256", name: "_useCase", type: "uint256" },
    ],
    name: "retrieveCollectionUseCaseLockStatusOneCall",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_delegationAddress", type: "address" },
      { internalType: "address", name: "_collectionAddress", type: "address" },
      { internalType: "uint256", name: "_useCase", type: "uint256" },
    ],
    name: "retrieveDelegationAddressStatusOfDelegation",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_delegatorAddress", type: "address" },
      { internalType: "address", name: "_collectionAddress", type: "address" },
      { internalType: "uint256", name: "_useCase", type: "uint256" },
    ],
    name: "retrieveDelegationAddresses",
    outputs: [{ internalType: "address[]", name: "", type: "address[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_delegatorAddress", type: "address" },
      { internalType: "address", name: "_collectionAddress", type: "address" },
      { internalType: "uint256", name: "_useCase", type: "uint256" },
    ],
    name: "retrieveDelegationAddressesTokensIDsandExpiredDates",
    outputs: [
      { internalType: "address[]", name: "", type: "address[]" },
      { internalType: "uint256[]", name: "", type: "uint256[]" },
      { internalType: "bool[]", name: "", type: "bool[]" },
      { internalType: "uint256[]", name: "", type: "uint256[]" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_delegatorAddress", type: "address" },
      { internalType: "address", name: "_collectionAddress", type: "address" },
      { internalType: "uint256", name: "_useCase", type: "uint256" },
    ],
    name: "retrieveDelegatorStatusOfDelegation",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_delegationAddress", type: "address" },
      { internalType: "address", name: "_collectionAddress", type: "address" },
      { internalType: "uint256", name: "_useCase", type: "uint256" },
    ],
    name: "retrieveDelegators",
    outputs: [{ internalType: "address[]", name: "", type: "address[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_delegationAddress", type: "address" },
      { internalType: "address", name: "_collectionAddress", type: "address" },
      { internalType: "uint256", name: "_useCase", type: "uint256" },
    ],
    name: "retrieveDelegatorsTokensIDsandExpiredDates",
    outputs: [
      { internalType: "address[]", name: "", type: "address[]" },
      { internalType: "uint256[]", name: "", type: "uint256[]" },
      { internalType: "bool[]", name: "", type: "bool[]" },
      { internalType: "uint256[]", name: "", type: "uint256[]" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_delegationAddress", type: "address" },
      { internalType: "uint256", name: "_useCase", type: "uint256" },
    ],
    name: "retrieveFullHistoryOfDelAddress",
    outputs: [{ internalType: "address[]", name: "", type: "address[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_delegatorAddress", type: "address" },
      { internalType: "uint256", name: "_useCase", type: "uint256" },
    ],
    name: "retrieveFullHistoryOfDelegator",
    outputs: [{ internalType: "address[]", name: "", type: "address[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_delegatorAddress", type: "address" },
      { internalType: "address", name: "_collectionAddress", type: "address" },
      { internalType: "address", name: "_delegationAddress", type: "address" },
      { internalType: "uint256", name: "_useCase", type: "uint256" },
    ],
    name: "retrieveGlobalHash",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_delegationAddress", type: "address" },
    ],
    name: "retrieveGlobalLockStatus",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_delegatorAddress", type: "address" },
      { internalType: "address", name: "_collectionAddress", type: "address" },
      { internalType: "address", name: "_delegationAddress", type: "address" },
      { internalType: "uint256", name: "_useCase", type: "uint256" },
    ],
    name: "retrieveGlobalStatusOfDelegation",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_walletAddress", type: "address" },
      { internalType: "address", name: "_collectionAddress", type: "address" },
      { internalType: "uint256", name: "_useCase", type: "uint256" },
    ],
    name: "retrieveLocalHash",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_delegatorAddress", type: "address" },
      { internalType: "address", name: "_collectionAddress", type: "address" },
      { internalType: "uint256", name: "_useCase", type: "uint256" },
    ],
    name: "retrieveMostRecentDelegation",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_delegationAddress", type: "address" },
      { internalType: "address", name: "_collectionAddress", type: "address" },
      { internalType: "uint256", name: "_useCase", type: "uint256" },
    ],
    name: "retrieveMostRecentDelegator",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_delegatorAddress", type: "address" },
      { internalType: "address", name: "_collectionAddress", type: "address" },
      { internalType: "address", name: "_delegationAddress", type: "address" },
      { internalType: "uint256", name: "_date", type: "uint256" },
      { internalType: "uint256", name: "_useCase", type: "uint256" },
    ],
    name: "retrieveStatusOfActiveDelegator",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_delegatorAddress", type: "address" },
      { internalType: "address", name: "_collectionAddress", type: "address" },
      { internalType: "address", name: "_delegationAddress", type: "address" },
      { internalType: "uint256", name: "_useCase", type: "uint256" },
    ],
    name: "retrieveStatusOfMostRecentDelegation",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_delegatorAddress", type: "address" },
      { internalType: "address", name: "_collectionAddress", type: "address" },
      { internalType: "address", name: "_delegationAddress", type: "address" },
    ],
    name: "retrieveSubDelegationStatus",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_delegatorAddress", type: "address" },
      { internalType: "address", name: "_collectionAddress", type: "address" },
      { internalType: "address", name: "_delegationAddress", type: "address" },
      { internalType: "uint256", name: "_useCase", type: "uint256" },
      { internalType: "uint256", name: "_tokenId", type: "uint256" },
    ],
    name: "retrieveTokenStatus",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_collectionAddress", type: "address" },
      { internalType: "address", name: "_delegationAddress", type: "address" },
      { internalType: "uint256", name: "_useCase", type: "uint256" },
    ],
    name: "revokeDelegationAddress",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_delegatorAddress", type: "address" },
      { internalType: "address", name: "_collectionAddress", type: "address" },
      { internalType: "address", name: "_delegationAddress", type: "address" },
      { internalType: "uint256", name: "_useCase", type: "uint256" },
    ],
    name: "revokeDelegationAddressUsingSubdelegation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_collectionAddress", type: "address" },
      { internalType: "bool", name: "_status", type: "bool" },
    ],
    name: "setCollectionLock",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_collectionAddress", type: "address" },
      { internalType: "uint256", name: "_useCase", type: "uint256" },
      { internalType: "bool", name: "_status", type: "bool" },
    ],
    name: "setCollectionUsecaseLock",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bool", name: "_status", type: "bool" }],
    name: "setGlobalLock",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_collectionAddress", type: "address" },
      {
        internalType: "address",
        name: "_olddelegationAddress",
        type: "address",
      },
      {
        internalType: "address",
        name: "_newdelegationAddress",
        type: "address",
      },
      { internalType: "uint256", name: "_expiryDate", type: "uint256" },
      { internalType: "uint256", name: "_useCase", type: "uint256" },
      { internalType: "bool", name: "_allTokens", type: "bool" },
      { internalType: "uint256", name: "_tokenId", type: "uint256" },
    ],
    name: "updateDelegationAddress",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "updateUseCaseCounter",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "useCaseCounter",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
];

export const NEXT_GEN_ABI = [
  {
    inputs: [
      { internalType: "string", name: "name", type: "string" },
      { internalType: "string", name: "symbol", type: "string" },
      {
        internalType: "address",
        name: "_delegationManagementContract",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "approved",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "Approval",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "operator",
        type: "address",
      },
      { indexed: false, internalType: "bool", name: "approved", type: "bool" },
    ],
    name: "ApprovalForAll",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "from", type: "address" },
      { indexed: true, internalType: "address", name: "to", type: "address" },
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "Transfer",
    type: "event",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_collectionID", type: "uint256" },
      {
        internalType: "address",
        name: "_collectionArtistAddress",
        type: "address",
      },
      { internalType: "uint256", name: "_collectionMintCost", type: "uint256" },
      {
        internalType: "uint256",
        name: "_maxCollectionPurchases",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_collectionTotalSupply",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_collectionSalesPercentage",
        type: "uint256",
      },
    ],
    name: "addCollectionData",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "adminPermissions",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address[]", name: "_recipients", type: "address[]" },
      { internalType: "uint256[]", name: "TDH", type: "uint256[]" },
      { internalType: "uint256[][]", name: "memesIds", type: "uint256[][]" },
      { internalType: "uint256", name: "_collectionID", type: "uint256" },
      { internalType: "uint256", name: "_numberOfTokens", type: "uint256" },
    ],
    name: "airDropTokens",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "to", type: "address" },
      { internalType: "uint256", name: "tokenId", type: "uint256" },
    ],
    name: "approve",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_collectionID", type: "uint256" },
      { internalType: "string", name: "_signature", type: "string" },
    ],
    name: "artistSignature",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "artistsSignatures",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "owner", type: "address" }],
    name: "balanceOf",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_collectionID", type: "uint256" },
      { internalType: "uint256", name: "_tokenId", type: "uint256" },
    ],
    name: "burn",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "burnAmount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_burnCollectionID", type: "uint256" },
      { internalType: "uint256", name: "_tokenId", type: "uint256" },
      { internalType: "uint256", name: "_mintCollectionID", type: "uint256" },
    ],
    name: "burnToMint",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_collectionID", type: "uint256" },
      { internalType: "bool", name: "_status", type: "bool" },
    ],
    name: "changeCollectionMintStatus",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_collectionID", type: "uint256" },
      { internalType: "bool", name: "_status", type: "bool" },
    ],
    name: "changeMetadataView",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    name: "collectionAdmin",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "collectionTotalAmount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "_collectionName", type: "string" },
      { internalType: "string", name: "_collectionArtist", type: "string" },
      {
        internalType: "string",
        name: "_collectionDescription",
        type: "string",
      },
      { internalType: "string", name: "_collectionWebsite", type: "string" },
      { internalType: "string", name: "_collectionLicense", type: "string" },
      { internalType: "string", name: "_collectionBaseURI", type: "string" },
      { internalType: "string", name: "_collectionLibrary", type: "string" },
      { internalType: "string[]", name: "_collectionScript", type: "string[]" },
    ],
    name: "createCollection",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
    name: "getApproved",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_burnCollectionID", type: "uint256" },
      { internalType: "uint256", name: "_mintCollectionID", type: "uint256" },
      { internalType: "bool", name: "_status", type: "bool" },
    ],
    name: "initializeBurn",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "owner", type: "address" },
      { internalType: "address", name: "operator", type: "address" },
    ],
    name: "isApprovedForAll",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_collectionID", type: "uint256" },
      { internalType: "uint256", name: "_numberOfTokens", type: "uint256" },
      { internalType: "uint256", name: "_maxAllowance", type: "uint256" },
      { internalType: "uint256", name: "TDH", type: "uint256" },
      { internalType: "uint256[]", name: "memesIds", type: "uint256[]" },
      { internalType: "address", name: "_mintTo", type: "address" },
      { internalType: "bytes32[]", name: "merkleProof", type: "bytes32[]" },
      { internalType: "address", name: "_delegator", type: "address" },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "name",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "newCollectionIndex",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "onchainMetadata",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
    name: "ownerOf",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_collectionID", type: "uint256" },
    ],
    name: "payArtist",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_admin", type: "address" },
      { internalType: "bool", name: "_status", type: "bool" },
    ],
    name: "registerAdmin",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_collectionID", type: "uint256" },
      { internalType: "address", name: "_address", type: "address" },
      { internalType: "bool", name: "_status", type: "bool" },
    ],
    name: "registerCollectionAdmin",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_collectionID", type: "uint256" },
    ],
    name: "retrieveCollectionAdditionalData",
    outputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "bool", name: "", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_collectionID", type: "uint256" },
    ],
    name: "retrieveCollectionInfo",
    outputs: [
      { internalType: "string", name: "", type: "string" },
      { internalType: "string", name: "", type: "string" },
      { internalType: "string", name: "", type: "string" },
      { internalType: "string", name: "", type: "string" },
      { internalType: "string", name: "", type: "string" },
      { internalType: "string", name: "", type: "string" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_collectionID", type: "uint256" },
    ],
    name: "retrieveCollectionLibraryAndScript",
    outputs: [
      { internalType: "string", name: "", type: "string" },
      { internalType: "string[]", name: "", type: "string[]" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_collectionID", type: "uint256" },
    ],
    name: "retrieveCollectionPhases",
    outputs: [
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "bytes32", name: "", type: "bytes32" },
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "uint256[]", name: "", type: "uint256[]" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
    name: "retrieveGenerativeScript",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
    name: "retrieveMemesIds",
    outputs: [{ internalType: "uint256[]", name: "", type: "uint256[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_collectionID", type: "uint256" },
      { internalType: "address", name: "_address", type: "address" },
    ],
    name: "retrieveTokensPerAddress",
    outputs: [
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "from", type: "address" },
      { internalType: "address", name: "to", type: "address" },
      { internalType: "uint256", name: "tokenId", type: "uint256" },
    ],
    name: "safeTransferFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "from", type: "address" },
      { internalType: "address", name: "to", type: "address" },
      { internalType: "uint256", name: "tokenId", type: "uint256" },
      { internalType: "bytes", name: "data", type: "bytes" },
    ],
    name: "safeTransferFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "operator", type: "address" },
      { internalType: "bool", name: "approved", type: "bool" },
    ],
    name: "setApprovalForAll",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_collectionID", type: "uint256" },
      { internalType: "uint256", name: "_allowlistStartTime", type: "uint256" },
      { internalType: "uint256", name: "_allowlistEndTime", type: "uint256" },
      { internalType: "uint256", name: "_publicStartTime", type: "uint256" },
      { internalType: "uint256", name: "_publicEndTime", type: "uint256" },
      { internalType: "bytes32", name: "_merkleRoot", type: "bytes32" },
      { internalType: "uint256[]", name: "_memesIDs", type: "uint256[]" },
    ],
    name: "setCollectionPhases",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes4", name: "interfaceId", type: "bytes4" }],
    name: "supportsInterface",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "symbol",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "tdhBalance",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "index", type: "uint256" }],
    name: "tokenByIndex",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "owner", type: "address" },
      { internalType: "uint256", name: "index", type: "uint256" },
    ],
    name: "tokenOfOwnerByIndex",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "tokenToHash",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
    name: "tokenURI",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalSupply",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_collectionID", type: "uint256" },
    ],
    name: "totalSupplyOfCollection",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "from", type: "address" },
      { internalType: "address", name: "to", type: "address" },
      { internalType: "uint256", name: "tokenId", type: "uint256" },
    ],
    name: "transferFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_collectionID", type: "uint256" },
      {
        internalType: "address",
        name: "_newCollectionArtistAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_newCollectionMintCost",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_newMaxCollectionPurchases",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_newCollectionSalesPercentage",
        type: "uint256",
      },
    ],
    name: "updateCollectionAdditionalData",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_collectionID", type: "uint256" },
      { internalType: "string", name: "_newCollectionName", type: "string" },
      { internalType: "string", name: "_newCollectionArtist", type: "string" },
      {
        internalType: "string",
        name: "_newCollectionDescription",
        type: "string",
      },
      { internalType: "string", name: "_newCollectionWebsite", type: "string" },
      { internalType: "string", name: "_newCollectionLicense", type: "string" },
      { internalType: "string", name: "_newCollectionBaseURI", type: "string" },
      { internalType: "string", name: "_newCollectionLibrary", type: "string" },
      {
        internalType: "string[]",
        name: "_newCollectionScript",
        type: "string[]",
      },
    ],
    name: "updateCollectionInfo",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_collectionID", type: "uint256" },
      { internalType: "uint256", name: "_index", type: "uint256" },
      {
        internalType: "string",
        name: "_newCollectionIndexScript",
        type: "string",
      },
    ],
    name: "updateCollectionScriptByIndex",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_collectionID", type: "uint256" },
    ],
    name: "viewTokensIndexForCollection",
    outputs: [
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
