import reactYouMightNotNeedAnEffect from "eslint-plugin-react-you-might-not-need-an-effect";
import { createEslintConfig } from "./eslint.config.mjs";

const tightRuleOverrides = {
  "@next/next/no-css-tags": "error",
  "@next/next/no-html-link-for-pages": "error",
  "@next/next/no-img-element": "error",
  "@typescript-eslint/await-thenable": "error",
  "@typescript-eslint/consistent-type-imports": [
    "error",
    {
      prefer: "type-imports",
      fixStyle: "separate-type-imports",
    },
  ],
  "@typescript-eslint/no-confusing-void-expression": [
    "error",
    {
      ignoreArrowShorthand: true,
    },
  ],
  "@typescript-eslint/no-deprecated": "error",
  "@typescript-eslint/no-duplicate-type-constituents": "error",
  "@typescript-eslint/no-explicit-any": "error",
  "@typescript-eslint/no-floating-promises": "error",
  "@typescript-eslint/no-import-type-side-effects": "error",
  "@typescript-eslint/no-misused-promises": [
    "error",
    {
      checksVoidReturn: {
        attributes: false,
      },
    },
  ],
  "@typescript-eslint/no-redundant-type-constituents": "error",
  "@typescript-eslint/no-shadow": "error",
  "@typescript-eslint/no-unnecessary-condition": "error",
  "@typescript-eslint/no-unnecessary-type-assertion": "error",
  "@typescript-eslint/no-unnecessary-type-parameters": "error",
  "@typescript-eslint/no-unsafe-argument": "error",
  "@typescript-eslint/no-unsafe-assignment": "error",
  "@typescript-eslint/no-unsafe-call": "error",
  "@typescript-eslint/no-unsafe-enum-comparison": "error",
  "@typescript-eslint/no-unsafe-member-access": "error",
  "@typescript-eslint/no-unsafe-return": "error",
  "@typescript-eslint/prefer-nullish-coalescing": "error",
  "@typescript-eslint/prefer-optional-chain": "error",
  "@typescript-eslint/require-await": "error",
  "@typescript-eslint/restrict-template-expressions": [
    "error",
    {
      allowNumber: true,
      allowBoolean: true,
      allowNullish: false,
    },
  ],
  "@typescript-eslint/strict-boolean-expressions": [
    "error",
    {
      allowString: true,
      allowNumber: true,
      allowNullableObject: true,
      allowNullableBoolean: true,
      allowNullableString: true,
      allowNullableNumber: false,
      allowAny: false,
    },
  ],
  "@typescript-eslint/switch-exhaustiveness-check": "error",
  "@typescript-eslint/unbound-method": "error",
  "@typescript-eslint/use-unknown-in-catch-callback-variable": "error",
  "array-callback-return": [
    "error",
    {
      allowImplicit: true,
    },
  ],
  eqeqeq: ["error", "always"],
  "import/first": "error",
  "import/no-cycle": ["error", { maxDepth: 3 }],
  "import/no-duplicates": "error",
  "import/no-useless-path-segments": ["error", { noUselessIndex: true }],
  "max-depth": ["error", 4],
  "max-lines": [
    "error",
    {
      max: 750,
      skipBlankLines: true,
      skipComments: true,
    },
  ],
  "max-lines-per-function": [
    "error",
    {
      max: 150,
      skipBlankLines: true,
      skipComments: true,
    },
  ],
  "max-params": ["error", 5],
  "no-alert": "error",
  "no-else-return": ["error", { allowElseIf: false }],
  "no-nested-ternary": "error",
  "no-param-reassign": ["error", { props: false }],
  "no-useless-return": "error",
  "prefer-arrow-callback": "error",
  "prefer-const": "error",
  "promise/catch-or-return": ["error", { allowFinally: true }],
  "promise/no-nesting": "error",
  "promise/prefer-await-to-callbacks": "error",
  "react-hooks/error-boundaries": "error",
  "react-hooks/exhaustive-deps": "error",
  "react-hooks/immutability": "error",
  "react-hooks/preserve-manual-memoization": "error",
  "react-hooks/purity": "error",
  "react-hooks/refs": "error",
  "react-hooks/rules-of-hooks": "error",
  "react-hooks/set-state-in-effect": "error",
  "react/no-unescaped-entities": "error",
  "security/detect-non-literal-regexp": "error",
  "security/detect-unsafe-regex": "error",
  "sonarjs/cognitive-complexity": ["error", 15],
  "sonarjs/no-collapsible-if": "error",
  "sonarjs/no-duplicate-string": ["error", { threshold: 4 }],
  "sonarjs/no-ignored-return": "error",
  "sonarjs/no-nested-conditional": "error",
  "sonarjs/no-redundant-jump": "error",
  "sonarjs/prefer-immediate-return": "error",
  "sonarjs/prefer-single-boolean-return": "error",
  "tailwindcss/enforces-shorthand": "error",
  "tailwindcss/no-contradicting-classname": "error",
  "tailwindcss/no-unnecessary-arbitrary-value": "error",
};

export default createEslintConfig({
  rulesOverride: tightRuleOverrides,
  extraPlugins: {
    "react-you-might-not-need-an-effect": reactYouMightNotNeedAnEffect,
  },
  additionalConfigs: [
    {
      files: ["**/*.tsx", "**/*.jsx"],
      rules: {
        "max-lines-per-function": "off",
      },
    },
    reactYouMightNotNeedAnEffect.configs.strict,
  ],
  includeTestResultsIgnore: false,
  reactCompilerRule: "error",
});
