import reactYouMightNotNeedAnEffect from "eslint-plugin-react-you-might-not-need-an-effect";
import { baseGlobalIgnores, createEslintConfig } from "./eslint.config.mjs";

const tightGlobalIgnores = baseGlobalIgnores.filter(
  (pattern) => pattern !== "**/test-results/**"
);

const tightRuleOverrides = {
  // Preserve every rule explicitly enabled by the legacy tight config. Some of
  // these currently match baseRules, but tight lint must not silently weaken if
  // the shared base is relaxed later.
  "@next/next/no-sync-scripts": "error",
  "@next/next/google-font-display": "error",
  "@next/next/google-font-preconnect": "error",
  "@next/next/no-page-custom-font": "error",
  "@next/next/no-head-element": "error",
  "@next/next/next-script-for-ga": "error",
  "@next/next/inline-script-id": "error",
  "@next/next/no-before-interactive-script-outside-document": "error",
  "@next/next/no-script-component-in-head": "error",
  "@next/next/no-document-import-in-page": "error",
  "@next/next/no-head-import-in-document": "error",
  "@next/next/no-duplicate-head": "error",
  "@next/next/no-title-in-document-head": "error",
  "@next/next/no-styled-jsx-in-document": "error",
  "@next/next/no-typos": "error",
  "@next/next/no-assign-module-variable": "error",
  "@next/next/no-unwanted-polyfillio": "error",
  "@next/next/no-async-client-component": "error",
  "@next/next/no-css-tags": "error",
  "@next/next/no-html-link-for-pages": "error",
  "@next/next/no-img-element": "error",
  "@typescript-eslint/await-thenable": "error",
  "@typescript-eslint/consistent-type-imports": [
    "error",
    {
      prefer: "type-imports",
      fixStyle: "separate-type-imports",
    },
  ],
  "@typescript-eslint/consistent-type-exports": [
    "error",
    {
      fixMixedExportsWithInlineTypeSpecifier: true,
    },
  ],
  "@typescript-eslint/no-array-delete": "error",
  "@typescript-eslint/no-base-to-string": "error",
  "@typescript-eslint/no-confusing-void-expression": [
    "error",
    {
      ignoreArrowShorthand: true,
    },
  ],
  "@typescript-eslint/no-deprecated": "error",
  "@typescript-eslint/no-duplicate-enum-values": "error",
  "@typescript-eslint/no-duplicate-type-constituents": "error",
  "@typescript-eslint/no-explicit-any": "error",
  "@typescript-eslint/no-floating-promises": "error",
  "@typescript-eslint/no-for-in-array": "error",
  "@typescript-eslint/no-import-type-side-effects": "error",
  "@typescript-eslint/no-misused-promises": [
    "error",
    {
      checksVoidReturn: {
        attributes: false,
      },
    },
  ],
  "@typescript-eslint/no-mixed-enums": "error",
  "@typescript-eslint/no-unused-vars": "off",
  "@typescript-eslint/no-redundant-type-constituents": "error",
  "@typescript-eslint/no-shadow": "error",
  "@typescript-eslint/no-unnecessary-condition": "error",
  "@typescript-eslint/no-unnecessary-type-assertion": "error",
  "@typescript-eslint/no-unnecessary-type-parameters": "error",
  "@typescript-eslint/no-unsafe-argument": "error",
  "@typescript-eslint/no-unsafe-assignment": "error",
  "@typescript-eslint/no-unsafe-call": "error",
  "@typescript-eslint/no-unsafe-enum-comparison": "error",
  "@typescript-eslint/no-unsafe-member-access": "error",
  "@typescript-eslint/no-unsafe-return": "error",
  "@typescript-eslint/only-throw-error": "error",
  "@typescript-eslint/prefer-as-const": "error",
  "@typescript-eslint/prefer-nullish-coalescing": "error",
  "@typescript-eslint/prefer-optional-chain": "error",
  "@typescript-eslint/require-await": "error",
  "@typescript-eslint/restrict-plus-operands": "error",
  "@typescript-eslint/restrict-template-expressions": [
    "error",
    {
      allowNumber: true,
      allowBoolean: true,
      allowNullish: false,
    },
  ],
  "@typescript-eslint/strict-boolean-expressions": [
    "error",
    {
      allowString: true,
      allowNumber: true,
      allowNullableObject: true,
      allowNullableBoolean: true,
      allowNullableString: true,
      allowNullableNumber: false,
      allowAny: false,
    },
  ],
  "@typescript-eslint/switch-exhaustiveness-check": "error",
  "@typescript-eslint/unbound-method": "error",
  "@typescript-eslint/use-unknown-in-catch-callback-variable": "error",
  "array-callback-return": [
    "error",
    {
      allowImplicit: true,
    },
  ],
  eqeqeq: ["error", "always"],
  "import/first": "error",
  "import/no-cycle": ["error", { maxDepth: 3 }],
  "import/no-duplicates": "error",
  "import/no-extraneous-dependencies": [
    "error",
    {
      devDependencies: [
        "**/*.test.{ts,tsx}",
        "**/*.spec.{ts,tsx}",
        "**/tests/**",
        "**/__tests__/**",
        "**/e2e/**",
        "**/*.config.{js,ts,mjs}",
        "**/scripts/**",
      ],
    },
  ],
  "import/no-mutable-exports": "error",
  "import/no-relative-packages": "error",
  "import/no-self-import": "error",
  "import/no-useless-path-segments": ["error", { noUselessIndex: true }],
  "max-depth": ["error", 4],
  "max-lines": [
    "error",
    {
      max: 750,
      skipBlankLines: true,
      skipComments: true,
    },
  ],
  "max-lines-per-function": [
    "error",
    {
      max: 150,
      skipBlankLines: true,
      skipComments: true,
    },
  ],
  "max-params": ["error", 5],
  "no-alert": "error",
  "no-array-constructor": "error",
  "no-console": ["error", { allow: ["warn", "error"] }],
  "no-debugger": "error",
  "no-else-return": ["error", { allowElseIf: false }],
  "no-lonely-if": "error",
  "no-nested-ternary": "error",
  "no-param-reassign": ["error", { props: false }],
  "no-return-assign": "error",
  "no-sequences": "error",
  "no-shadow": "off",
  "no-unneeded-ternary": "error",
  "no-unused-expressions": [
    "error",
    { allowShortCircuit: true, allowTernary: true },
  ],
  "no-useless-return": "error",
  "no-var": "error",
  "prefer-arrow-callback": "error",
  "prefer-const": "error",
  "prefer-rest-params": "error",
  "prefer-spread": "error",
  "promise/always-return": ["error", { ignoreLastCallback: true }],
  "promise/catch-or-return": ["error", { allowFinally: true }],
  "promise/no-callback-in-promise": "error",
  "promise/no-multiple-resolved": "error",
  "promise/no-new-statics": "error",
  "promise/no-nesting": "error",
  "promise/no-promise-in-callback": "error",
  "promise/no-return-in-finally": "error",
  "promise/no-return-wrap": "error",
  "promise/param-names": "error",
  "promise/prefer-await-to-callbacks": "error",
  "promise/valid-params": "error",
  "react-hooks/error-boundaries": "error",
  "react-hooks/exhaustive-deps": "error",
  "react-hooks/gating": "error",
  "react-hooks/globals": "error",
  "react-hooks/incompatible-library": "error",
  "react-hooks/immutability": "error",
  "react-hooks/preserve-manual-memoization": "error",
  "react-hooks/purity": "error",
  "react-hooks/refs": "error",
  "react-hooks/rules-of-hooks": "error",
  "react-hooks/set-state-in-effect": "error",
  "react-hooks/set-state-in-render": "error",
  "react-hooks/static-components": "error",
  "react-hooks/use-memo": "off",
  "react/no-unescaped-entities": "error",
  "require-await": "off",
  "security/detect-bidi-characters": "error",
  "security/detect-buffer-noassert": "error",
  "security/detect-child-process": "error",
  "security/detect-eval-with-expression": "error",
  "security/detect-no-csrf-before-method-override": "error",
  "security/detect-non-literal-regexp": "error",
  "security/detect-non-literal-fs-filename": "error",
  "security/detect-non-literal-require": "error",
  "security/detect-possible-timing-attacks": "error",
  "security/detect-pseudoRandomBytes": "error",
  "security/detect-unsafe-regex": "error",
  "sonarjs/cognitive-complexity": ["error", 15],
  "sonarjs/no-all-duplicated-branches": "error",
  "sonarjs/no-collapsible-if": "error",
  "sonarjs/no-collection-size-mischeck": "error",
  "sonarjs/no-duplicate-string": ["error", { threshold: 4 }],
  "sonarjs/no-duplicated-branches": "error",
  "sonarjs/no-element-overwrite": "error",
  "sonarjs/no-empty-collection": "error",
  "sonarjs/no-extra-arguments": "error",
  "sonarjs/no-gratuitous-expressions": "error",
  "sonarjs/no-ignored-return": "error",
  "sonarjs/no-identical-conditions": "error",
  "sonarjs/no-identical-expressions": "error",
  "sonarjs/no-identical-functions": "error",
  "sonarjs/no-inverted-boolean-check": "error",
  "sonarjs/no-nested-conditional": "error",
  "sonarjs/no-nested-switch": "error",
  "sonarjs/no-nested-template-literals": "error",
  "sonarjs/no-redundant-jump": "error",
  "sonarjs/no-redundant-boolean": "error",
  "sonarjs/no-same-line-conditional": "error",
  "sonarjs/no-unused-collection": "error",
  "sonarjs/no-use-of-empty-return-value": "error",
  "sonarjs/prefer-immediate-return": "error",
  "sonarjs/prefer-object-literal": "error",
  "sonarjs/prefer-single-boolean-return": "error",
  "sonarjs/prefer-while": "error",
  "tailwindcss/classnames-order": "off",
  "tailwindcss/enforces-negative-arbitrary-values": "error",
  "tailwindcss/enforces-shorthand": "error",
  "tailwindcss/no-arbitrary-value": "off",
  "tailwindcss/no-contradicting-classname": "error",
  "tailwindcss/no-custom-classname": "off",
  "tailwindcss/no-unnecessary-arbitrary-value": "error",
  "unused-imports/no-unused-imports": "error",
  "unused-imports/no-unused-vars": [
    "error",
    {
      vars: "all",
      varsIgnorePattern: "^_",
      args: "after-used",
      argsIgnorePattern: "^_",
      ignoreRestSiblings: true,
      destructuredArrayIgnorePattern: "^_",
    },
  ],
};

export default createEslintConfig({
  rulesOverride: tightRuleOverrides,
  extraPlugins: {
    "react-you-might-not-need-an-effect": reactYouMightNotNeedAnEffect,
  },
  additionalConfigs: [
    {
      files: ["**/*.tsx", "**/*.jsx"],
      rules: {
        "max-lines-per-function": "off",
      },
    },
    reactYouMightNotNeedAnEffect.configs.strict,
  ],
  globalIgnorePatterns: tightGlobalIgnores,
  reactCompilerRule: "error",
});
