allowBuilds:
  '@nestjs/core': true
  '@openapitools/openapi-generator-cli': true
  '@parcel/watcher': true
  '@reown/appkit': true
  '@sentry/cli': true
  bufferutil: true
  esbuild: true
  keccak: true
  sharp: true
  unrs-resolver: true
  utf-8-validate: true
