import { migratedWordPressTrustedHtml } from "@/components/migrated-wordpress/trusted-html";
import type { MigratedWordPressStaticPageContent } from "@/components/migrated-wordpress/types";

export const museumGenesisCryptoblotsMigratedWordPressPage = {
  source: "migrated-wordpress",
  path: "/museum/genesis/cryptoblots",
  title: "CRYPTOBLOTS",
  description:
    "Cryptoblots Daïm Aggott-Hönsch Mint Date: 12/12/2020 Artist Narrative A cryptoart collectible series to indulge the irrepressible human compulsion for pareidolia. This algorithmic homage to Hermann Rorschach's inkblot perception test will help you externali...",
  section: "Museum / Genesis",
  blocks: [
    {
      type: "html",
      html: migratedWordPressTrustedHtml(
        "<p><strong>Cryptoblots</strong><br>Daïm Aggott-Hönsch <br>Mint Date: 12/12/2020 </p>"
      ),
    },
    {
      type: "html",
      html: migratedWordPressTrustedHtml(
        "<p><strong>Artist Narrative <br></strong></p>"
      ),
    },
    {
      type: "html",
      html: migratedWordPressTrustedHtml(
        "<p>A cryptoart collectible series to indulge the irrepressible human compulsion for pareidolia. This algorithmic homage to Hermann Rorschach's inkblot perception test will help you externalize your inner world. </p>"
      ),
    },
    {
      type: "html",
      html: migratedWordPressTrustedHtml(
        "<p><strong>6529 Museum Notes</strong><br>Cryptoblots are an accessible entry point to ABC due to the large collection size. The 6529 collection contains one of each type (Unary, Binary and Ternary) and another rare color. </p>"
      ),
    },
    {
      type: "image",
      media: {
        src: "https://dnclu2fna0b2b.cloudfront.net/wp-content/uploads/2022/04/cryptoblots-560-300x300.png",
        alt: "6529.io",
        width: 300,
        height: 300,
        href: "https://dnclu2fna0b2b.cloudfront.net/wp-content/uploads/2022/04/cryptoblots-560-300x300.png",
      },
    },
    {
      type: "html",
      html: migratedWordPressTrustedHtml(
        "<p>One of only 2 Beige Brown colors (one of the rarest colors) </p>"
      ),
    },
    {
      type: "html",
      html: migratedWordPressTrustedHtml("<p>Token: 560</p>"),
    },
    {
      type: "html",
      html: migratedWordPressTrustedHtml(
        "<p><strong>Key Traits: <br></strong>Color: Beige Brown <br>Mystery Feature: Unary Cryptoblot </p>"
      ),
    },
    {
      type: "html",
      html: migratedWordPressTrustedHtml(
        "<p><strong>Rarity: <br></strong>4/1921 AR <br>11/1921 ASR <br>18/1921 RG </p>"
      ),
    },
    {
      type: "image",
      media: {
        src: "https://dnclu2fna0b2b.cloudfront.net/wp-content/uploads/2022/04/cryptoblots-1869-300x300.png",
        alt: "6529.io",
        width: 300,
        height: 300,
        href: "https://dnclu2fna0b2b.cloudfront.net/wp-content/uploads/2022/04/cryptoblots-1869-300x300.png",
      },
    },
    {
      type: "html",
      html: migratedWordPressTrustedHtml(
        "<p>A highly-detailed output that resembles a Transformer robot, 1 of 111 Ternary Cryptoblots </p>"
      ),
    },
    {
      type: "html",
      html: migratedWordPressTrustedHtml("<p>Token: 1869</p>"),
    },
    {
      type: "html",
      html: migratedWordPressTrustedHtml(
        "<p><strong>Key Traits: <br></strong>Color: Silver Gray <br>Mystery Feature: Ternary Cryptoblot </p>"
      ),
    },
    {
      type: "html",
      html: migratedWordPressTrustedHtml(
        "<p><strong>Rarity: <br></strong>51/1921 AR <br>53/1921 ASR <br>57/1921 RG </p>"
      ),
    },
    {
      type: "image",
      media: {
        src: "https://dnclu2fna0b2b.cloudfront.net/wp-content/uploads/2022/04/cryptoblots-705-300x300.png",
        alt: "6529.io",
        width: 300,
        height: 300,
      },
    },
    {
      type: "html",
      html: migratedWordPressTrustedHtml(
        "<p>Strong blue hues in this output are generated by the ‘Savoy Blue' color palette. </p>"
      ),
    },
    {
      type: "html",
      html: migratedWordPressTrustedHtml("<p>Token: 705</p>"),
    },
    {
      type: "html",
      html: migratedWordPressTrustedHtml(
        "<p><strong>Key Traits: <br></strong>Color: Savoy Blue <br>Mystery Feature: Binary Cryptoblot </p>"
      ),
    },
    {
      type: "html",
      html: migratedWordPressTrustedHtml(
        "<p><strong>Rarity: <br></strong>244/1921 ASR <br>276/1921 RG <br>291/1921 AR </p>"
      ),
    },
    {
      type: "image",
      media: {
        src: "https://dnclu2fna0b2b.cloudfront.net/wp-content/uploads/2022/04/cryptoblots-90-300x300.png",
        alt: "6529.io",
        width: 300,
        height: 300,
        href: "https://dnclu2fna0b2b.cloudfront.net/wp-content/uploads/2022/04/cryptoblots-90-300x300.png",
      },
    },
    {
      type: "html",
      html: migratedWordPressTrustedHtml(
        "<p>A ‘Moroccan Blue' color and ‘Unary Cryptoblot' mystery feature makes for a unique output. </p>"
      ),
    },
    {
      type: "html",
      html: migratedWordPressTrustedHtml("<p>Token: 900</p>"),
    },
    {
      type: "html",
      html: migratedWordPressTrustedHtml(
        "<p><strong>Key Traits: <br></strong>Color: Moroccan Blue <br>Mystery Feature: Unary Cryptoblot </p>"
      ),
    },
    {
      type: "html",
      html: migratedWordPressTrustedHtml(
        "<p><strong>Rarity: <br></strong>1215/1921 AR <br>1345/1921 ASR <br>1421/1921 RG </p>"
      ),
    },
    {
      type: "html",
      html: migratedWordPressTrustedHtml(
        "<p><strong>AR: Artacle Rarity | ASR: Artacle Statistical Rarity | RG: Rarity Guide | RS: Rarity Studio </strong></p>"
      ),
    },
  ],
} satisfies MigratedWordPressStaticPageContent;
