import { goerli } from "wagmi/chains";

export const NEXTGEN_FUNCTION_SELECTOR = "0xb85f97a0";
export const NEXTGEN_CHAIN_ID = goerli.id;
export enum FunctionSelectors {
  CREATE_COLLECTION = "0x02de55d0",
  SET_COLLECTION_DATA = "0xfb171694",
  UPDATE_COLLECTION_INFO = "0x16e7c899",
  CHANGE_METADATA_VIEW = "0xf6a85dd0",
  CHANGE_TOKEN_DATA = "0x9a8490f3", // not implemented
  UPDATE_IMAGES_AND_ATTRIBUTES = "0xad241020",
  ADD_RANDOMIZER = "0x1aab8d69",
  FREEZE_COLLECTION = "0xbcc405d0", // not implemented
  SET_COLLECTION_COSTS = "0xd2f4302f",
  SET_COLLECTION_PHASES = "0xb85f97a0",
  AIRDROP_TOKENS = "0x5ac57d8b",
  INITIALIZE_BURN = "0x1253e16d",
  SET_FINAL_SUPPLY = "0x366b0ab2",
  SET_PRIMARY_AND_SECONDARY_SPLITS = "0xd418baec",
  PROPOSE_PRIMARY_ADDRESSES_AND_PERCENTAGES = "0x7e04bcb7",
  PROPOSE_SECONDARY_ADDRESSES_AND_PERCENTAGES = "0x1c7a8b22",
  ACCEPT_ADDRESSES_AND_PERCENTAGES = "0xd6516f47",
  PAY_ARTIST = "0x2ebc24b3",
  MINT_AND_AUCTION = "0x46372ba6",
  INITIALIZE_EXTERNAL_BURN_SWAP = "0x4c29c6f2",
  UPDATE_DELEGATION_COLLECTION = "0x81c1a52b",
}

export const NEXTGEN_CORE = {
  contract: "0xF3ff54B93844B1512C7bDafd2c41B5D228D03f98",
  abi: [
    {
      inputs: [
        { internalType: "string", name: "name", type: "string" },
        { internalType: "string", name: "symbol", type: "string" },
        { internalType: "address", name: "_adminsContract", type: "address" },
      ],
      stateMutability: "nonpayable",
      type: "constructor",
    },
    {
      inputs: [
        { internalType: "uint256", name: "numerator", type: "uint256" },
        { internalType: "uint256", name: "denominator", type: "uint256" },
      ],
      name: "ERC2981InvalidDefaultRoyalty",
      type: "error",
    },
    {
      inputs: [{ internalType: "address", name: "receiver", type: "address" }],
      name: "ERC2981InvalidDefaultRoyaltyReceiver",
      type: "error",
    },
    {
      inputs: [
        { internalType: "uint256", name: "tokenId", type: "uint256" },
        { internalType: "uint256", name: "numerator", type: "uint256" },
        { internalType: "uint256", name: "denominator", type: "uint256" },
      ],
      name: "ERC2981InvalidTokenRoyalty",
      type: "error",
    },
    {
      inputs: [
        { internalType: "uint256", name: "tokenId", type: "uint256" },
        { internalType: "address", name: "receiver", type: "address" },
      ],
      name: "ERC2981InvalidTokenRoyaltyReceiver",
      type: "error",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "address",
          name: "owner",
          type: "address",
        },
        {
          indexed: true,
          internalType: "address",
          name: "approved",
          type: "address",
        },
        {
          indexed: true,
          internalType: "uint256",
          name: "tokenId",
          type: "uint256",
        },
      ],
      name: "Approval",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "address",
          name: "owner",
          type: "address",
        },
        {
          indexed: true,
          internalType: "address",
          name: "operator",
          type: "address",
        },
        {
          indexed: false,
          internalType: "bool",
          name: "approved",
          type: "bool",
        },
      ],
      name: "ApprovalForAll",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "address",
          name: "previousOwner",
          type: "address",
        },
        {
          indexed: true,
          internalType: "address",
          name: "newOwner",
          type: "address",
        },
      ],
      name: "OwnershipTransferred",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "address",
          name: "from",
          type: "address",
        },
        { indexed: true, internalType: "address", name: "to", type: "address" },
        {
          indexed: true,
          internalType: "uint256",
          name: "tokenId",
          type: "uint256",
        },
      ],
      name: "Transfer",
      type: "event",
    },
    {
      inputs: [
        { internalType: "address", name: "_minterContract", type: "address" },
      ],
      name: "addMinterContract",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_collectionID", type: "uint256" },
        {
          internalType: "address",
          name: "_randomizerContract",
          type: "address",
        },
      ],
      name: "addRandomizer",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "mintIndex", type: "uint256" },
        { internalType: "address", name: "_recipient", type: "address" },
        { internalType: "string", name: "_tokenData", type: "string" },
        { internalType: "uint256", name: "_saltfun_o", type: "uint256" },
        { internalType: "uint256", name: "_collectionID", type: "uint256" },
      ],
      name: "airDropTokens",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "to", type: "address" },
        { internalType: "uint256", name: "tokenId", type: "uint256" },
      ],
      name: "approve",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_collectionID", type: "uint256" },
        { internalType: "string", name: "_signature", type: "string" },
      ],
      name: "artistSignature",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      name: "artistSigned",
      outputs: [{ internalType: "bool", name: "", type: "bool" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      name: "artistsSignatures",
      outputs: [{ internalType: "string", name: "", type: "string" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "owner", type: "address" }],
      name: "balanceOf",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_collectionID", type: "uint256" },
        { internalType: "uint256", name: "_tokenId", type: "uint256" },
      ],
      name: "burn",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      name: "burnAmount",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "mintIndex", type: "uint256" },
        { internalType: "uint256", name: "_burnCollectionID", type: "uint256" },
        { internalType: "uint256", name: "_tokenId", type: "uint256" },
        { internalType: "uint256", name: "_mintCollectionID", type: "uint256" },
        { internalType: "uint256", name: "_saltfun_o", type: "uint256" },
        { internalType: "address", name: "burner", type: "address" },
      ],
      name: "burnToMint",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_collectionID", type: "uint256" },
        { internalType: "bool", name: "_status", type: "bool" },
      ],
      name: "changeMetadataView",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_tokenId", type: "uint256" },
        { internalType: "string", name: "newData", type: "string" },
      ],
      name: "changeTokenData",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_collectionID", type: "uint256" },
      ],
      name: "collectionFreezeStatus",
      outputs: [{ internalType: "bool", name: "", type: "bool" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "string", name: "_collectionName", type: "string" },
        { internalType: "string", name: "_collectionArtist", type: "string" },
        {
          internalType: "string",
          name: "_collectionDescription",
          type: "string",
        },
        { internalType: "string", name: "_collectionWebsite", type: "string" },
        { internalType: "string", name: "_collectionLicense", type: "string" },
        { internalType: "string", name: "_collectionBaseURI", type: "string" },
        { internalType: "string", name: "_collectionLibrary", type: "string" },
        {
          internalType: "string[]",
          name: "_collectionScript",
          type: "string[]",
        },
      ],
      name: "createCollection",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_collectionID", type: "uint256" },
      ],
      name: "freezeCollection",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
      name: "getApproved",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "owner", type: "address" },
        { internalType: "address", name: "operator", type: "address" },
      ],
      name: "isApprovedForAll",
      outputs: [{ internalType: "bool", name: "", type: "bool" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "mintIndex", type: "uint256" },
        { internalType: "address", name: "_mintingAddress", type: "address" },
        { internalType: "address", name: "_mintTo", type: "address" },
        { internalType: "string", name: "_tokenData", type: "string" },
        { internalType: "uint256", name: "_saltfun_o", type: "uint256" },
        { internalType: "uint256", name: "_collectionID", type: "uint256" },
        { internalType: "uint256", name: "phase", type: "uint256" },
      ],
      name: "mint",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [],
      name: "minterContract",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "name",
      outputs: [{ internalType: "string", name: "", type: "string" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "newCollectionIndex",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      name: "onchainMetadata",
      outputs: [{ internalType: "bool", name: "", type: "bool" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "owner",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
      name: "ownerOf",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "renounceOwnership",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_collectionID", type: "uint256" },
      ],
      name: "retrieveArtistAddress",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_collectionID", type: "uint256" },
      ],
      name: "retrieveCollectionAdditionalData",
      outputs: [
        { internalType: "address", name: "", type: "address" },
        { internalType: "uint256", name: "", type: "uint256" },
        { internalType: "uint256", name: "", type: "uint256" },
        { internalType: "uint256", name: "", type: "uint256" },
        { internalType: "uint256", name: "", type: "uint256" },
        { internalType: "address", name: "", type: "address" },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_collectionID", type: "uint256" },
      ],
      name: "retrieveCollectionInfo",
      outputs: [
        { internalType: "string", name: "", type: "string" },
        { internalType: "string", name: "", type: "string" },
        { internalType: "string", name: "", type: "string" },
        { internalType: "string", name: "", type: "string" },
        { internalType: "string", name: "", type: "string" },
        { internalType: "string", name: "", type: "string" },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_collectionID", type: "uint256" },
      ],
      name: "retrieveCollectionLibraryAndScript",
      outputs: [
        { internalType: "string", name: "", type: "string" },
        { internalType: "string[]", name: "", type: "string[]" },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
      name: "retrieveGenerativeScript",
      outputs: [{ internalType: "string", name: "", type: "string" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "_tokenid", type: "uint256" }],
      name: "retrieveTokenHash",
      outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_collectionID", type: "uint256" },
        { internalType: "address", name: "_address", type: "address" },
      ],
      name: "retrieveTokensAirdroppedPerAddress",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_collectionID", type: "uint256" },
        { internalType: "address", name: "_address", type: "address" },
      ],
      name: "retrieveTokensMintedALPerAddress",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_collectionID", type: "uint256" },
        { internalType: "address", name: "_address", type: "address" },
      ],
      name: "retrieveTokensMintedPublicPerAddress",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "_tokenId", type: "uint256" }],
      name: "retrievetokenImageAndAttributes",
      outputs: [
        { internalType: "string", name: "", type: "string" },
        { internalType: "string", name: "", type: "string" },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_collectionID", type: "uint256" },
      ],
      name: "retrievewereDataAdded",
      outputs: [{ internalType: "bool", name: "", type: "bool" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "tokenId", type: "uint256" },
        { internalType: "uint256", name: "salePrice", type: "uint256" },
      ],
      name: "royaltyInfo",
      outputs: [
        { internalType: "address", name: "", type: "address" },
        { internalType: "uint256", name: "", type: "uint256" },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "from", type: "address" },
        { internalType: "address", name: "to", type: "address" },
        { internalType: "uint256", name: "tokenId", type: "uint256" },
      ],
      name: "safeTransferFrom",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "from", type: "address" },
        { internalType: "address", name: "to", type: "address" },
        { internalType: "uint256", name: "tokenId", type: "uint256" },
        { internalType: "bytes", name: "data", type: "bytes" },
      ],
      name: "safeTransferFrom",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "operator", type: "address" },
        { internalType: "bool", name: "approved", type: "bool" },
      ],
      name: "setApprovalForAll",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_collectionID", type: "uint256" },
        {
          internalType: "address",
          name: "_collectionArtistAddress",
          type: "address",
        },
        {
          internalType: "uint256",
          name: "_maxCollectionPurchases",
          type: "uint256",
        },
        {
          internalType: "uint256",
          name: "_collectionTotalSupply",
          type: "uint256",
        },
        {
          internalType: "uint256",
          name: "_setFinalSupplyTimeAfterMint",
          type: "uint256",
        },
      ],
      name: "setCollectionData",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "_royaltyAddress", type: "address" },
        { internalType: "uint96", name: "_bps", type: "uint96" },
      ],
      name: "setDefaultRoyalties",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_collectionID", type: "uint256" },
      ],
      name: "setFinalSupply",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_collectionID", type: "uint256" },
        { internalType: "uint256", name: "_mintIndex", type: "uint256" },
        { internalType: "bytes32", name: "_hash", type: "bytes32" },
      ],
      name: "setTokenHash",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "bytes4", name: "interfaceId", type: "bytes4" }],
      name: "supportsInterface",
      outputs: [{ internalType: "bool", name: "", type: "bool" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "symbol",
      outputs: [{ internalType: "string", name: "", type: "string" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "index", type: "uint256" }],
      name: "tokenByIndex",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      name: "tokenData",
      outputs: [{ internalType: "string", name: "", type: "string" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "owner", type: "address" },
        { internalType: "uint256", name: "index", type: "uint256" },
      ],
      name: "tokenOfOwnerByIndex",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
      name: "tokenURI",
      outputs: [{ internalType: "string", name: "", type: "string" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "totalSupply",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_collectionID", type: "uint256" },
      ],
      name: "totalSupplyOfCollection",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "from", type: "address" },
        { internalType: "address", name: "to", type: "address" },
        { internalType: "uint256", name: "tokenId", type: "uint256" },
      ],
      name: "transferFrom",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
      name: "transferOwnership",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        {
          internalType: "address",
          name: "_newadminsContract",
          type: "address",
        },
      ],
      name: "updateAdminContract",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_collectionID", type: "uint256" },
        { internalType: "string", name: "_newCollectionName", type: "string" },
        {
          internalType: "string",
          name: "_newCollectionArtist",
          type: "string",
        },
        {
          internalType: "string",
          name: "_newCollectionDescription",
          type: "string",
        },
        {
          internalType: "string",
          name: "_newCollectionWebsite",
          type: "string",
        },
        {
          internalType: "string",
          name: "_newCollectionLicense",
          type: "string",
        },
        {
          internalType: "string",
          name: "_newCollectionBaseURI",
          type: "string",
        },
        {
          internalType: "string",
          name: "_newCollectionLibrary",
          type: "string",
        },
        { internalType: "uint256", name: "_index", type: "uint256" },
        {
          internalType: "string[]",
          name: "_newCollectionScript",
          type: "string[]",
        },
      ],
      name: "updateCollectionInfo",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256[]", name: "_tokenId", type: "uint256[]" },
        { internalType: "string[]", name: "_images", type: "string[]" },
        { internalType: "string[]", name: "_attributes", type: "string[]" },
      ],
      name: "updateImagesAndAttributes",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_collectionID", type: "uint256" },
      ],
      name: "viewCirSupply",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "_tokenid", type: "uint256" }],
      name: "viewColIDforTokenID",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_collectionID", type: "uint256" },
      ],
      name: "viewMaxAllowance",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_collectionID", type: "uint256" },
      ],
      name: "viewTokensIndexMax",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_collectionID", type: "uint256" },
      ],
      name: "viewTokensIndexMin",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
  ],
};

export const NEXTGEN_MINTER = {
  contract: "0x0DC656875269F58EBd1d663168aB298a338f3FCe",
  abi: [
    {
      inputs: [
        { internalType: "address", name: "_gencore", type: "address" },
        { internalType: "address", name: "_del", type: "address" },
        { internalType: "address", name: "_adminsContract", type: "address" },
      ],
      stateMutability: "nonpayable",
      type: "constructor",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "address",
          name: "previousOwner",
          type: "address",
        },
        {
          indexed: true,
          internalType: "address",
          name: "newOwner",
          type: "address",
        },
      ],
      name: "OwnershipTransferred",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "address",
          name: "_add",
          type: "address",
        },
        { indexed: false, internalType: "bool", name: "status", type: "bool" },
        {
          indexed: true,
          internalType: "uint256",
          name: "funds",
          type: "uint256",
        },
      ],
      name: "PayArtist",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "address",
          name: "_add",
          type: "address",
        },
        { indexed: false, internalType: "bool", name: "status", type: "bool" },
        {
          indexed: true,
          internalType: "uint256",
          name: "funds",
          type: "uint256",
        },
      ],
      name: "PayTeam",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "address",
          name: "_add",
          type: "address",
        },
        { indexed: false, internalType: "bool", name: "status", type: "bool" },
        {
          indexed: true,
          internalType: "uint256",
          name: "funds",
          type: "uint256",
        },
      ],
      name: "Withdraw",
      type: "event",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_collectionID", type: "uint256" },
        { internalType: "bool", name: "_statusPrimary", type: "bool" },
        { internalType: "bool", name: "_statusSecondary", type: "bool" },
      ],
      name: "acceptAddressesAndPercentages",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address[]", name: "_recipients", type: "address[]" },
        { internalType: "string[]", name: "_tokenData", type: "string[]" },
        { internalType: "uint256[]", name: "_saltfun_o", type: "uint256[]" },
        { internalType: "uint256", name: "_collectionID", type: "uint256" },
        {
          internalType: "uint256[]",
          name: "_numberOfTokens",
          type: "uint256[]",
        },
      ],
      name: "airDropTokens",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "bytes32", name: "", type: "bytes32" },
        { internalType: "uint256", name: "", type: "uint256" },
      ],
      name: "burnExternalToMintCollections",
      outputs: [{ internalType: "bool", name: "", type: "bool" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
      name: "burnOrSwapAddress",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "_erc721Collection", type: "address" },
        { internalType: "uint256", name: "_burnCollectionID", type: "uint256" },
        { internalType: "uint256", name: "_tokenId", type: "uint256" },
        { internalType: "uint256", name: "_mintCollectionID", type: "uint256" },
        { internalType: "string", name: "_tokenData", type: "string" },
        { internalType: "bytes32[]", name: "merkleProof", type: "bytes32[]" },
        { internalType: "uint256", name: "_saltfun_o", type: "uint256" },
      ],
      name: "burnOrSwapExternalToMint",
      outputs: [],
      stateMutability: "payable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_burnCollectionID", type: "uint256" },
        { internalType: "uint256", name: "_tokenId", type: "uint256" },
        { internalType: "uint256", name: "_mintCollectionID", type: "uint256" },
        { internalType: "uint256", name: "_saltfun_o", type: "uint256" },
      ],
      name: "burnToMint",
      outputs: [],
      stateMutability: "payable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "", type: "uint256" },
        { internalType: "uint256", name: "", type: "uint256" },
      ],
      name: "burnToMintCollections",
      outputs: [{ internalType: "bool", name: "", type: "bool" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      name: "collectionTotalAmount",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "emergencyWithdraw",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [],
      name: "gencore",
      outputs: [
        { internalType: "contract INextGenCore", name: "", type: "address" },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "_tokenId", type: "uint256" }],
      name: "getAuctionEndTime",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "_tokenId", type: "uint256" }],
      name: "getAuctionStatus",
      outputs: [{ internalType: "bool", name: "", type: "bool" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_collectionID", type: "uint256" },
      ],
      name: "getEndTime",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_collectionId", type: "uint256" },
      ],
      name: "getPrice",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_burnCollectionID", type: "uint256" },
        { internalType: "uint256", name: "_mintCollectionID", type: "uint256" },
        { internalType: "bool", name: "_status", type: "bool" },
      ],
      name: "initializeBurn",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "_erc721Collection", type: "address" },
        { internalType: "uint256", name: "_burnCollectionID", type: "uint256" },
        { internalType: "uint256", name: "_mintCollectionID", type: "uint256" },
        { internalType: "uint256", name: "_tokmin", type: "uint256" },
        { internalType: "uint256", name: "_tokmax", type: "uint256" },
        {
          internalType: "address",
          name: "_burnOrSwapAddress",
          type: "address",
        },
        { internalType: "bool", name: "_status", type: "bool" },
      ],
      name: "initializeExternalBurnOrSwap",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [],
      name: "isMinterContract",
      outputs: [{ internalType: "bool", name: "", type: "bool" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      name: "lastMintDate",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_collectionID", type: "uint256" },
        { internalType: "uint256", name: "_numberOfTokens", type: "uint256" },
        { internalType: "uint256", name: "_maxAllowance", type: "uint256" },
        { internalType: "string", name: "_tokenData", type: "string" },
        { internalType: "address", name: "_mintTo", type: "address" },
        { internalType: "bytes32[]", name: "merkleProof", type: "bytes32[]" },
        { internalType: "address", name: "_delegator", type: "address" },
        { internalType: "uint256", name: "_saltfun_o", type: "uint256" },
      ],
      name: "mint",
      outputs: [],
      stateMutability: "payable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "_recipient", type: "address" },
        { internalType: "string", name: "_tokenData", type: "string" },
        { internalType: "uint256", name: "_saltfun_o", type: "uint256" },
        { internalType: "uint256", name: "_collectionID", type: "uint256" },
        { internalType: "uint256", name: "_auctionEndTime", type: "uint256" },
      ],
      name: "mintAndAuction",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [],
      name: "owner",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_collectionID", type: "uint256" },
        { internalType: "address", name: "_team1", type: "address" },
        { internalType: "address", name: "_team2", type: "address" },
        { internalType: "uint256", name: "_teamperc1", type: "uint256" },
        { internalType: "uint256", name: "_teamperc2", type: "uint256" },
      ],
      name: "payArtist",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_collectionID", type: "uint256" },
        { internalType: "address", name: "_primaryAdd1", type: "address" },
        { internalType: "address", name: "_primaryAdd2", type: "address" },
        { internalType: "address", name: "_primaryAdd3", type: "address" },
        { internalType: "uint256", name: "_add1Percentage", type: "uint256" },
        { internalType: "uint256", name: "_add2Percentage", type: "uint256" },
        { internalType: "uint256", name: "_add3Percentage", type: "uint256" },
      ],
      name: "proposePrimaryAddressesAndPercentages",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_collectionID", type: "uint256" },
        { internalType: "address", name: "_secondaryAdd1", type: "address" },
        { internalType: "address", name: "_secondaryAdd2", type: "address" },
        { internalType: "address", name: "_secondaryAdd3", type: "address" },
        { internalType: "uint256", name: "_add1Percentage", type: "uint256" },
        { internalType: "uint256", name: "_add2Percentage", type: "uint256" },
        { internalType: "uint256", name: "_add3Percentage", type: "uint256" },
      ],
      name: "proposeSecondaryAddressesAndPercentages",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [],
      name: "renounceOwnership",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_collectionID", type: "uint256" },
      ],
      name: "retrieveCollectionMintingDetails",
      outputs: [
        { internalType: "uint256", name: "", type: "uint256" },
        { internalType: "uint256", name: "", type: "uint256" },
        { internalType: "uint256", name: "", type: "uint256" },
        { internalType: "uint256", name: "", type: "uint256" },
        { internalType: "uint8", name: "", type: "uint8" },
        { internalType: "address", name: "", type: "address" },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_collectionID", type: "uint256" },
      ],
      name: "retrieveCollectionPhases",
      outputs: [
        { internalType: "uint256", name: "", type: "uint256" },
        { internalType: "uint256", name: "", type: "uint256" },
        { internalType: "bytes32", name: "", type: "bytes32" },
        { internalType: "uint256", name: "", type: "uint256" },
        { internalType: "uint256", name: "", type: "uint256" },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_collectionID", type: "uint256" },
      ],
      name: "retrievePrimaryAddressesAndPercentages",
      outputs: [
        { internalType: "address", name: "", type: "address" },
        { internalType: "address", name: "", type: "address" },
        { internalType: "address", name: "", type: "address" },
        { internalType: "uint256", name: "", type: "uint256" },
        { internalType: "uint256", name: "", type: "uint256" },
        { internalType: "uint256", name: "", type: "uint256" },
        { internalType: "bool", name: "", type: "bool" },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_collectionID", type: "uint256" },
      ],
      name: "retrievePrimarySplits",
      outputs: [
        { internalType: "uint256", name: "", type: "uint256" },
        { internalType: "uint256", name: "", type: "uint256" },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_collectionID", type: "uint256" },
      ],
      name: "retrieveSecondaryAddressesAndPercentages",
      outputs: [
        { internalType: "address", name: "", type: "address" },
        { internalType: "address", name: "", type: "address" },
        { internalType: "address", name: "", type: "address" },
        { internalType: "uint256", name: "", type: "uint256" },
        { internalType: "uint256", name: "", type: "uint256" },
        { internalType: "uint256", name: "", type: "uint256" },
        { internalType: "bool", name: "", type: "bool" },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_collectionID", type: "uint256" },
      ],
      name: "retrieveSecondarySplits",
      outputs: [
        { internalType: "uint256", name: "", type: "uint256" },
        { internalType: "uint256", name: "", type: "uint256" },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_collectionID", type: "uint256" },
        {
          internalType: "uint256",
          name: "_collectionMintCost",
          type: "uint256",
        },
        {
          internalType: "uint256",
          name: "_collectionEndMintCost",
          type: "uint256",
        },
        { internalType: "uint256", name: "_rate", type: "uint256" },
        { internalType: "uint256", name: "_timePeriod", type: "uint256" },
        { internalType: "uint8", name: "_salesOption", type: "uint8" },
        { internalType: "address", name: "_delAddress", type: "address" },
      ],
      name: "setCollectionCosts",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_collectionID", type: "uint256" },
        {
          internalType: "uint256",
          name: "_allowlistStartTime",
          type: "uint256",
        },
        { internalType: "uint256", name: "_allowlistEndTime", type: "uint256" },
        { internalType: "uint256", name: "_publicStartTime", type: "uint256" },
        { internalType: "uint256", name: "_publicEndTime", type: "uint256" },
        { internalType: "bytes32", name: "_merkleRoot", type: "bytes32" },
      ],
      name: "setCollectionPhases",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_collectionID", type: "uint256" },
        { internalType: "uint256", name: "_artistPrSplit", type: "uint256" },
        { internalType: "uint256", name: "_teamPrSplit", type: "uint256" },
        { internalType: "uint256", name: "_artistSecSplit", type: "uint256" },
        { internalType: "uint256", name: "_teamSecSplit", type: "uint256" },
      ],
      name: "setPrimaryAndSecondarySplits",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
      name: "transferOwnership",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        {
          internalType: "address",
          name: "_newadminsContract",
          type: "address",
        },
      ],
      name: "updateAdminContract",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "_gencore", type: "address" }],
      name: "updateCoreContract",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_collectionID", type: "uint256" },
        {
          internalType: "address",
          name: "_collectionAddress",
          type: "address",
        },
      ],
      name: "updateDelegationCollection",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
  ],
};

export const NEXTGEN_ADMIN = {
  contract: "0x1bAe1D145Dd61fBBB62C85f8A6d7B6eDe0D150f5",
  abi: [
    { inputs: [], stateMutability: "nonpayable", type: "constructor" },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "address",
          name: "previousOwner",
          type: "address",
        },
        {
          indexed: true,
          internalType: "address",
          name: "newOwner",
          type: "address",
        },
      ],
      name: "OwnershipTransferred",
      type: "event",
    },
    {
      inputs: [{ internalType: "address", name: "", type: "address" }],
      name: "adminPermissions",
      outputs: [{ internalType: "bool", name: "", type: "bool" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "isAdminContract",
      outputs: [{ internalType: "bool", name: "", type: "bool" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "owner",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "_admin", type: "address" },
        { internalType: "bool", name: "_status", type: "bool" },
      ],
      name: "registerAdmin",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "_address", type: "address" },
        { internalType: "bytes4[]", name: "_selector", type: "bytes4[]" },
        { internalType: "bool", name: "_status", type: "bool" },
      ],
      name: "registerBatchFunctionAdmin",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_collectionID", type: "uint256" },
        { internalType: "address", name: "_address", type: "address" },
        { internalType: "bool", name: "_status", type: "bool" },
      ],
      name: "registerCollectionAdmin",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "_address", type: "address" },
        { internalType: "bytes4", name: "_selector", type: "bytes4" },
        { internalType: "bool", name: "_status", type: "bool" },
      ],
      name: "registerFunctionAdmin",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [],
      name: "renounceOwnership",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "_address", type: "address" },
        { internalType: "uint256", name: "_collectionID", type: "uint256" },
      ],
      name: "retrieveCollectionAdmin",
      outputs: [{ internalType: "bool", name: "", type: "bool" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "_address", type: "address" },
        { internalType: "bytes4", name: "_selector", type: "bytes4" },
      ],
      name: "retrieveFunctionAdmin",
      outputs: [{ internalType: "bool", name: "", type: "bool" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "_address", type: "address" }],
      name: "retrieveGlobalAdmin",
      outputs: [{ internalType: "bool", name: "", type: "bool" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
      name: "transferOwnership",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
  ],
};
