"use client";

import { ProfileBadgeSize } from "@/components/common/profile/ProfileAvatar";
import ProfileBadge from "@/components/common/profile/ProfileBadge";
import {
  formatAmount,
  formatDateTime,
} from "@/components/user/xtdh/utils/xtdhGrantFormatters";
import UserProfileTooltipWrapper from "@/components/utils/tooltip/UserProfileTooltipWrapper";
import type { ApiXTdhGrant } from "@/generated/models/ApiXTdhGrant";
import { shortenAddress } from "@/helpers/address.helpers";
import {
  isAutoGeneratedHandle,
  isEthereumAddress,
} from "@/helpers/AllowlistToolHelpers";
import { cicToType } from "@/helpers/Helpers";

import { getGrantStatusLabel } from "../utils";

import type { KeyboardEvent } from "react";

interface GroupCreateXtdhGrantRowProps {
  readonly grant: ApiXTdhGrant;
  readonly isSelected?: boolean | undefined;
  readonly interactive?: boolean | undefined;
  readonly asListItem?: boolean | undefined;
  readonly className?: string | undefined;
  readonly onSelect?: ((grant: ApiXTdhGrant) => void) | undefined;
}

const getStatusPillClasses = (statusLabel: string): string => {
  if (statusLabel === "ACTIVE") {
    return "tw-bg-green/20 tw-text-green";
  }
  if (statusLabel === "SCHEDULED") {
    return "tw-bg-blue-400/20 tw-text-blue-200";
  }
  if (statusLabel === "ENDED") {
    return "tw-bg-iron-700/30 tw-text-iron-400";
  }
  if (statusLabel === "PENDING") {
    return "tw-bg-primary-400/20 tw-text-primary-300";
  }
  return "tw-bg-red/20 tw-text-red";
};

const getStateClasses = (interactive: boolean, isSelected: boolean): string => {
  if (interactive && isSelected) {
    return "tw-cursor-pointer tw-border-primary-400 tw-bg-primary-500/10";
  }
  if (interactive) {
    return "tw-cursor-pointer tw-border-iron-800 tw-bg-iron-900/70 desktop-hover:hover:tw-border-iron-700 desktop-hover:hover:tw-bg-iron-900";
  }
  if (isSelected) {
    return "tw-border-primary-400 tw-bg-primary-500/10";
  }
  return "tw-border-iron-800 tw-bg-iron-900/60";
};

const getRowClasses = ({
  asListItem,
  interactive,
  stateClasses,
  className,
}: {
  readonly asListItem: boolean;
  readonly interactive: boolean;
  readonly stateClasses: string;
  readonly className: string | undefined;
}): string =>
  `${asListItem ? "tw-list-none " : ""}tw-rounded-lg tw-border tw-border-solid tw-p-3 tw-outline-none tw-transition tw-duration-200 ${interactive ? "focus-visible:tw-ring-2 focus-visible:tw-ring-primary-400" : ""} ${stateClasses} ${className ?? ""}`.trim();

const getInteractiveProps = (
  interactive: boolean,
  handleSelect: () => void,
  handleKeyDown: (event: KeyboardEvent<HTMLElement>) => void
) => {
  if (!interactive) {
    return {
      role: undefined,
      tabIndex: undefined,
      onClick: undefined,
      onKeyDown: undefined,
    };
  }

  return {
    role: "button" as const,
    tabIndex: 0,
    onClick: handleSelect,
    onKeyDown: handleKeyDown,
  };
};

const isActivationKey = (key: string): boolean =>
  key === "Enter" || key === " ";

export default function GroupCreateXtdhGrantRow({
  grant,
  isSelected = false,
  interactive = false,
  asListItem = false,
  className,
  onSelect,
}: GroupCreateXtdhGrantRowProps) {
  const statusLabel = getGrantStatusLabel({
    status: grant.status,
    validFrom: grant.valid_from,
    validTo: grant.valid_to,
  });

  const trimmedCollectionName = grant.target_collection_name?.trim() ?? "";
  const targetLabel =
    trimmedCollectionName.length > 0
      ? trimmedCollectionName
      : grant.target_contract || "Unknown target";

  const grantor = grant.grantor;
  const grantorHandle = grantor.handle;
  const grantorPrimaryAddress = grantor.primary_address;
  const displayGrantor = grantorHandle ?? shortenAddress(grantorPrimaryAddress);
  const shouldTruncateGrantor =
    isEthereumAddress(grantorHandle ?? grantorPrimaryAddress) ||
    isAutoGeneratedHandle(grantorHandle ?? grantorPrimaryAddress);
  const tooltipIdentity = grantorHandle ?? grantor.id;
  const profileHref = grantorHandle ? `/${grantorHandle}` : undefined;

  const avatarFallback = (
    <div className="tw-flex tw-h-full tw-w-full tw-items-center tw-justify-center tw-text-xs tw-font-semibold tw-text-iron-400">
      ?
    </div>
  );

  const grantorBadge = (
    <ProfileBadge
      handle={displayGrantor}
      href={profileHref}
      pfpUrl={grantor.pfp}
      level={grantor.level}
      cicType={cicToType(grantor.cic)}
      size={ProfileBadgeSize.SMALL}
      className={`tw-min-w-0 ${
        shouldTruncateGrantor
          ? "[&>div>div]:tw-min-w-0 [&>div]:tw-min-w-0 [&_p]:tw-truncate"
          : ""
      }`}
      avatarAlt={grantorHandle ?? "Grantor profile"}
      avatarFallback={avatarFallback}
      asLink={Boolean(profileHref)}
    />
  );

  const grantorSummary = tooltipIdentity ? (
    <UserProfileTooltipWrapper user={tooltipIdentity}>
      {grantorBadge}
    </UserProfileTooltipWrapper>
  ) : (
    grantorBadge
  );

  const handleSelect = () => onSelect?.(grant);

  const handleKeyDown = (event: KeyboardEvent<HTMLElement>) => {
    if (!interactive || !isActivationKey(event.key)) {
      return;
    }
    event.preventDefault();
    handleSelect();
  };

  const stateClasses = getStateClasses(interactive, isSelected);
  const rowClasses = getRowClasses({
    asListItem,
    interactive,
    stateClasses,
    className,
  });
  const interactiveProps = getInteractiveProps(
    interactive,
    handleSelect,
    handleKeyDown
  );
  const ContainerTag = asListItem ? "li" : "div";

  const rowContent = (
    <div className="tw-flex tw-flex-col tw-gap-3">
      <div className="tw-min-w-0 tw-flex-1 tw-space-y-1.5">
        <div className="tw-flex tw-flex-wrap tw-items-center tw-gap-2">
          <span
            className={`tw-inline-flex tw-items-center tw-rounded-full tw-px-2 tw-py-0.5 tw-text-[11px] tw-font-semibold tw-tracking-wide ${getStatusPillClasses(
              statusLabel
            )}`}
          >
            {statusLabel}
          </span>
          <p className="tw-m-0 tw-truncate tw-text-sm tw-font-semibold tw-text-iron-50">
            {targetLabel}
          </p>
        </div>

        <div className="tw-flex tw-flex-wrap tw-items-center tw-justify-between tw-gap-2">
          <div className="tw-min-w-0 tw-flex-1">{grantorSummary}</div>
          <p className="tw-m-0 tw-whitespace-nowrap tw-text-xs tw-font-semibold tw-text-iron-400">
            Rate: {formatAmount(grant.rate)}
          </p>
        </div>

        <p className="tw-m-0 tw-text-xs tw-text-iron-500">
          Valid:{" "}
          {formatDateTime(grant.valid_from ?? null, {
            fallbackLabel: "Immediately",
            includeTime: false,
          })}{" "}
          {"->"}{" "}
          {formatDateTime(grant.valid_to ?? null, {
            fallbackLabel: "No expiry",
            includeTime: false,
          })}
        </p>
      </div>
    </div>
  );

  return (
    <ContainerTag className={rowClasses} {...interactiveProps}>
      {rowContent}
    </ContainerTag>
  );
}
