"use client";

import type { KeyboardEvent } from "react";
import ProfileBadge from "@/components/common/profile/ProfileBadge";
import { ProfileBadgeSize } from "@/components/common/profile/ProfileAvatar";
import UserProfileTooltipWrapper from "@/components/utils/tooltip/UserProfileTooltipWrapper";
import type { ApiXTdhGrant } from "@/generated/models/ApiXTdhGrant";
import { cicToType } from "@/helpers/Helpers";
import {
  isAutoGeneratedHandle,
  isEthereumAddress,
} from "@/helpers/AllowlistToolHelpers";
import { shortenAddress } from "@/helpers/address.helpers";
import {
  formatAmount,
  formatDateTime,
} from "@/components/user/xtdh/utils/xtdhGrantFormatters";
import { getGrantStatusLabel } from "../utils";

interface GroupCreateXtdhGrantRowProps {
  readonly grant: ApiXTdhGrant;
  readonly isSelected?: boolean | undefined;
  readonly interactive?: boolean | undefined;
  readonly asListItem?: boolean | undefined;
  readonly className?: string | undefined;
  readonly quiet?: boolean;
  readonly onSelect?: ((grant: ApiXTdhGrant) => void) | undefined;
}

const getStatusPillClasses = (statusLabel: string): string => {
  if (statusLabel === "ACTIVE") {
    return "tw-bg-green/20 tw-text-green";
  }
  if (statusLabel === "SCHEDULED") {
    return "tw-bg-blue-400/20 tw-text-blue-200";
  }
  if (statusLabel === "ENDED") {
    return "tw-bg-iron-700/30 tw-text-iron-400";
  }
  if (statusLabel === "PENDING") {
    return "tw-bg-primary-400/20 tw-text-primary-300";
  }
  return "tw-bg-red/20 tw-text-red";
};

const getStateClasses = (
  interactive: boolean,
  isSelected: boolean,
  quiet: boolean
): string => {
  if (quiet && !isSelected) {
    return `tw-border-transparent tw-bg-iron-900/50 ${interactive ? "tw-cursor-pointer desktop-hover:hover:tw-bg-iron-900" : ""}`;
  }
  if (interactive && isSelected) {
    return "tw-cursor-pointer tw-border-primary-400 tw-bg-primary-500/10";
  }
  if (interactive) {
    return "tw-cursor-pointer tw-border-iron-800 tw-bg-iron-900/70 desktop-hover:hover:tw-border-iron-700 desktop-hover:hover:tw-bg-iron-900";
  }
  if (isSelected) {
    return "tw-border-primary-400 tw-bg-primary-500/10";
  }
  return "tw-border-iron-800 tw-bg-iron-900/60";
};

const getRowClasses = ({
  asListItem,
  interactive,
  stateClasses,
  className,
  quiet,
}: {
  readonly asListItem: boolean;
  readonly interactive: boolean;
  readonly stateClasses: string;
  readonly className: string | undefined;
  readonly quiet: boolean;
}): string =>
  `${asListItem ? "tw-list-none " : ""}${quiet ? "tw-rounded-xl tw-p-4 focus-visible:tw-ring-inset" : "tw-rounded-lg tw-p-3"} tw-border tw-border-solid tw-outline-none tw-transition tw-duration-200 ${interactive ? "focus-visible:tw-ring-2 focus-visible:tw-ring-primary-400" : ""} ${stateClasses} ${className ?? ""}`.trim();

const getInteractiveProps = (
  interactive: boolean,
  handleSelect: () => void,
  handleKeyDown: (event: KeyboardEvent<HTMLElement>) => void
) => {
  if (!interactive) {
    return {
      role: undefined,
      tabIndex: undefined,
      onClick: undefined,
      onKeyDown: undefined,
    };
  }

  return {
    role: "button" as const,
    tabIndex: 0,
    onClick: handleSelect,
    onKeyDown: handleKeyDown,
  };
};

const isActivationKey = (key: string): boolean =>
  key === "Enter" || key === " ";

export default function GroupCreateXtdhGrantRow({
  grant,
  isSelected = false,
  interactive = false,
  asListItem = false,
  className,
  onSelect,
  quiet = false,
}: GroupCreateXtdhGrantRowProps) {
  const statusLabel = getGrantStatusLabel({
    status: grant.status,
    validFrom: grant.valid_from,
    validTo: grant.valid_to,
  });

  const trimmedCollectionName = grant.target_collection_name?.trim() ?? "";
  const targetLabel =
    trimmedCollectionName.length > 0
      ? trimmedCollectionName
      : grant.target_contract || "Unknown target";

  const grantor = grant.grantor;
  const grantorHandle = grantor.handle;
  const grantorPrimaryAddress = grantor.primary_address;
  const displayGrantor = grantorHandle ?? shortenAddress(grantorPrimaryAddress);
  const shouldTruncateGrantor =
    isEthereumAddress(grantorHandle ?? grantorPrimaryAddress) ||
    isAutoGeneratedHandle(grantorHandle ?? grantorPrimaryAddress);
  const tooltipIdentity = grantorHandle ?? grantor.id;
  const profileHref = grantorHandle ? `/${grantorHandle}` : undefined;

  const avatarFallback = (
    <div className="tw-flex tw-h-full tw-w-full tw-items-center tw-justify-center tw-text-xs tw-font-semibold tw-text-iron-400">
      ?
    </div>
  );

  const grantorBadge = (
    <ProfileBadge
      handle={displayGrantor}
      href={profileHref}
      pfpUrl={grantor.pfp}
      level={grantor.level}
      cicType={cicToType(grantor.cic)}
      size={ProfileBadgeSize.SMALL}
      className={`tw-min-w-0 ${quiet ? "desktop-hover:[&_a:hover]:tw-text-iron-200 [&_a]:tw-text-iron-350 [&_p]:tw-m-0 [&_p]:tw-text-xxs [&_p]:tw-font-normal [&_p]:tw-text-iron-350" : ""} ${
        shouldTruncateGrantor
          ? "[&>div>div]:tw-min-w-0 [&>div]:tw-min-w-0 [&_p]:tw-truncate"
          : ""
      }`}
      avatarAlt={grantorHandle ?? "Grantor profile"}
      avatarFallback={avatarFallback}
      asLink={Boolean(profileHref)}
    />
  );

  const grantorSummary = tooltipIdentity ? (
    <UserProfileTooltipWrapper user={tooltipIdentity}>
      {grantorBadge}
    </UserProfileTooltipWrapper>
  ) : (
    grantorBadge
  );

  const handleSelect = () => onSelect?.(grant);

  const handleKeyDown = (event: KeyboardEvent<HTMLElement>) => {
    if (!interactive || !isActivationKey(event.key)) {
      return;
    }
    event.preventDefault();
    handleSelect();
  };

  const stateClasses = getStateClasses(interactive, isSelected, quiet);
  const rowClasses = getRowClasses({
    asListItem,
    interactive,
    stateClasses,
    className,
    quiet,
  });
  const interactiveProps = getInteractiveProps(
    interactive,
    handleSelect,
    handleKeyDown
  );
  const ContainerTag = asListItem ? "li" : "div";

  const rate = (
    <p
      className={`tw-m-0 tw-whitespace-nowrap tw-text-iron-400 ${quiet ? "tw-text-xxs tw-font-normal" : "tw-text-xs tw-font-semibold"}`}
    >
      Rate:{" "}
      <span className={quiet ? "tw-font-medium tw-text-iron-200" : undefined}>
        {formatAmount(grant.rate)}
      </span>
    </p>
  );

  const rowContent = (
    <div className="tw-flex tw-flex-col tw-gap-3">
      <div
        className={`tw-min-w-0 tw-flex-1 ${quiet ? "tw-space-y-2" : "tw-space-y-1.5"}`}
      >
        <div
          className={`tw-flex tw-flex-wrap tw-items-center tw-gap-2 ${quiet ? "tw-justify-between" : ""}`}
        >
          <div
            className={
              quiet
                ? "tw-flex tw-min-w-0 tw-flex-1 tw-flex-wrap tw-items-center tw-gap-2"
                : "tw-contents"
            }
          >
            <span
              className={`tw-inline-flex tw-items-center tw-px-2 tw-tracking-wide ${quiet ? "tw-rounded-lg tw-py-1 tw-text-[10px] tw-font-medium" : "tw-rounded-full tw-py-0.5 tw-text-[11px] tw-font-semibold"} ${getStatusPillClasses(statusLabel)}`}
            >
              {statusLabel}
            </span>
            <p
              className={`tw-m-0 tw-truncate tw-text-iron-50 ${quiet ? "tw-text-md tw-font-medium" : "tw-text-sm tw-font-semibold"}`}
            >
              {targetLabel}
            </p>
          </div>
          {quiet && rate}
        </div>

        <div className="tw-flex tw-flex-wrap tw-items-center tw-justify-between tw-gap-2">
          <div className="tw-min-w-0 tw-flex-1">{grantorSummary}</div>
          {!quiet && rate}
        </div>

        <p
          className={`tw-m-0 tw-text-xs tw-text-iron-500 ${quiet ? "tw-pl-9" : ""}`}
        >
          Valid:{" "}
          {formatDateTime(grant.valid_from ?? null, {
            fallbackLabel: "Immediately",
            includeTime: false,
          })}{" "}
          {"->"}{" "}
          {formatDateTime(grant.valid_to ?? null, {
            fallbackLabel: "No expiry",
            includeTime: false,
          })}
        </p>
      </div>
    </div>
  );

  return (
    <ContainerTag className={rowClasses} {...interactiveProps}>
      {rowContent}
    </ContainerTag>
  );
}
