"use client";

import Link from "next/link";
import { isAutoGeneratedHandle } from "@/helpers/AllowlistToolHelpers";
import { formatAddress } from "@/helpers/addressFormatting";
import { getProfileTargetRoute } from "@/helpers/Helpers";
import { usePathname } from "next/navigation";
import type { UserPageTabKey } from "@/components/user/layout/userTabs.config";

export default function CommonProfileLink({
  handleOrWallet,
  isCurrentUser,
  tabTarget,
  textClassName,
}: {
  readonly handleOrWallet: string;
  readonly isCurrentUser: boolean;
  readonly tabTarget: UserPageTabKey;
  readonly textClassName?: string | undefined;
}) {
  const pathname = usePathname();
  const url = getProfileTargetRoute({
    handleOrWallet,
    pathname,
    defaultPath: tabTarget,
  });
  const resolvedTextClassName =
    textClassName ?? "tw-text-base tw-font-medium tw-text-iron-200";
  const displayHandleOrWallet = isAutoGeneratedHandle(handleOrWallet)
    ? `id-${formatAddress(handleOrWallet.slice(3))}`
    : formatAddress(handleOrWallet);

  return (
    <Link
      href={url}
      aria-label={handleOrWallet}
      className={`${
        isCurrentUser ? "tw-pointer-events-none tw-no-underline" : ""
      } tw-p-0 tw-leading-4 tw-no-underline hover:tw-no-underline`}
    >
      <span
        className={`${
          isCurrentUser ? "" : "tw-cursor-pointer"
        } tw-whitespace-nowrap tw-transition tw-duration-300 tw-ease-out hover:tw-text-iron-400 ${resolvedTextClassName}`}
      >
        {displayHandleOrWallet}
      </span>
    </Link>
  );
}
