import { z } from "zod";

const reviewbotUsageEnvSchema = z.object({
  REVIEWBOT_USAGE_API_BASE_URL: z.string().optional(),
  REVIEWBOT_USAGE_API_PUBLIC_SUMMARY_PATH: z.string().optional(),
  REVIEWBOT_USAGE_API_ADMIN_ALERT_STATUS_PATH: z.string().optional(),
  REVIEWBOT_USAGE_API_ADMIN_BUDGET_STATUS_PATH: z.string().optional(),
  REVIEWBOT_USAGE_API_ADMIN_HMAC_SECRET: z.string().optional(),
  REVIEWBOT_USAGE_API_ADMIN_JOB_EVENTS_PATH: z.string().optional(),
  REVIEWBOT_USAGE_API_ADMIN_MODEL_PRICE_STATUS_PATH: z.string().optional(),
  REVIEWBOT_USAGE_API_ADMIN_ROLES: z.string().optional(),
  REVIEWBOT_USAGE_API_ADMIN_RUN_CLAIMS_PATH: z.string().optional(),
  REVIEWBOT_USAGE_API_ADMIN_STATUS_PATH: z.string().optional(),
  REVIEWBOT_USAGE_API_ADMIN_SUMMARY_PATH: z.string().optional(),
  REVIEWBOT_USAGE_API_ADMIN_TTL_SECONDS: z.string().optional(),
  REVIEWBOT_USAGE_ADMIN_ALLOWED_WALLETS: z.string().optional(),
  REVIEWBOT_USAGE_ADMIN_AUTH_CHECK_URL: z.string().optional(),
});

export type ReviewbotUsageEnv = z.infer<typeof reviewbotUsageEnvSchema>;

export function getReviewbotUsageEnv(
  env: NodeJS.ProcessEnv = process.env
): ReviewbotUsageEnv {
  const parsed = reviewbotUsageEnvSchema.safeParse({
    REVIEWBOT_USAGE_API_BASE_URL: env["REVIEWBOT_USAGE_API_BASE_URL"],
    REVIEWBOT_USAGE_ADMIN_ALLOWED_WALLETS:
      env["REVIEWBOT_USAGE_ADMIN_ALLOWED_WALLETS"],
    REVIEWBOT_USAGE_ADMIN_AUTH_CHECK_URL:
      env["REVIEWBOT_USAGE_ADMIN_AUTH_CHECK_URL"],
    REVIEWBOT_USAGE_API_ADMIN_ALERT_STATUS_PATH:
      env["REVIEWBOT_USAGE_API_ADMIN_ALERT_STATUS_PATH"],
    REVIEWBOT_USAGE_API_ADMIN_BUDGET_STATUS_PATH:
      env["REVIEWBOT_USAGE_API_ADMIN_BUDGET_STATUS_PATH"],
    REVIEWBOT_USAGE_API_ADMIN_HMAC_SECRET:
      env["REVIEWBOT_USAGE_API_ADMIN_HMAC_SECRET"],
    REVIEWBOT_USAGE_API_ADMIN_JOB_EVENTS_PATH:
      env["REVIEWBOT_USAGE_API_ADMIN_JOB_EVENTS_PATH"],
    REVIEWBOT_USAGE_API_ADMIN_MODEL_PRICE_STATUS_PATH:
      env["REVIEWBOT_USAGE_API_ADMIN_MODEL_PRICE_STATUS_PATH"],
    REVIEWBOT_USAGE_API_ADMIN_ROLES: env["REVIEWBOT_USAGE_API_ADMIN_ROLES"],
    REVIEWBOT_USAGE_API_ADMIN_RUN_CLAIMS_PATH:
      env["REVIEWBOT_USAGE_API_ADMIN_RUN_CLAIMS_PATH"],
    REVIEWBOT_USAGE_API_ADMIN_STATUS_PATH:
      env["REVIEWBOT_USAGE_API_ADMIN_STATUS_PATH"],
    REVIEWBOT_USAGE_API_ADMIN_SUMMARY_PATH:
      env["REVIEWBOT_USAGE_API_ADMIN_SUMMARY_PATH"],
    REVIEWBOT_USAGE_API_ADMIN_TTL_SECONDS:
      env["REVIEWBOT_USAGE_API_ADMIN_TTL_SECONDS"],
    REVIEWBOT_USAGE_API_PUBLIC_SUMMARY_PATH:
      env["REVIEWBOT_USAGE_API_PUBLIC_SUMMARY_PATH"],
  });

  if (!parsed.success) {
    return {};
  }

  return parsed.data;
}
