import React from "react";
import type { ApiWaveVoter } from "@/generated/models/ApiWaveVoter";
import Link from "next/link";
import Image from "next/image";
import { formatNumberWithCommas } from "@/helpers/Helpers";
import { Tooltip } from "react-tooltip";
import type { ApiWaveCreditType } from "@/generated/models/ApiWaveCreditType";
import { TOOLTIP_STYLES } from "@/helpers/tooltip.helpers";
import { WAVE_VOTING_LABELS, WAVE_VOTE_STATS_LABELS } from "@/helpers/waves/waves.constants";
import {
  isEthereumAddress,
  isAutoGeneratedHandle,
} from "@/helpers/AllowlistToolHelpers";
import UserProfileTooltipWrapper from "@/components/utils/tooltip/UserProfileTooltipWrapper";
import { resolveIpfsUrlSync } from "@/components/ipfs/IPFSContext";

interface SingleWaveDropVoterProps {
  readonly voter: ApiWaveVoter;
  readonly position: number;
  readonly creditType: ApiWaveCreditType;
}

export const SingleWaveDropVoter: React.FC<SingleWaveDropVoterProps> = ({
  voter,
  position,
  creditType,
}) => {
  const hasPositiveVotes = !!voter.positive_votes_summed;
  const hasNegativeVotes = !!voter.negative_votes_summed;

  const pfpClasses = "tw-size-7 tw-rounded-md tw-ring-1 tw-ring-white/10 tw-bg-iron-800 tw-flex-shrink-0 tw-object-contain";
  const dotClasses = "tw-w-1.5 tw-h-1.5 tw-rounded-sm";

  const handleValue = voter.voter.handle ?? "";
  const shouldLimit =
    isEthereumAddress(handleValue) || isAutoGeneratedHandle(handleValue);

  return (
    <div className="tw-p-3 tw-flex tw-items-center tw-justify-between hover:tw-bg-white/[0.02] tw-transition-colors">
      <div className="tw-flex tw-items-center tw-gap-4">
        <span className="tw-text-xs tw-font-medium tw-text-iron-600">
          {position}
        </span>
        <Link
          href={`/${voter.voter.handle}`}
          className="tw-flex tw-items-center tw-gap-2.5 tw-no-underline tw-group hover:tw-opacity-80 tw-transition-all tw-duration-300 tw-whitespace-nowrap"
        >
          {voter.voter.pfp ? (
            <Image src={resolveIpfsUrlSync(voter.voter.pfp)} alt="" width={24} height={24} className={pfpClasses} />
          ) : (
            <div className={pfpClasses} />
          )}
          <UserProfileTooltipWrapper user={voter.voter.handle ?? voter.voter.id}>
            <span className={`tw-inline-block${shouldLimit ? " tw-truncate tw-max-w-[8rem]" : ""}`}>
              <span className="tw-text-sm tw-font-medium tw-text-iron-50 tw-transition-all tw-duration-300 group-hover:tw-text-iron-300">
                {voter.voter.handle}
              </span>
            </span>
          </UserProfileTooltipWrapper>
        </Link>
      </div>
      <div className="tw-flex tw-items-center tw-gap-3 tw-whitespace-nowrap">
        <>
          <div
            className="tw-flex tw-items-center tw-gap-1"
            data-tooltip-id={`single-voter-${voter.voter.handle}-${position}`}
          >
            {hasPositiveVotes && (
              <div className={`${dotClasses} tw-bg-green`} />
            )}
            {hasNegativeVotes && (
              <div className={`${dotClasses} tw-bg-red`} />
            )}
          </div>
          <Tooltip
            id={`single-voter-${voter.voter.handle}-${position}`}
            place="top"
            offset={8}
            opacity={1}
            style={TOOLTIP_STYLES}
          >
            <div className="tw-text-sm tw-space-x-1">
              <div className="tw-text-green">
                +{formatNumberWithCommas(voter.positive_votes_summed)}
              </div>
              {hasNegativeVotes && (
                <div className="tw-text-red">
                  -{formatNumberWithCommas(voter.negative_votes_summed)}
                </div>
              )}
            </div>
          </Tooltip>
        </>
        <span className="tw-text-xs tw-text-iron-600">
          <span className="tw-tabular-nums">{formatNumberWithCommas(voter.absolute_votes_summed)}</span> {WAVE_VOTING_LABELS[creditType]} {WAVE_VOTE_STATS_LABELS.TOTAL}
        </span>
      </div>
    </div>
  );
}; 
