import { SystemAdjustmentPill } from "@/components/common/SystemAdjustmentPill";
import { resolveIpfsUrlSync } from "@/components/ipfs/IPFSContext";
import UserProfileTooltipWrapper from "@/components/utils/tooltip/UserProfileTooltipWrapper";
import { ApiWaveCreditType } from "@/generated/models/ApiWaveCreditType";
import { ApiWaveLog } from "@/generated/models/ApiWaveLog";
import {
  isAutoGeneratedHandle,
  isEthereumAddress,
} from "@/helpers/AllowlistToolHelpers";
import {
  formatNumberWithCommas,
  getTimeAgoShort,
} from "@/helpers/Helpers";
import { getScaledImageUri, ImageScale } from "@/helpers/image.helpers";
import { WAVE_VOTING_LABELS } from "@/helpers/waves/waves.constants";
import useIsMobileScreen from "@/hooks/isMobileScreen";
import Image from "next/image";
import Link from "next/link";

interface SingleWaveDropLogProps {
  readonly log: ApiWaveLog;
  readonly creditType: ApiWaveCreditType;
}

interface VoteSummaryProps {
  readonly log: ApiWaveLog;
  readonly creditType: ApiWaveCreditType;
}

interface TimeStampProps {
  readonly createdAt: Date | string;
  readonly iconClassName: string;
  readonly textClassName: string;
}

const ClockIcon = ({ className }: { readonly className: string }) => (
  <svg className={className} viewBox="0 0 24 24" aria-hidden="true" fill="none">
    <path
      d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"
      stroke="currentColor"
      strokeWidth="1.5"
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
);

const VoteSummary = ({ log, creditType }: VoteSummaryProps) => (
  <>
    <span className="tw-text-sm tw-text-iron-500">
      {log.contents.oldVote === 0 ? "voted" : "changed from"}
    </span>
    {log.contents.oldVote !== 0 && (
      <span className="tw-text-sm tw-font-medium tw-text-iron-400 tw-whitespace-nowrap">
        <span className="tw-tabular-nums">
          {formatNumberWithCommas(log.contents.oldVote)}
        </span>{" "}
        →
      </span>
    )}
    <span
      className={`tw-text-sm tw-font-medium tw-whitespace-nowrap ${
        log.contents.newVote > 0 ? "tw-text-emerald-500" : "tw-text-rose-500"
      }`}
    >
      <span className="tw-tabular-nums">
        {formatNumberWithCommas(log.contents.newVote)}
      </span>{" "}
      {WAVE_VOTING_LABELS[creditType]}
    </span>
    {log.contents?.reason === "CREDIT_OVERSPENT" && <SystemAdjustmentPill />}
  </>
);

const TimeStamp = ({
  createdAt,
  iconClassName,
  textClassName,
}: TimeStampProps) => (
  <div className="tw-flex tw-items-center tw-gap-1 tw-whitespace-nowrap">
    <ClockIcon className={iconClassName} />
    <span className={textClassName}>
      {getTimeAgoShort(
        typeof createdAt === "string"
          ? new Date(createdAt).getTime()
          : createdAt.getTime()
      )}
    </span>
  </div>
);

export const SingleWaveDropLog = ({
  log,
  creditType,
}: SingleWaveDropLogProps) => {
  const isMobile = useIsMobileScreen();
  const handleValue = log.invoker.handle ?? "";
  const shouldLimit =
    isEthereumAddress(handleValue) || isAutoGeneratedHandle(handleValue);

  const avatar = log.invoker.pfp ? (
    <Image
      unoptimized
      src={getScaledImageUri(resolveIpfsUrlSync(log.invoker.pfp), ImageScale.W_AUTO_H_50)}
      alt="User profile picture"
      width={28}
      height={28}
      className="tw-size-7 tw-rounded-md tw-ring-1 tw-ring-white/10 tw-bg-iron-800 tw-flex-shrink-0 tw-object-contain"
    />
  ) : (
    <div className="tw-size-7 tw-rounded-md tw-ring-1 tw-ring-white/10 tw-bg-iron-800 tw-flex-shrink-0" />
  );

  const handleLink = (
    <UserProfileTooltipWrapper user={log.invoker.handle ?? log.invoker.id}>
      <Link
        href={`/${log.invoker.handle}`}
        className="tw-no-underline tw-group desktop-hover:hover:tw-opacity-80 tw-transition-all tw-duration-300"
      >
        <span
          className={`tw-inline-block${shouldLimit ? " tw-truncate tw-max-w-[8rem]" : ""
            }`}
        >
          <span className="tw-text-sm tw-font-medium tw-text-iron-50 tw-transition-all tw-duration-300 desktop-hover:group-hover:tw-text-iron-300">
            {log.invoker.handle}
          </span>
        </span>
      </Link>
    </UserProfileTooltipWrapper>
  );

  return (
    <div className="tw-p-3 hover:tw-bg-white/[0.02] tw-transition-colors">
      {isMobile ? (
        <div className="tw-flex tw-gap-3">
          {avatar}
          <div className="tw-flex tw-flex-col tw-flex-1 tw-min-w-0">
            <div className="tw-flex tw-items-center tw-justify-between tw-gap-2">
              {handleLink}
              <TimeStamp
                createdAt={log.created_at}
                iconClassName="tw-w-3 tw-h-3 tw-text-iron-400"
                textClassName="tw-text-xs tw-font-medium tw-text-iron-400"
              />
            </div>

            <div className="tw-flex tw-flex-wrap tw-items-center tw-gap-x-1.5 tw-gap-y-1.5 tw-mt-1">
              <VoteSummary log={log} creditType={creditType} />
            </div>
          </div>
        </div>
      ) : (
        <div className="tw-flex tw-items-center tw-justify-between tw-gap-x-2">
          <div className="tw-flex tw-items-center tw-gap-x-2 tw-gap-y-2">
            {avatar}
            <div className="tw-inline-flex tw-items-center tw-gap-x-1 tw-gap-y-1 tw-flex-wrap">
              {handleLink}
              <VoteSummary log={log} creditType={creditType} />
            </div>
          </div>
          <TimeStamp
            createdAt={log.created_at}
            iconClassName="tw-w-3.5 tw-h-3.5 tw-text-iron-600 tw-flex-shrink-0"
            textClassName="tw-text-xs tw-font-medium tw-text-iron-600"
          />
        </div>
      )}
    </div>
  );
};
