import UserProfileTooltipWrapper from "@/components/utils/tooltip/UserProfileTooltipWrapper";
import type { ApiDropVoteEditLog } from "@/generated/models/ApiDropVoteEditLog";
import type { ApiDropVoter } from "@/generated/models/ApiDropVoter";
import type { ApiIdentityOverview } from "@/generated/models/ApiIdentityOverview";
import type { ApiWaveCreditType } from "@/generated/models/ApiWaveCreditType";
import {
  isAutoGeneratedHandle,
  isEthereumAddress,
} from "@/helpers/AllowlistToolHelpers";
import { formatNumberWithCommas, getTimeAgoShort } from "@/helpers/Helpers";
import { WAVE_VOTING_LABELS } from "@/helpers/waves/waves.constants";
import { resolveIpfsUrlSync } from "@/components/ipfs/IPFSContext";
import Image from "next/image";
import Link from "next/link";

interface ParticipationDropVoteDetailsVoterRowProps {
  readonly voter: ApiDropVoter;
  readonly creditType: ApiWaveCreditType;
}

interface ParticipationDropVoteDetailsLogRowProps {
  readonly log: ApiDropVoteEditLog;
  readonly creditType: ApiWaveCreditType;
}

const getIdentityLabel = (identity: ApiIdentityOverview): string =>
  identity.handle ?? identity.primary_address;

const getIdentityTooltipKey = (identity: ApiIdentityOverview): string =>
  identity.handle ?? identity.primary_address;

const shouldLimitIdentityLabel = (label: string): boolean =>
  isEthereumAddress(label) || isAutoGeneratedHandle(label);

const getVoteColorClass = (vote: number): string => {
  if (vote > 0) {
    return "tw-text-emerald-400";
  }

  if (vote < 0) {
    return "tw-text-rose-400";
  }

  return "tw-text-iron-300";
};

const formatSignedVote = (vote: number): string => {
  if (vote === 0) {
    return "0";
  }

  const sign = vote > 0 ? "+" : "-";
  return `${sign}${formatNumberWithCommas(Math.abs(vote))}`;
};

const normalizeDropVoteLogTimestampMs = (
  createdAt: number | string | Date
): number => {
  if (createdAt instanceof Date) {
    return createdAt.getTime();
  }

  if (typeof createdAt === "string") {
    const asNumber = Number(createdAt);
    if (Number.isFinite(asNumber)) {
      return normalizeDropVoteLogTimestampMs(asNumber);
    }

    return new Date(createdAt).getTime();
  }

  if (!Number.isFinite(createdAt)) {
    return Date.now();
  }

  return createdAt < 1_000_000_000_000 ? createdAt * 1000 : createdAt;
};

function VoterAvatar({ identity }: { readonly identity: ApiIdentityOverview }) {
  const label = getIdentityLabel(identity);
  const avatarClassName =
    "tw-size-7 tw-flex-shrink-0 tw-rounded-md tw-bg-iron-800 tw-object-contain tw-ring-1 tw-ring-white/10";

  if (!identity.pfp) {
    return <div className={avatarClassName} aria-hidden="true" />;
  }

  // Voter avatars can come from arbitrary remote hosts, so this stays unoptimized.
  return (
    <Image
      unoptimized
      src={resolveIpfsUrlSync(identity.pfp)}
      alt={`${label}'s avatar`}
      width={28}
      height={28}
      className={avatarClassName}
    />
  );
}

function VoterIdentityLink({
  identity,
}: {
  readonly identity: ApiIdentityOverview;
}) {
  const label = getIdentityLabel(identity);
  const shouldLimit = shouldLimitIdentityLabel(label);

  return (
    <UserProfileTooltipWrapper user={getIdentityTooltipKey(identity)}>
      <Link
        href={`/${label}`}
        className="tw-group tw-min-w-0 tw-no-underline tw-transition-all tw-duration-300 desktop-hover:hover:tw-opacity-80"
      >
        <span
          className={`tw-block tw-min-w-0 ${
            shouldLimit ? "tw-max-w-[8rem] tw-truncate" : ""
          }`}
        >
          <span className="tw-text-sm tw-font-medium tw-text-iron-50 tw-transition-all tw-duration-300 desktop-hover:group-hover:tw-text-iron-300">
            {label}
          </span>
        </span>
      </Link>
    </UserProfileTooltipWrapper>
  );
}

export function ParticipationDropVoteDetailsVoterRow({
  voter,
  creditType,
}: ParticipationDropVoteDetailsVoterRowProps) {
  const voteColorClass = getVoteColorClass(voter.vote);

  return (
    <div className="tw-flex tw-items-center tw-justify-between tw-gap-3 tw-px-3 tw-py-2.5 tw-transition-colors hover:tw-bg-white/[0.03]">
      <div className="tw-flex tw-min-w-0 tw-items-center tw-gap-2.5">
        <VoterAvatar identity={voter.voter} />
        <VoterIdentityLink identity={voter.voter} />
      </div>
      <span
        className={`tw-shrink-0 tw-whitespace-nowrap tw-text-sm tw-font-semibold tw-tabular-nums ${voteColorClass}`}
      >
        {formatSignedVote(voter.vote)} {WAVE_VOTING_LABELS[creditType]}
      </span>
    </div>
  );
}

export function ParticipationDropVoteDetailsLogRow({
  log,
  creditType,
}: ParticipationDropVoteDetailsLogRowProps) {
  const newVoteColorClass = getVoteColorClass(log.new_vote);
  const timeAgo = getTimeAgoShort(
    normalizeDropVoteLogTimestampMs(log.created_at)
  );

  return (
    <div className="tw-px-3 tw-py-2.5 tw-transition-colors hover:tw-bg-white/[0.03]">
      <div className="tw-flex tw-items-start tw-gap-2.5">
        <VoterAvatar identity={log.voter} />
        <div className="tw-min-w-0 tw-flex-1">
          <div className="tw-flex tw-items-center tw-justify-between tw-gap-3">
            <VoterIdentityLink identity={log.voter} />
            <span className="tw-shrink-0 tw-whitespace-nowrap tw-text-xs tw-font-medium tw-text-iron-500">
              {timeAgo}
            </span>
          </div>
          <div className="tw-mt-1 tw-flex tw-flex-wrap tw-items-center tw-gap-x-1.5 tw-gap-y-1 tw-text-sm">
            {log.old_vote === 0 ? (
              <span className="tw-text-iron-500">voted</span>
            ) : (
              <>
                <span className="tw-text-iron-500">changed</span>
                <span className="tw-whitespace-nowrap tw-font-medium tw-tabular-nums tw-text-iron-400">
                  {formatSignedVote(log.old_vote)}
                </span>
                <span className="tw-text-iron-600">-&gt;</span>
              </>
            )}
            <span
              className={`tw-whitespace-nowrap tw-font-semibold tw-tabular-nums ${newVoteColorClass}`}
            >
              {formatSignedVote(log.new_vote)} {WAVE_VOTING_LABELS[creditType]}
            </span>
          </div>
        </div>
      </div>
    </div>
  );
}
