"use client";

import React, { memo, useRef } from "react";
import { useClickAway } from "react-use";
import { useSeizeConnectContext } from "@/components/auth/SeizeConnectContext";
import { useIdentity } from "@/hooks/useIdentity";
import {
  EllipsisVerticalIcon,
  UserCircleIcon,
} from "@heroicons/react/24/outline";
import DropPfp from "@/components/drops/create/utils/DropPfp";
import { DropPartSize } from "@/components/drops/view/part/DropPart";
import UserLevel from "@/components/user/utils/level/UserLevel";
import HeaderUserConnect from "@/components/header/user/HeaderUserConnect";
import HeaderUserProxyDropdown from "@/components/header/user/proxy/HeaderUserProxyDropdown";
import {
  isEthereumAddress,
  isAutoGeneratedHandle,
} from "@/helpers/AllowlistToolHelpers";
import PrimaryButton from "@/components/utils/button/PrimaryButton";

interface DesktopSidebarUserProps {
  isCollapsed: boolean;
  showUserMenu: boolean;
  onToggleUserMenu: () => void;
  profile: any;
}

function DesktopSidebarUser({
  isCollapsed,
  showUserMenu,
  onToggleUserMenu,
  profile: parentProfile,
}: DesktopSidebarUserProps) {
  const { address, seizeConnect } = useSeizeConnectContext();
  const dropdownRef = useRef<HTMLDivElement>(null);
  const buttonRef = useRef<HTMLButtonElement>(null);

  // Click away that properly handles button clicks
  useClickAway(dropdownRef, (event) => {
    if (
      showUserMenu &&
      buttonRef.current &&
      !buttonRef.current.contains(event.target as Node)
    ) {
      onToggleUserMenu();
    }
  });

  const { profile: localProfile, isLoading } = useIdentity({
    handleOrWallet: address || "",
    initialProfile: null,
  });

  const profile = parentProfile || localProfile;

  const containerClasses = `tw-mt-auto tw-relative tw-w-full tw-group ${
    isCollapsed ? "tw-px-2 tw-py-3" : "tw-px-4 tw-py-4"
  }`;

  if (!address) {
    return (
      <div className={containerClasses}>
        {isCollapsed ? (
          <div
            data-tooltip-id="sidebar-tooltip"
            data-tooltip-content="Connect Wallet"
          >
            <button
              className="tw-w-full tw-flex tw-items-center tw-no-underline tw-rounded-xl tw-border-none tw-transition-colors tw-duration-200 tw-h-12 tw-cursor-pointer focus:tw-outline-none focus-visible:tw-ring-2 focus-visible:tw-ring-iron-500 focus-visible:tw-ring-offset-2 tw-font-medium tw-text-base tw-justify-center tw-px-2 tw-text-iron-400 tw-bg-transparent desktop-hover:hover:tw-bg-iron-900 desktop-hover:hover:tw-text-white active:tw-bg-transparent"
              onClick={() => seizeConnect()}
              title="Connect Wallet"
            >
              <UserCircleIcon className="tw-h-6 tw-w-6 tw-flex-shrink-0" />
            </button>
          </div>
        ) : (
          <div className="[&>button]:tw-w-full">
            <HeaderUserConnect />
          </div>
        )}
      </div>
    );
  }

  // Loading state
  if (isLoading || !profile) {
    return (
      <div className={containerClasses}>
        <div
          className={`tw-flex tw-items-center tw-w-full tw-rounded-xl ${
            isCollapsed
              ? "tw-justify-center tw-px-2 tw-py-2"
              : "tw-justify-start tw-px-3 tw-gap-x-3 tw-py-2"
          }`}
        >
          <div className="tw-h-10 tw-w-10 tw-rounded-lg tw-bg-iron-800 tw-animate-pulse" />
          {!isCollapsed && (
            <div className="tw-flex tw-flex-col tw-gap-y-2 tw-flex-1">
              <div className="tw-h-4 tw-w-24 tw-bg-iron-800 tw-rounded tw-animate-pulse" />
              <div className="tw-h-3 tw-w-16 tw-bg-iron-800 tw-rounded tw-animate-pulse" />
            </div>
          )}
        </div>
      </div>
    );
  }

  // Derived state for authenticated user
  const displayHandle = profile.handle || address || "";
  const shouldTruncate =
    address && (isEthereumAddress(address) || isAutoGeneratedHandle(address));

  // Authenticated user
  return (
    <div className={containerClasses}>
      <button
        ref={buttonRef}
        onClick={onToggleUserMenu}
        className={`tw-group/user tw-border-none tw-bg-transparent tw-flex tw-items-center tw-w-full tw-rounded-xl tw-text-sm tw-font-semibold tw-text-white tw-transition-colors tw-duration-200 desktop-hover:hover:tw-bg-iron-900 ${
          isCollapsed
            ? "tw-justify-center tw-px-2"
            : "tw-justify-start tw-px-3 tw-gap-x-3 tw-py-2"
        }`}
        aria-label="Open user menu"
        aria-expanded={showUserMenu}
        aria-controls="user-menu"
      >
        <DropPfp pfpUrl={profile.pfp} size={DropPartSize.MEDIUM} />
        {!isCollapsed && (
          <>
            <div className="tw-flex tw-flex-col tw-items-start tw-justify-between tw-min-w-0 tw-flex-1 tw-whitespace-nowrap">
              <div
                className={`tw-text-white tw-font-medium tw-text-md tw-leading-tight tw-w-full tw-text-left tw-overflow-hidden -tw-mt-0.5 tw-mb-1 ${
                  shouldTruncate ? "tw-max-w-[8rem] tw-truncate" : ""
                }`}
              >
                {displayHandle}
              </div>
              <UserLevel level={profile.level} size="xxs" asSpan={true} />
            </div>
            <EllipsisVerticalIcon className="tw-h-5 tw-w-5 tw-flex-shrink-0 tw-text-iron-400 group-hover/user:tw-text-white" />
          </>
        )}
      </button>
      {showUserMenu && profile && (
        <div ref={dropdownRef}>
          <HeaderUserProxyDropdown
            profile={profile}
            isOpen={showUserMenu}
            onClose={onToggleUserMenu}
          />
        </div>
      )}
    </div>
  );
}

export default memo(DesktopSidebarUser);
