"use client";

import {
  EllipsisVerticalIcon,
  UserCircleIcon,
} from "@heroicons/react/24/outline";
import { memo, useEffect, useRef, useState } from "react";
import { useClickAway } from "react-use";
import { getConnectionProfileIndicator } from "@/components/auth/connection-state-indicator";
import { useSeizeConnectContext } from "@/components/auth/SeizeConnectContext";
import HeaderUserConnect from "@/components/header/user/HeaderUserConnect";
import HeaderUserProxyDropdown from "@/components/header/user/proxy/HeaderUserProxyDropdown";
import { resolveIpfsUrlSync } from "@/components/ipfs/IPFSContext";
import UserLevel from "@/components/user/utils/level/UserLevel";
import { DEFAULT_CONNECTED_PROFILE_FALLBACK_PFP } from "@/constants/constants";
import {
  isAutoGeneratedHandle,
  isEthereumAddress,
} from "@/helpers/AllowlistToolHelpers";
import { useIdentity } from "@/hooks/useIdentity";

interface WebSidebarUserProps {
  readonly isCollapsed: boolean;
  readonly profile: any;
}

function WebSidebarUser({
  isCollapsed,
  profile: parentProfile,
}: WebSidebarUserProps) {
  const PROFILE_DOUBLE_ACTIVATE_DELAY_MS = 280;
  const [showUserMenu, setShowUserMenu] = useState(false);
  const {
    address,
    seizeConnect,
    isAuthenticated,
    isConnected,
    connectedAccounts,
    seizeSwitchConnectedAccount,
  } = useSeizeConnectContext();
  const dropdownRef = useRef<HTMLDivElement>(null);
  const buttonRef = useRef<HTMLButtonElement>(null);
  const profileClickTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(
    null
  );

  useEffect(
    () => () => {
      if (profileClickTimeoutRef.current) {
        clearTimeout(profileClickTimeoutRef.current);
      }
    },
    []
  );

  // Click away that properly handles button clicks
  useClickAway(dropdownRef, (event) => {
    if (
      showUserMenu &&
      buttonRef.current &&
      !buttonRef.current.contains(event.target as Node)
    ) {
      setShowUserMenu(false);
    }
  });

  const { profile: localProfile, isLoading } = useIdentity({
    handleOrWallet: address || "",
    initialProfile: null,
  });

  const profile = parentProfile || localProfile;

  const containerClasses =
    "tw-mt-auto tw-relative tw-w-full tw-group tw-pb-2 tw-px-3";
  const resolvedPfp = profile?.pfp ? resolveIpfsUrlSync(profile.pfp) : null;
  const [avatarSrc, setAvatarSrc] = useState(
    resolvedPfp ?? DEFAULT_CONNECTED_PROFILE_FALLBACK_PFP
  );
  const isResolvedAvatar = !!resolvedPfp && avatarSrc === resolvedPfp;

  useEffect(() => {
    setAvatarSrc(resolvedPfp ?? DEFAULT_CONNECTED_PROFILE_FALLBACK_PFP);
  }, [resolvedPfp]);

  if (!address) {
    return (
      <div className={containerClasses}>
        {isCollapsed ? (
          <button
            className="tw-block tw-h-12 tw-w-full tw-cursor-pointer tw-rounded-xl tw-border-none tw-bg-transparent tw-px-2 tw-text-base tw-font-medium tw-text-iron-400 tw-no-underline tw-transition-colors tw-duration-200 focus:tw-outline-none focus-visible:tw-ring-2 focus-visible:tw-ring-iron-500 focus-visible:tw-ring-offset-2 active:tw-bg-transparent desktop-hover:hover:tw-text-white"
            onClick={() => seizeConnect()}
            title="Connect Wallet"
            data-tooltip-id="sidebar-tooltip"
            data-tooltip-content="Connect Wallet"
          >
            <div className="tw-flex tw-h-full tw-w-full tw-items-center">
              <div className="tw-flex tw-w-10 tw-flex-shrink-0 tw-items-center tw-justify-center">
                <UserCircleIcon className="tw-h-6 tw-w-6 tw-flex-shrink-0" />
              </div>
            </div>
          </button>
        ) : (
          <div className="tw-mt-2 tw-w-full tw-px-2">
            <div className="[&>button]:tw-w-full">
              <HeaderUserConnect />
            </div>
          </div>
        )}
      </div>
    );
  }

  // Loading state
  if (isLoading || !profile) {
    return (
      <div className={containerClasses}>
        <div
          className={`tw-flex tw-w-full tw-items-center tw-rounded-xl tw-px-2 tw-py-2 ${
            isCollapsed ? "tw-justify-center" : "tw-justify-start tw-gap-x-3"
          }`}
        >
          <div className="tw-h-10 tw-w-10 tw-flex-shrink-0 tw-animate-pulse tw-rounded-lg tw-bg-iron-800" />
          {!isCollapsed && (
            <div className="tw-flex tw-flex-1 tw-flex-col tw-gap-y-2">
              <div className="tw-h-4 tw-w-24 tw-animate-pulse tw-rounded tw-bg-iron-800" />
              <div className="tw-h-3 tw-w-16 tw-animate-pulse tw-rounded tw-bg-iron-800" />
            </div>
          )}
        </div>
      </div>
    );
  }

  // Derived state for authenticated user
  const displayHandle = profile.handle || address || "";
  const shouldTruncate =
    address && (isEthereumAddress(address) || isAutoGeneratedHandle(address));
  const connectionIndicator = getConnectionProfileIndicator({
    isAuthenticated,
    isConnected,
  });

  const switchToNextConnectedAccount = (): boolean => {
    if (connectedAccounts.length < 2) {
      return false;
    }

    const activeIndex = connectedAccounts.findIndex(
      (account) => account.isActive
    );
    const currentIndex = Math.max(activeIndex, 0);
    const nextAccount =
      connectedAccounts[(currentIndex + 1) % connectedAccounts.length];
    if (!nextAccount) {
      return false;
    }

    seizeSwitchConnectedAccount(nextAccount.address);
    return true;
  };

  const toggleUserMenu = () => {
    setShowUserMenu((current) => !current);
  };

  const onProfileActivate = () => {
    if (profileClickTimeoutRef.current) {
      clearTimeout(profileClickTimeoutRef.current);
      profileClickTimeoutRef.current = null;

      const didSwitchAccount = switchToNextConnectedAccount();
      if (!didSwitchAccount) {
        toggleUserMenu();
      }
      return;
    }

    profileClickTimeoutRef.current = setTimeout(() => {
      profileClickTimeoutRef.current = null;
      toggleUserMenu();
    }, PROFILE_DOUBLE_ACTIVATE_DELAY_MS);
  };

  // Authenticated user
  return (
    <div className={containerClasses}>
      <button
        ref={buttonRef}
        onClick={onProfileActivate}
        className={`tw-group/user tw-mt-1 tw-w-full tw-rounded-xl tw-border-none tw-bg-transparent tw-px-2 tw-py-2 tw-text-sm tw-font-semibold tw-text-white tw-transition-colors tw-duration-200 ${
          isCollapsed ? "" : "desktop-hover:hover:tw-bg-iron-900"
        }`}
        aria-label="Open user menu"
        aria-expanded={showUserMenu}
        aria-controls="user-menu"
      >
        <div
          className={`tw-flex tw-w-full tw-items-center ${
            isCollapsed ? "" : "tw-gap-x-2"
          }`}
        >
          <div
            className={`tw-relative tw-flex tw-h-10 tw-w-10 tw-flex-shrink-0 tw-items-center tw-justify-center tw-overflow-hidden tw-rounded-xl ${connectionIndicator.avatarClassName}`}
            title={connectionIndicator.title}
          >
            <img
              src={avatarSrc}
              alt={displayHandle || "Connected account"}
              onError={(event) => {
                if (
                  event.currentTarget.src.endsWith(
                    DEFAULT_CONNECTED_PROFILE_FALLBACK_PFP
                  )
                ) {
                  return;
                }
                setAvatarSrc(DEFAULT_CONNECTED_PROFILE_FALLBACK_PFP);
              }}
              className={`tw-absolute tw-inset-0 tw-block tw-h-full tw-w-full tw-rounded-xl tw-bg-iron-900 ${
                isResolvedAvatar
                  ? "tw-object-contain"
                  : "tw-object-cover tw-grayscale"
              }`}
            />
            {connectionIndicator.overlayClassName && (
              <div
                className={`tw-pointer-events-none tw-absolute tw-inset-0 tw-rounded-xl ${connectionIndicator.overlayClassName}`}
              />
            )}
          </div>
          {!isCollapsed && (
            <>
              <div className="tw-flex tw-min-w-0 tw-flex-1 tw-flex-col tw-items-start tw-justify-between tw-whitespace-nowrap">
                <div
                  className={`-tw-mt-0.5 tw-mb-1 tw-w-full tw-overflow-hidden tw-text-left tw-text-md tw-font-medium tw-leading-tight tw-text-white ${
                    shouldTruncate ? "tw-max-w-[8rem] tw-truncate" : ""
                  }`}
                >
                  {displayHandle}
                </div>
                <UserLevel level={profile.level} size="xxs" asSpan={true} />
              </div>
              <EllipsisVerticalIcon className="tw-h-5 tw-w-5 tw-flex-shrink-0 tw-text-iron-400 group-hover/user:tw-text-white" />
            </>
          )}
        </div>
      </button>
      {showUserMenu && profile && (
        <div ref={dropdownRef}>
          <HeaderUserProxyDropdown
            profile={profile}
            isOpen={showUserMenu}
            onClose={() => setShowUserMenu(false)}
          />
        </div>
      )}
    </div>
  );
}

export default memo(WebSidebarUser);
