"use client";

import { EllipsisVerticalIcon } from "@heroicons/react/24/outline";
import { memo, useEffect, useId, useRef, useState } from "react";
import Link from "next/link";
import { useClickAway } from "react-use";
import { getConnectionProfileIndicator } from "@/components/auth/connection-state-indicator";
import { HeaderConnectModal } from "@/components/header/share/HeaderShare";
import { useSeizeConnectContext } from "@/components/auth/SeizeConnectContext";
import HeaderUserMenuDropdown from "@/components/header/user/HeaderUserMenuDropdown";
import { resolveIpfsUrlSync } from "@/components/ipfs/IPFSContext";
import UserLevel from "@/components/user/utils/level/UserLevel";
import {
  isAutoGeneratedHandle,
  isEthereumAddress,
} from "@/helpers/AllowlistToolHelpers";
import { useIsMobileDeviceStatus } from "@/hooks/isMobileDevice";
import useCapacitor from "@/hooks/useCapacitor";
import { useAuth } from "@/components/auth/Auth";
import { useArtworkDocumentationAccess } from "@/hooks/artwork-documentation/useArtworkDocumentationAccess";
import WebSidebarAccountAvatar from "./WebSidebarAccountAvatar";
import { useSidebarIdentity } from "./useSidebarIdentity";
import type { ApiIdentity } from "@/generated/models/ApiIdentity";
import { DEFAULT_LOCALE } from "@/i18n/locales";
import { t } from "@/i18n/messages";
import { PROFILE_DOUBLE_ACTIVATE_DELAY_MS } from "@/components/header/profile-activation.constants";

interface WebSidebarUserProps {
  readonly isCollapsed: boolean;
  readonly profile: ApiIdentity | null;
}

function WebSidebarUser({
  isCollapsed,
  profile: parentProfile,
}: WebSidebarUserProps) {
  const [showUserMenu, setShowUserMenu] = useState(false);
  const [showConnectModal, setShowConnectModal] = useState(false);
  const accountDescriptionId = useId();
  const capacitor = useCapacitor();
  const { isMobileDevice, isDeviceDetectionResolved } =
    useIsMobileDeviceStatus();
  const canUseDesktopConnect =
    !capacitor.isCapacitor && isDeviceDetectionResolved && !isMobileDevice;
  const {
    address,
    seizeConnect,
    seizeConnectFresh,
    connectionState,
    hasValidWalletAuth: isAuthenticated,
    isConnected,
    connectedAccounts,
    connectedAccountUnreadNotifications,
    seizeSwitchConnectedAccount,
  } = useSeizeConnectContext();
  const dropdownRef = useRef<HTMLDivElement>(null);
  const buttonRef = useRef<HTMLButtonElement>(null);
  const profileClickTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(
    null
  );
  // Click away that properly handles button clicks
  useClickAway(dropdownRef, (event) => {
    if (
      showUserMenu &&
      buttonRef.current &&
      !buttonRef.current.contains(event.target as Node)
    ) {
      setShowUserMenu(false);
    }
  });

  const {
    profile: localProfile,
    isLoading,
    isError,
    isFetching,
    refetch,
  } = useSidebarIdentity(address);

  const profile = parentProfile || localProfile;
  const { connectedProfile, activeProfileProxy, setToast } = useAuth();
  // Stay subscribed while the account UI is mounted, including while its menu
  // is closed. No persistent cache or menu-triggered request is needed.
  const artworkAccess = useArtworkDocumentationAccess();
  const accountScope = JSON.stringify([
    address,
    connectedProfile?.id,
    activeProfileProxy?.id,
    isAuthenticated,
  ]);
  const containerClasses =
    "tw-relative tw-block tw-h-16 tw-w-full tw-shrink-0 tw-px-3 tw-pb-2";
  const rowClasses =
    "motion-safe:tw-animate-sidebar-account-fade-in tw-flex tw-h-14 tw-w-full tw-items-center tw-gap-x-2 tw-rounded-xl tw-border-none tw-bg-transparent tw-px-2 tw-py-2";
  const avatarClasses =
    "tw-relative tw-flex tw-size-10 tw-shrink-0 tw-items-center tw-justify-center tw-overflow-hidden tw-rounded-xl tw-bg-iron-900 tw-ring-2 tw-ring-inset tw-ring-white/10";
  const resolvedPfp = profile?.pfp ? resolveIpfsUrlSync(profile.pfp) : null;

  useEffect(
    () => () => {
      if (profileClickTimeoutRef.current) {
        clearTimeout(profileClickTimeoutRef.current);
      }
    },
    []
  );

  if (
    connectionState === "initializing" ||
    (address && (isLoading || isFetching) && !profile)
  ) {
    return (
      <output
        className={containerClasses}
        data-sidebar-account="loading"
        aria-label={t(DEFAULT_LOCALE, "webSidebar.account.loading")}
      >
        <span className={rowClasses}>
          <span
            className={`${avatarClasses} tw-bg-iron-800 motion-safe:tw-animate-pulse`}
          />
          {!isCollapsed && (
            <span
              className="tw-flex tw-flex-1 tw-flex-col tw-gap-y-2"
              aria-hidden="true"
            >
              <span className="tw-h-4 tw-w-24 tw-rounded tw-bg-iron-800 motion-safe:tw-animate-pulse" />
              <span className="tw-h-3 tw-w-16 tw-rounded tw-bg-iron-800 motion-safe:tw-animate-pulse" />
            </span>
          )}
        </span>
      </output>
    );
  }

  if (address && !profile && !isError) {
    const label = t(DEFAULT_LOCALE, "profileSetup.createAction");
    return (
      <div className={containerClasses} data-sidebar-account="empty">
        <Link
          href={`/${address.toLowerCase()}`}
          className={`${rowClasses} tw-text-iron-400 tw-no-underline focus-visible:tw-outline focus-visible:tw-outline-2 focus-visible:tw-outline-primary-400 desktop-hover:hover:tw-text-white`}
          aria-label={label}
          data-tooltip-id="sidebar-tooltip"
          data-tooltip-content={label}
          data-tooltip-hidden={!isCollapsed}
        >
          <span className={avatarClasses}>
            <WebSidebarAccountAvatar src={null} />
          </span>
          {!isCollapsed && (
            <span className="tw-truncate tw-text-sm tw-font-medium">
              {label}
            </span>
          )}
        </Link>
      </div>
    );
  }

  if (!address || !profile) {
    const label = t(
      DEFAULT_LOCALE,
      address ? "webSidebar.account.retry" : "webSidebar.account.connect"
    );
    return (
      <div
        className={containerClasses}
        data-sidebar-account={address ? "error" : "signed-out"}
      >
        {address && (
          <output className="tw-sr-only" aria-live="polite">
            {label}
          </output>
        )}
        <button
          type="button"
          className={`${rowClasses} tw-cursor-pointer tw-text-iron-400 focus-visible:tw-outline focus-visible:tw-outline-2 focus-visible:tw-outline-primary-400 desktop-hover:hover:tw-text-white`}
          onClick={() => {
            if (address) {
              void refetch();
            } else if (isCollapsed) {
              seizeConnect();
            } else {
              void seizeConnectFresh().catch(() =>
                setToast({
                  message: t(
                    DEFAULT_LOCALE,
                    "webSidebar.account.connectFailed"
                  ),
                  type: "error",
                })
              );
            }
          }}
          aria-label={label}
          data-tooltip-id="sidebar-tooltip"
          data-tooltip-content={label}
          data-tooltip-hidden={!isCollapsed}
        >
          <span className={avatarClasses}>
            <WebSidebarAccountAvatar src={null} />
          </span>
          {!isCollapsed && (
            <span className="tw-truncate tw-text-sm tw-font-medium">
              {label}
            </span>
          )}
        </button>
      </div>
    );
  }

  // Derived state for authenticated user
  const displayHandle = profile.handle || address || "";
  const shouldTruncate =
    address && (isEthereumAddress(address) || isAutoGeneratedHandle(address));
  const connectionIndicator = getConnectionProfileIndicator({
    isAuthenticated,
    isConnected,
  });
  const hasUnreadOnOtherConnectedProfiles = connectedAccounts.some(
    (account) =>
      !account.isActive &&
      (connectedAccountUnreadNotifications?.[account.address.toLowerCase()] ??
        0) > 0
  );
  const hasMultipleConnectedAccounts = connectedAccounts.length > 1;

  const toggleUserMenu = () => {
    setShowUserMenu((current) => !current);
  };

  const switchToNextConnectedAccount = (): boolean => {
    if (!hasMultipleConnectedAccounts) {
      return false;
    }

    const activeIndex = connectedAccounts.findIndex(
      (account) => account.isActive
    );
    const currentIndex = Math.max(activeIndex, 0);
    const nextAccount =
      connectedAccounts[(currentIndex + 1) % connectedAccounts.length];

    if (!nextAccount) {
      return false;
    }

    try {
      seizeSwitchConnectedAccount(nextAccount.address);
      setShowUserMenu(false);
      return true;
    } catch (error) {
      console.error(
        "Failed to switch connected account from desktop sidebar",
        error
      );
      return false;
    }
  };

  const handleProfileActivate = () => {
    if (!hasMultipleConnectedAccounts) {
      if (profileClickTimeoutRef.current) {
        clearTimeout(profileClickTimeoutRef.current);
        profileClickTimeoutRef.current = null;
      }
      toggleUserMenu();
      return;
    }

    if (profileClickTimeoutRef.current) {
      clearTimeout(profileClickTimeoutRef.current);
      profileClickTimeoutRef.current = null;

      switchToNextConnectedAccount();
      return;
    }

    toggleUserMenu();
    profileClickTimeoutRef.current = setTimeout(() => {
      profileClickTimeoutRef.current = null;
    }, PROFILE_DOUBLE_ACTIVATE_DELAY_MS);
  };

  const onOpenConnect = () => {
    setShowUserMenu(false);
    setShowConnectModal(true);
  };

  // Authenticated user
  return (
    <div className={containerClasses} data-sidebar-account="profile">
      <button
        type="button"
        ref={buttonRef}
        onClick={handleProfileActivate}
        className={`${rowClasses} tw-group/user tw-text-sm tw-font-semibold tw-text-white tw-transition-colors tw-duration-200 focus-visible:tw-outline focus-visible:tw-outline-2 focus-visible:tw-outline-primary-400 ${
          isCollapsed ? "" : "desktop-hover:hover:tw-bg-iron-900"
        }`}
        aria-label={t(
          DEFAULT_LOCALE,
          hasMultipleConnectedAccounts
            ? "webSidebar.accountMenu.openWithSwitchAriaLabel"
            : "webSidebar.accountMenu.openAriaLabel"
        )}
        aria-expanded={showUserMenu}
        aria-describedby={accountDescriptionId}
        aria-controls="user-menu"
      >
        <span id={accountDescriptionId} className="tw-sr-only">
          {displayHandle}
        </span>
        <div
          className={`tw-flex tw-w-full tw-items-center ${
            isCollapsed ? "" : "tw-gap-x-2"
          }`}
        >
          <div className="tw-relative tw-h-10 tw-w-10 tw-flex-shrink-0">
            <div
              className={`tw-relative tw-flex tw-h-10 tw-w-10 tw-items-center tw-justify-center tw-overflow-hidden tw-rounded-xl tw-transition-[box-shadow,filter] tw-duration-200 tw-ease-out ${connectionIndicator.avatarClassName} ${
                isCollapsed
                  ? "desktop-hover:group-hover/user:tw-shadow-[0_0_0_1px_rgba(255,255,255,0.1),0_0_14px_rgba(255,255,255,0.06)] desktop-hover:group-hover/user:tw-brightness-[1.05]"
                  : ""
              }`}
              title={connectionIndicator.title}
            >
              <WebSidebarAccountAvatar
                key={`${address}:${resolvedPfp ?? "default"}`}
                src={resolvedPfp}
              />
              {connectionIndicator.overlayClassName && (
                <div
                  className={`tw-pointer-events-none tw-absolute tw-inset-0 tw-rounded-xl ${connectionIndicator.overlayClassName}`}
                />
              )}
            </div>
            {hasUnreadOnOtherConnectedProfiles && (
              <div
                className="tw-absolute tw-right-[-6px] tw-top-[-6px] tw-size-3 tw-rounded-full tw-bg-indigo-500 tw-shadow-sm"
                aria-hidden="true"
              />
            )}
          </div>
          {!isCollapsed && (
            <>
              <div className="tw-flex tw-min-w-0 tw-flex-1 tw-flex-col tw-items-start tw-justify-between tw-whitespace-nowrap">
                <div
                  className={`-tw-mt-0.5 tw-mb-1 tw-w-full tw-overflow-hidden tw-text-left tw-text-md tw-font-medium tw-leading-tight tw-text-white ${
                    shouldTruncate ? "tw-max-w-[8rem] tw-truncate" : ""
                  }`}
                >
                  {displayHandle}
                </div>
                <UserLevel level={profile.level} size="xxs" asSpan={true} />
              </div>
              <EllipsisVerticalIcon className="tw-h-5 tw-w-5 tw-flex-shrink-0 tw-text-iron-400 group-hover/user:tw-text-white" />
            </>
          )}
        </div>
      </button>
      {showUserMenu && profile && (
        <div ref={dropdownRef}>
          <HeaderUserMenuDropdown
            key={accountScope}
            artworkDocumentationEnabled={
              isAuthenticated &&
              connectedProfile?.id === profile.id &&
              !artworkAccess.isError &&
              artworkAccess.enabled
            }
            profile={profile}
            isOpen={showUserMenu}
            onClose={() => setShowUserMenu(false)}
            onOpenConnect={canUseDesktopConnect ? onOpenConnect : undefined}
          />
        </div>
      )}
      <HeaderConnectModal
        show={canUseDesktopConnect && showConnectModal}
        onClose={() => setShowConnectModal(false)}
      />
    </div>
  );
}

export default memo(WebSidebarUser);
