"use client";

import UserProfileTooltipWrapper from "@/components/utils/tooltip/UserProfileTooltipWrapper";
import { QueryKey } from "@/components/react-query-wrapper/ReactQueryWrapper";
import { updateDropInCachedDrops } from "@/components/react-query-wrapper/utils/updateAttachmentInCachedDrops";
import { useAuth } from "@/components/auth/Auth";
import { resolveIpfsUrlSync } from "@/components/ipfs/IPFSContext";
import type { ApiDrop } from "@/generated/models/ApiDrop";
import type { ApiDropPoll } from "@/generated/models/ApiDropPoll";
import type { ApiDropPollOption } from "@/generated/models/ApiDropPollOption";
import type { ApiIdentityOverview } from "@/generated/models/ApiIdentityOverview";
import {
  formatNumberWithCommas,
  formatAddress,
  getTimeUntil,
} from "@/helpers/Helpers";
import {
  isAutoGeneratedHandle,
  isEthereumAddress,
} from "@/helpers/AllowlistToolHelpers";
import { useDropPollOptionVoters } from "@/hooks/useDropPollOptionVoters";
import { voteDropPollV2 } from "@/services/api/wave-drops-v2-api";
import { useMyStreamOptional } from "@/contexts/wave/MyStreamContext";
import { ProcessIncomingDropType } from "@/contexts/wave/hooks/useWaveRealtimeUpdater";
import { CheckCircleIcon } from "@heroicons/react/24/solid";
import { ChevronDownIcon } from "@heroicons/react/24/outline";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import Image from "next/image";
import Link from "next/link";
import { useCallback, useState } from "react";

type PollView = "vote" | "results";

interface WaveDropPollProps {
  readonly drop: ApiDrop;
}

interface LocalPollOverride {
  readonly sourcePoll: ApiDropPoll | undefined;
  readonly poll: ApiDropPoll | null;
}

interface PollInteractionState {
  readonly pollKey: string;
  readonly view: PollView;
  readonly selectedOptionNos: readonly number[];
  readonly expandedOptionNo: number | null;
}

const getDefaultPollView = (poll: ApiDropPoll): PollView =>
  poll.is_open && poll.voted.length === 0 ? "vote" : "results";

const getVotedKey = (poll: ApiDropPoll): string =>
  [...poll.voted].sort((a, b) => a - b).join(",");

const getPollInteractionKey = (poll: ApiDropPoll): string =>
  `${poll.id}:${poll.is_open ? "open" : "closed"}:${getVotedKey(poll)}`;

const getDefaultPollInteractionState = (
  poll: ApiDropPoll
): PollInteractionState => ({
  pollKey: getPollInteractionKey(poll),
  view: getDefaultPollView(poll),
  selectedOptionNos: [...poll.voted],
  expandedOptionNo: null,
});

const getScopedPollInteractionState = (
  current: PollInteractionState | null,
  poll: ApiDropPoll
): PollInteractionState => {
  const pollKey = getPollInteractionKey(poll);
  return current?.pollKey === pollKey
    ? current
    : getDefaultPollInteractionState(poll);
};

const getPollToggleLabel = ({
  effectiveView,
  hasVoted,
}: {
  readonly effectiveView: PollView;
  readonly hasVoted: boolean;
}): string => {
  if (effectiveView === "vote") {
    return "Results";
  }

  return hasVoted ? "Change vote" : "Vote";
};

const getPollSubmitLabel = ({
  isPending,
  hasVoted,
}: {
  readonly isPending: boolean;
  readonly hasVoted: boolean;
}): string => {
  if (isPending) {
    return "Submitting...";
  }

  return hasVoted ? "Update vote" : "Submit vote";
};

const getIdentityLabel = (identity: ApiIdentityOverview): string =>
  identity.handle ?? formatAddress(identity.primary_address);

const getIdentityHrefValue = (identity: ApiIdentityOverview): string =>
  identity.handle ?? identity.primary_address;

const shouldLimitIdentityLabel = (label: string): boolean =>
  isEthereumAddress(label) || isAutoGeneratedHandle(label);

const getPollClosingLabel = (poll: ApiDropPoll): string => {
  const time = getTimeUntil(poll.closing_time).trim();
  return poll.is_open ? `Closes ${time}` : `Closed ${time}`;
};

function PollVoterAvatar({
  identity,
}: {
  readonly identity: ApiIdentityOverview;
}) {
  const label = getIdentityLabel(identity);
  const avatarClassName =
    "tw-size-7 tw-flex-shrink-0 tw-rounded-md tw-bg-iron-800 tw-object-contain tw-ring-1 tw-ring-white/10";

  if (!identity.pfp) {
    return <div className={avatarClassName} aria-hidden="true" />;
  }

  return (
    <Image
      unoptimized
      src={resolveIpfsUrlSync(identity.pfp)}
      alt={`${label}'s avatar`}
      width={28}
      height={28}
      className={avatarClassName}
    />
  );
}

function PollVoterRow({ voter }: { readonly voter: ApiIdentityOverview }) {
  const label = getIdentityLabel(voter);
  const hrefValue = getIdentityHrefValue(voter);
  const shouldLimit = shouldLimitIdentityLabel(label);

  return (
    <div className="tw-flex tw-min-w-0 tw-items-center tw-gap-2.5 tw-px-3 tw-py-2">
      <PollVoterAvatar identity={voter} />
      <UserProfileTooltipWrapper user={hrefValue}>
        <Link
          href={`/${encodeURIComponent(hrefValue)}`}
          onClick={(event) => event.stopPropagation()}
          className="tw-group tw-min-w-0 tw-no-underline tw-transition-all tw-duration-300 desktop-hover:hover:tw-opacity-80"
        >
          <span
            className={`tw-block tw-min-w-0 ${
              shouldLimit ? "tw-max-w-[10rem] tw-truncate" : "tw-break-all"
            }`}
          >
            <span className="tw-text-sm tw-font-medium tw-text-iron-50 tw-transition-all tw-duration-300 desktop-hover:group-hover:tw-text-iron-300">
              {label}
            </span>
          </span>
        </Link>
      </UserProfileTooltipWrapper>
    </div>
  );
}

function PollOptionVoters({
  dropId,
  option,
}: {
  readonly dropId: string;
  readonly option: ApiDropPollOption;
}) {
  const {
    voters,
    fetchNextPage,
    hasNextPage,
    isLoading,
    isFetchingNextPage,
    isError,
  } = useDropPollOptionVoters({
    dropId,
    optionNo: option.option_no,
    enabled: option.votes > 0,
  });

  if (option.votes === 0) {
    return (
      <div className="tw-px-3 tw-py-2 tw-text-xs tw-font-medium tw-text-iron-500">
        No votes yet
      </div>
    );
  }

  if (isLoading) {
    return (
      <div className="tw-px-3 tw-py-2 tw-text-xs tw-font-medium tw-text-iron-500">
        Loading voters...
      </div>
    );
  }

  if (isError) {
    return (
      <div className="tw-px-3 tw-py-2 tw-text-xs tw-font-medium tw-text-rose-300">
        Voters could not be loaded.
      </div>
    );
  }

  return (
    <div className="tw-border-t tw-border-solid tw-border-iron-800/70">
      <div className="tw-divide-y tw-divide-iron-800/70">
        {voters.map((voter) => (
          <PollVoterRow key={voter.id} voter={voter} />
        ))}
      </div>
      {hasNextPage && (
        <div className="tw-px-3 tw-pb-2">
          <button
            type="button"
            disabled={isFetchingNextPage}
            onClick={(event) => {
              event.stopPropagation();
              void fetchNextPage();
            }}
            className="tw-inline-flex tw-items-center tw-rounded-md tw-border tw-border-solid tw-border-iron-700 tw-bg-iron-900 tw-px-2.5 tw-py-1.5 tw-text-xs tw-font-semibold tw-text-iron-200 tw-transition disabled:tw-cursor-not-allowed disabled:tw-opacity-60 desktop-hover:hover:tw-border-iron-600 desktop-hover:hover:tw-bg-iron-800"
          >
            {isFetchingNextPage ? "Loading..." : "Load more"}
          </button>
        </div>
      )}
    </div>
  );
}

function PollVoteOption({
  option,
  checked,
  multichoice,
  groupName,
  disabled,
  onChange,
}: {
  readonly option: ApiDropPollOption;
  readonly checked: boolean;
  readonly multichoice: boolean;
  readonly groupName: string;
  readonly disabled: boolean;
  readonly onChange: (optionNo: number) => void;
}) {
  return (
    <label className="tw-flex tw-cursor-pointer tw-items-start tw-gap-3 tw-rounded-lg tw-border tw-border-solid tw-border-iron-800 tw-bg-iron-950/60 tw-p-3 tw-transition desktop-hover:hover:tw-border-iron-700 desktop-hover:hover:tw-bg-iron-900/80">
      <input
        type={multichoice ? "checkbox" : "radio"}
        name={groupName}
        checked={checked}
        disabled={disabled}
        onClick={(event) => event.stopPropagation()}
        onChange={() => onChange(option.option_no)}
        className="tw-mt-1 tw-size-4 tw-flex-shrink-0 tw-cursor-pointer tw-border-iron-600 tw-bg-iron-950 tw-text-primary-400 focus:tw-ring-primary-400"
      />
      <span className="tw-min-w-0 tw-break-words tw-text-sm tw-font-medium tw-leading-5 tw-text-iron-100">
        {option.option_string}
      </span>
    </label>
  );
}

function PollResultOption({
  option,
  totalVotes,
  isSelected,
  isExpanded,
  onToggle,
}: {
  readonly option: ApiDropPollOption;
  readonly totalVotes: number;
  readonly isSelected: boolean;
  readonly isExpanded: boolean;
  readonly onToggle: (optionNo: number) => void;
}) {
  const percentage =
    totalVotes > 0 ? Math.round((option.votes / totalVotes) * 100) : 0;

  return (
    <div className="tw-overflow-hidden tw-rounded-lg tw-border tw-border-solid tw-border-iron-800 tw-bg-iron-950/60">
      <button
        type="button"
        aria-expanded={isExpanded}
        onClick={(event) => {
          event.stopPropagation();
          onToggle(option.option_no);
        }}
        className="tw-relative tw-w-full tw-border-0 tw-bg-transparent tw-p-0 tw-text-left"
      >
        <div
          className="tw-absolute tw-inset-y-0 tw-left-0 tw-bg-primary-500/15"
          style={{ width: `${percentage}%` }}
          aria-hidden="true"
        />
        <div className="tw-relative tw-flex tw-min-w-0 tw-items-center tw-gap-3 tw-px-3 tw-py-2.5">
          <div className="tw-min-w-0 tw-flex-1">
            <div className="tw-flex tw-min-w-0 tw-items-start tw-gap-2">
              {isSelected && (
                <CheckCircleIcon
                  className="tw-mt-0.5 tw-size-4 tw-flex-shrink-0 tw-text-primary-300"
                  aria-hidden="true"
                />
              )}
              <span className="tw-min-w-0 tw-break-words tw-text-sm tw-font-medium tw-leading-5 tw-text-iron-100">
                {option.option_string}
              </span>
            </div>
            <div className="tw-mt-1 tw-text-xs tw-font-medium tw-text-iron-500">
              {formatNumberWithCommas(option.votes)}{" "}
              {option.votes === 1 ? "vote" : "votes"}
            </div>
          </div>
          <div className="tw-flex tw-flex-shrink-0 tw-items-center tw-gap-2">
            <span className="tw-text-sm tw-font-semibold tw-tabular-nums tw-text-iron-100">
              {percentage}%
            </span>
            <ChevronDownIcon
              className={`tw-size-4 tw-text-iron-500 tw-transition-transform ${
                isExpanded ? "tw-rotate-180" : ""
              }`}
              aria-hidden="true"
            />
          </div>
        </div>
      </button>
    </div>
  );
}

export default function WaveDropPoll({ drop }: WaveDropPollProps) {
  const queryClient = useQueryClient();
  const { requestAuth, setToast } = useAuth();
  const myStream = useMyStreamOptional();
  const [localPollOverride, setLocalPollOverride] =
    useState<LocalPollOverride | null>(null);
  const localPoll =
    localPollOverride && localPollOverride.sourcePoll === drop.poll
      ? localPollOverride.poll
      : null;
  const poll = localPoll ?? drop.poll;
  const [interactionState, setInteractionState] =
    useState<PollInteractionState | null>(null);

  const voteMutation = useMutation({
    mutationFn: async (options: readonly number[]) =>
      await voteDropPollV2({
        drop,
        options,
      }),
    onSuccess: (updatedDrop) => {
      if (updatedDrop.poll) {
        setLocalPollOverride({
          sourcePoll: drop.poll,
          poll: updatedDrop.poll,
        });
        setInteractionState({
          ...getDefaultPollInteractionState(updatedDrop.poll),
          view: "results",
        });
      }
      updateDropInCachedDrops(queryClient, updatedDrop);
      myStream?.processIncomingDrop(
        updatedDrop,
        ProcessIncomingDropType.DROP_INSERT
      );
      void queryClient.invalidateQueries({
        queryKey: [QueryKey.DROP_POLL_VOTERS],
      });
    },
    onError: (error) => {
      setToast({
        message: error instanceof Error ? error.message : String(error),
        type: "error",
      });
    },
  });

  const handleVoteOptionChange = useCallback(
    (optionNo: number) => {
      if (!poll) {
        return;
      }

      setInteractionState((current) => {
        const scopedState = getScopedPollInteractionState(current, poll);
        if (!poll.multichoice) {
          return {
            ...scopedState,
            selectedOptionNos: [optionNo],
          };
        }

        const next = new Set(scopedState.selectedOptionNos);
        if (next.has(optionNo)) {
          next.delete(optionNo);
        } else {
          next.add(optionNo);
        }
        return {
          ...scopedState,
          selectedOptionNos: [...next].sort((a, b) => a - b),
        };
      });
    },
    [poll]
  );

  const handleSubmitVote = useCallback(async () => {
    if (!poll?.is_open) {
      return;
    }

    const scopedState = getScopedPollInteractionState(interactionState, poll);
    if (scopedState.selectedOptionNos.length === 0) {
      return;
    }

    const { success } = await requestAuth();
    if (!success) {
      return;
    }

    voteMutation.mutate(scopedState.selectedOptionNos);
  }, [interactionState, poll, requestAuth, voteMutation]);

  if (!poll) {
    return null;
  }

  const hasVoted = poll.voted.length > 0;
  const scopedState = getScopedPollInteractionState(interactionState, poll);
  const selectedOptions = new Set(scopedState.selectedOptionNos);
  const totalVotes = poll.options.reduce((total, option) => {
    return total + option.votes;
  }, 0);
  const votedOptionNos = new Set(poll.voted);
  const effectiveView = poll.is_open ? scopedState.view : "results";
  const expandedOptionNo = scopedState.expandedOptionNo;
  const voteOptionGroupName = `drop-poll-${poll.id}`;
  const toggleViewLabel = getPollToggleLabel({
    effectiveView,
    hasVoted,
  });
  const submitButtonLabel = getPollSubmitLabel({
    isPending: voteMutation.isPending,
    hasVoted,
  });

  return (
    <div
      className="tw-mt-3 tw-w-full tw-rounded-xl tw-border tw-border-solid tw-border-iron-800 tw-bg-iron-950/70 tw-p-3"
      onClick={(event) => event.stopPropagation()}
    >
      <div className="tw-flex tw-flex-wrap tw-items-center tw-justify-between tw-gap-2">
        <div className="tw-min-w-0">
          <div className="tw-flex tw-flex-wrap tw-items-center tw-gap-2">
            <span className="tw-text-sm tw-font-semibold tw-text-iron-50">
              Poll
            </span>
          </div>
          <div className="tw-mt-1 tw-text-xs tw-font-medium tw-text-iron-500">
            {getPollClosingLabel(poll)}
          </div>
        </div>
        {poll.is_open && (
          <button
            type="button"
            onClick={() => {
              setInteractionState((current) => {
                const currentState = getScopedPollInteractionState(
                  current,
                  poll
                );
                const nextView =
                  currentState.view === "results" ? "vote" : "results";
                return {
                  ...currentState,
                  view: nextView,
                };
              });
            }}
            className="tw-inline-flex tw-items-center tw-rounded-md tw-border tw-border-solid tw-border-iron-700 tw-bg-iron-900 tw-px-2.5 tw-py-1.5 tw-text-xs tw-font-semibold tw-text-iron-100 tw-transition desktop-hover:hover:tw-border-iron-600 desktop-hover:hover:tw-bg-iron-800"
          >
            {toggleViewLabel}
          </button>
        )}
      </div>

      {effectiveView === "vote" && poll.is_open ? (
        <div className="tw-mt-3 tw-flex tw-flex-col tw-gap-2">
          {poll.options.map((option) => (
            <PollVoteOption
              key={option.option_no}
              option={option}
              checked={selectedOptions.has(option.option_no)}
              multichoice={poll.multichoice}
              groupName={voteOptionGroupName}
              disabled={voteMutation.isPending}
              onChange={handleVoteOptionChange}
            />
          ))}
          <div className="tw-mt-1 tw-flex tw-justify-end">
            <button
              type="button"
              disabled={selectedOptions.size === 0 || voteMutation.isPending}
              onClick={(event) => {
                event.stopPropagation();
                void handleSubmitVote();
              }}
              className="tw-text-primary-200 tw-inline-flex tw-items-center tw-rounded-md tw-border tw-border-solid tw-border-primary-500/60 tw-bg-primary-500/15 tw-px-3 tw-py-1.5 tw-text-xs tw-font-semibold tw-transition disabled:tw-cursor-not-allowed disabled:tw-border-iron-700 disabled:tw-bg-iron-800 disabled:tw-text-iron-500 desktop-hover:hover:tw-bg-primary-500/25"
            >
              {submitButtonLabel}
            </button>
          </div>
        </div>
      ) : (
        <div className="tw-mt-3 tw-flex tw-flex-col tw-gap-2">
          {poll.options.map((option) => (
            <div key={option.option_no}>
              <PollResultOption
                option={option}
                totalVotes={totalVotes}
                isSelected={votedOptionNos.has(option.option_no)}
                isExpanded={expandedOptionNo === option.option_no}
                onToggle={(optionNo) =>
                  setInteractionState((current) => {
                    const currentState = getScopedPollInteractionState(
                      current,
                      poll
                    );
                    return {
                      ...currentState,
                      expandedOptionNo:
                        currentState.expandedOptionNo === optionNo
                          ? null
                          : optionNo,
                    };
                  })
                }
              />
              {expandedOptionNo === option.option_no && (
                <div className="tw-overflow-hidden tw-rounded-b-lg tw-border-x tw-border-b tw-border-solid tw-border-iron-800 tw-bg-iron-950">
                  <PollOptionVoters dropId={drop.id} option={option} />
                </div>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
