import type { ApiCommunityMemberOverview } from "@/generated/models/ApiCommunityMemberOverview";
import {
  formatLargeNumber,
  formatNumberWithCommasOrDash,
  getTimeAgoShort,
} from "@/helpers/Helpers";
import UserLevel from "@/components/user/utils/level/UserLevel";
import UserCICTypeIcon from "@/components/user/utils/user-cic-type/UserCICTypeIcon";
import {
  isEthereumAddress,
  isAutoGeneratedHandle,
} from "@/helpers/AllowlistToolHelpers";
import { ImageScale, getScaledImageUri } from "@/helpers/image.helpers";
import Image from "next/image";
import Link from "next/link";

export default function CommunityMembersMobileCard({
  member,
  rank,
}: {
  readonly member: ApiCommunityMemberOverview;
  readonly rank: number;
}) {
  const isNotProfile = isEthereumAddress(member.detail_view_key);
  const isProfile = !isNotProfile;
  const textColorClass = isProfile ? "tw-text-iron-50" : "tw-text-iron-400";
  const path = `/${member.detail_view_key}`;

  const now = Date.now();

  return (
    <Link
      href={path}
      className="tw-flex tw-flex-col tw-gap-y-3 tw-overflow-hidden tw-rounded-xl tw-border tw-border-solid tw-border-iron-800 tw-bg-iron-900/80 tw-p-3 tw-no-underline tw-shadow-sm tw-shadow-black/20 tw-backdrop-blur-md tw-transition-all tw-duration-200 active:tw-bg-iron-800"
    >
      <div className="tw-flex tw-w-full tw-justify-between">
        <div className="tw-flex tw-items-center tw-gap-x-2">
          <span className="tw-flex-shrink-0 tw-text-xs tw-text-iron-400">
            #{rank}
          </span>
          <div className="tw-relative tw-flex tw-size-11 tw-flex-shrink-0 tw-items-center tw-justify-center tw-overflow-hidden tw-rounded-md tw-bg-iron-900 tw-ring-1 tw-ring-white/10">
            {member.pfp && (
              <Image
                src={getScaledImageUri(member.pfp, ImageScale.W_AUTO_H_50)}
                alt={`${member.display} avatar`}
                fill
                unoptimized
                className="tw-object-contain"
              />
            )}
          </div>
          <div className="tw-flex tw-min-w-0 tw-flex-col tw-items-start tw-gap-y-1">
            <div
              className={`tw-overflow-hidden ${
                isEthereumAddress(member.detail_view_key) ||
                isAutoGeneratedHandle(member.detail_view_key)
                  ? "tw-max-w-48 tw-truncate"
                  : ""
              }`}
            >
              <span className={`tw-text-sm tw-font-medium ${textColorClass}`}>
                {member.display}
              </span>
            </div>
            <UserLevel level={member.level} size="xs" />
          </div>
        </div>
        {typeof member.last_activity === "number" && (
          <div className="tw-ml-auto tw-flex tw-items-center tw-gap-x-1 tw-self-start">
            <span className="tw-text-xs tw-text-iron-400">Last Seen</span>
            <span className="tw-text-xs tw-text-iron-400">
              {getTimeAgoShort(member.last_activity, now, true)} ago
            </span>
          </div>
        )}
      </div>
      <div className="tw-flex tw-items-center tw-justify-between tw-gap-x-3 tw-whitespace-nowrap">
        <div className="tw-flex tw-items-baseline tw-gap-x-1">
          <span className="tw-text-xs tw-font-semibold tw-text-iron-50">
            {member.tdh === 0 ? "-" : formatLargeNumber(member.tdh)}
          </span>
          <span className="tw-text-xxs tw-text-iron-400">TDH</span>
        </div>
        <div className="tw-flex tw-items-baseline tw-gap-x-1">
          <span className="tw-text-xs tw-font-semibold tw-text-iron-50">
            {member.xtdh === 0
              ? "-"
              : formatLargeNumber(Math.round(member.xtdh))}
          </span>
          <span className="tw-text-xxs tw-text-iron-400">xTDH</span>
        </div>
        <div className="tw-flex tw-items-baseline tw-gap-x-1">
          <span className="tw-text-xs tw-font-semibold tw-text-iron-50">
            {formatNumberWithCommasOrDash(member.rep)}
          </span>
          <span className="tw-text-xxs tw-text-iron-400">REP</span>
        </div>
        <div className="tw-flex tw-items-center tw-gap-x-1">
          <div className="tw-size-4">
            <UserCICTypeIcon cic={member.cic} />
          </div>
          <span className="tw-text-xs tw-font-semibold tw-text-iron-50">
            {formatNumberWithCommasOrDash(member.cic)}
          </span>
          <span className="tw-text-xxs tw-text-iron-400">NIC</span>
        </div>
      </div>
    </Link>
  );
}
