import type { ApiCommunityMemberOverview } from "@/generated/models/ApiCommunityMemberOverview";
import { formatLargeNumber, formatNumberWithCommasOrDash, getTimeAgoShort } from "@/helpers/Helpers";
import UserLevel from "@/components/user/utils/level/UserLevel";
import UserCICTypeIcon from "@/components/user/utils/user-cic-type/UserCICTypeIcon";
import {
  isEthereumAddress,
  isAutoGeneratedHandle,
} from "@/helpers/AllowlistToolHelpers";
import { ImageScale, getScaledImageUri } from "@/helpers/image.helpers";
import Link from "next/link";

export default function CommunityMembersMobileCard({
  member,
  rank,
}: {
  readonly member: ApiCommunityMemberOverview;
  readonly rank: number;
}) {
  const isNotProfile = isEthereumAddress(member.detail_view_key);
  const isProfile = !isNotProfile;
  const textColorClass = isProfile ? "tw-text-iron-50" : "tw-text-iron-400";
  const path = `/${member.detail_view_key}`;

  return (
    <Link
      href={path}
      className="tw-flex tw-flex-col tw-gap-y-3 tw-p-3 tw-rounded-xl tw-bg-iron-900/80 tw-border tw-border-iron-800 tw-border-solid tw-backdrop-blur-md active:tw-bg-iron-800 tw-transition-all tw-duration-200 tw-no-underline tw-overflow-hidden tw-shadow-sm tw-shadow-black/20"
    >
      <div className="tw-flex tw-justify-between tw-w-full">
        <div className="tw-flex tw-items-center tw-gap-x-2">
          <span className="tw-text-iron-400 tw-text-xs tw-flex-shrink-0">
            #{rank}
          </span>
          <div className="tw-flex-shrink-0 tw-h-11 tw-w-11 tw-rounded-md tw-overflow-hidden tw-ring-1 tw-ring-white/10 tw-bg-iron-900 tw-flex tw-items-center tw-justify-center">
            {member.pfp && (
              <img
                src={getScaledImageUri(member.pfp, ImageScale.W_AUTO_H_50)}
                alt={`${member.display} avatar`}
                className="tw-h-full tw-w-full tw-object-contain tw-mx-auto"
              />
            )}
          </div>
          <div className="tw-flex tw-flex-col tw-items-start tw-gap-y-1 tw-min-w-0">
            <div
              className={`tw-overflow-hidden ${
                isEthereumAddress(member.detail_view_key) ||
                isAutoGeneratedHandle(member.detail_view_key)
                  ? "tw-max-w-[12rem] tw-truncate"
                  : ""
              }`}
            >
              <span className={`tw-text-sm tw-font-medium ${textColorClass}`}>
                {member.display}
              </span>
            </div>
            <UserLevel level={member.level} size="xs" />
          </div>
        </div>
        {member.last_activity && (
          <div className="tw-flex tw-items-center tw-gap-x-1 tw-ml-auto tw-self-start">
            <span className="tw-text-iron-400 tw-text-xs">Last Seen</span>
            <span className="tw-text-iron-400 tw-text-xs">
              {getTimeAgoShort(member.last_activity, Date.now(), true)} ago
            </span>
          </div>
        )}
      </div>
      <div className="tw-flex tw-items-center tw-gap-x-3 tw-whitespace-nowrap tw-justify-between">
        <div className="tw-flex tw-items-baseline tw-gap-x-1">
          <span className="tw-font-semibold tw-text-iron-50 tw-text-xs">
            {member.tdh === 0 ? "-" : formatLargeNumber(member.tdh)}
          </span>
          <span className="tw-text-iron-400 tw-text-xxs">TDH</span>
        </div>
        <div className="tw-flex tw-items-baseline tw-gap-x-1">
          <span className="tw-font-semibold tw-text-iron-50 tw-text-xs">
            {member.xtdh === 0 ? "-" : formatLargeNumber(Math.round(member.xtdh))}
          </span>
          <span className="tw-text-iron-400 tw-text-xxs">xTDH</span>
        </div>
        <div className="tw-flex tw-items-baseline tw-gap-x-1">
          <span className="tw-font-semibold tw-text-iron-50 tw-text-xs">
            {formatNumberWithCommasOrDash(member.rep)}
          </span>
          <span className="tw-text-iron-400 tw-text-xxs">REP</span>
        </div>
        <div className="tw-flex tw-items-center tw-gap-x-1">
          <div className="tw-h-4 tw-w-4">
            <UserCICTypeIcon cic={member.cic} />
          </div>
          <span className="tw-font-semibold tw-text-iron-50 tw-text-xs">
            {formatNumberWithCommasOrDash(member.cic)}
          </span>
          <span className="tw-text-iron-400 tw-text-xxs">NIC</span>
        </div>
      </div>
    </Link>
  );
}
