import ProfileBadge from "@/components/common/profile/ProfileBadge";
import UserProfileTooltipWrapper from "@/components/utils/tooltip/UserProfileTooltipWrapper";
import { cicToType } from "@/helpers/Helpers";
import { isEthereumAddress, isAutoGeneratedHandle } from "@/helpers/AllowlistToolHelpers";
import type { ApiXTdhContribution } from "@/generated/models/ApiXTdhContribution";

import { formatXtdhRate, formatXtdhValue } from "../../../utils/formatters";
import { XtdhRatePill } from "../../../collection-card-content/subcomponents/XtdhRatePill";

interface XtdhTokenContributorsListItemProps {
  /**
   * Contribution row which either references a specific grant (flat view)
   * or represents a group of grants for a given grantor.
   */
  readonly contribution: ApiXTdhContribution;
  readonly onSelectGrant: (grantId: string, label: string) => void;
}

export function XtdhTokenContributorsListItem({
  contribution,
  onSelectGrant,
}: Readonly<XtdhTokenContributorsListItemProps>) {
  const xtdhValue = formatXtdhValue(contribution.xtdh);
  const xtdhRateValue = formatXtdhRate(contribution.xtdh_rate);
  const grantor = contribution.grant?.grantor ?? contribution.grantor ?? null;
  const grantorHandle = grantor?.handle ?? null;
  const tooltipIdentity = grantorHandle ?? grantor?.id ?? "";
  const displayHandle =
    grantorHandle ?? grantor?.primary_address ?? "Unknown grantor";
  const shouldTruncate =
    isEthereumAddress(displayHandle) || isAutoGeneratedHandle(displayHandle);
  const profileHref = grantorHandle ? `/${grantorHandle}` : undefined;

  const avatarFallback = (
    <div className="tw-flex tw-h-full tw-w-full tw-items-center tw-justify-center tw-text-xs tw-font-semibold tw-text-iron-400 tw-truncate">
      ?
    </div>
  );

  const grantorBadge = (
    <ProfileBadge
      handle={displayHandle}
      href={profileHref}
      pfpUrl={grantor?.pfp}
      level={grantor?.level ?? 0}
      cicType={cicToType(grantor?.cic ?? 0)}
      avatarFallback={avatarFallback}
      asLink={Boolean(profileHref)}
      avatarAlt={grantorHandle ?? "Grantor profile"}
    />
  );

  const grantorSummary = tooltipIdentity ? (
    <UserProfileTooltipWrapper user={tooltipIdentity}>
      {grantorBadge}
    </UserProfileTooltipWrapper>
  ) : (
    grantorBadge
  );

  const grantId = contribution.grant?.id;
  const isClickable = Boolean(grantId);

  return (
    <li
      className={`tw-list-none tw-rounded-xl tw-border tw-border-solid tw-border-white/5  tw-bg-iron-900 desktop-hover:hover:tw-bg-iron-900/60 tw-p-4 tw-cursor-pointer tw-transition-all tw-duration-300  ${isClickable
        ? "tw-cursor-pointer desktop-hover:hover:tw-bg-iron-950 desktop-hover:hover:tw-border-white/10"
        : ""
        }`}
      onClick={() => {
        if (grantId) {
          onSelectGrant(grantId, displayHandle);
        }
      }}
    >
      <div className="tw-flex tw-flex-col tw-gap-3 lg:tw-flex-row lg:tw-items-center lg:tw-justify-between">
        <div className="tw-flex tw-items-center tw-gap-3 tw-min-w-0">
          <div className={shouldTruncate ? "tw-max-w-40 md:tw-max-w-80 [&_p]:tw-truncate [&>div]:tw-min-w-0 [&>div>div]:tw-min-w-0" : ""}>
            {grantorSummary}
          </div>
        </div>
        <XtdhRatePill
          rateLabel={xtdhRateValue}
          totalLabel={xtdhValue}
          className="tw-justify-start lg:tw-justify-end lg:tw-w-[280px]"
        />
      </div>
    </li>
  );
}
