import Link from "next/link";
import type { ApiGroupFull } from "@/generated/models/ApiGroupFull";
import {
  isEthereumAddress,
  isAutoGeneratedHandle,
} from "@/helpers/AllowlistToolHelpers";

export default function GroupCardHeader({
  group,
  titlePlaceholder,
}: {
  readonly group?: ApiGroupFull | undefined;
  readonly titlePlaceholder?: string | undefined;
}) {
  const groupName = group?.name ?? titlePlaceholder ?? "";
  const nameHref = group ? `/network?page=1&group=${group.id}` : undefined;
  const containsAddress = groupName
    .split(/\s+/)
    .some((token) => isEthereumAddress(token) || isAutoGeneratedHandle(token));
  const nameClasses = containsAddress
    ? "tw-block tw-mb-0 tw-max-w-full tw-truncate tw-text-lg tw-font-semibold tw-leading-tight tw-text-iron-50"
    : "tw-block tw-mb-0 tw-max-w-full tw-line-clamp-2 tw-text-lg tw-font-semibold tw-leading-tight tw-text-iron-50";

  return (
    <div className="tw-flex tw-items-start tw-justify-between tw-gap-x-3">
      <div className="tw-min-w-0 tw-flex-1">
        {nameHref ? (
          <Link
            href={nameHref}
            tabIndex={-1}
            className={`${nameClasses} tw-relative tw-z-30 tw-no-underline tw-transition tw-duration-200 tw-ease-out desktop-hover:hover:tw-text-iron-300`}
            title={groupName}
          >
            {groupName}
          </Link>
        ) : (
          <span className={nameClasses} title={groupName}>
            {groupName}
          </span>
        )}
      </div>
    </div>
  );
}
