"use client";

import { useContext } from "react";
import { AuthContext } from "@/components/auth/Auth";
import { ApiGroupFull } from "@/generated/models/ApiGroupFull";
import {
  isAutoGeneratedHandle,
  isEthereumAddress,
} from "@/helpers/AllowlistToolHelpers";
import { GroupCardState } from "./GroupCard";
import GroupCardConfigs from "./GroupCardConfigs";

export default function GroupCardContent({
  group,
  haveActiveGroupVoteAll,
  setState,
  titlePlaceholder,
}: {
  readonly group?: ApiGroupFull;
  readonly haveActiveGroupVoteAll: boolean;
  readonly setState?: (state: GroupCardState) => void;
  readonly titlePlaceholder?: string;
}) {
  const { connectedProfile } = useContext(AuthContext);
  const baseButtonClasses =
    "tw-relative tw-z-30 tw-inline-flex tw-items-center tw-justify-center tw-gap-x-2 tw-rounded-lg tw-border tw-border-solid tw-ring-1 tw-ring-iron-700 tw-font-semibold tw-shadow-sm tw-transition tw-duration-300 tw-ease-out focus-visible:tw-outline focus-visible:tw-outline-2 focus-visible:tw-outline-offset-2 focus-visible:tw-outline-iron-700";
  const activeButtonClasses =
    "tw-bg-iron-800 tw-border-iron-800 tw-text-iron-200 desktop-hover:hover:tw-bg-iron-700 desktop-hover:hover:tw-border-iron-700 desktop-hover:hover:tw-text-white";
  const disabledButtonClasses =
    "tw-bg-iron-900 tw-border-iron-900 tw-text-iron-500 tw-cursor-not-allowed tw-opacity-50";
  const buttonPaddingClasses = "tw-px-2.5 tw-py-1.5 tw-text-sm";

  const groupName = group?.name ?? titlePlaceholder ?? "";
  const nameHref = group ? `/network?page=1&group=${group.id}` : undefined;
  const containsAddress = groupName
    .split(/\s+/)
    .some((token) => isEthereumAddress(token) || isAutoGeneratedHandle(token));
  const nameClasses = containsAddress
    ? "tw-block tw-mb-0 tw-max-w-full tw-truncate tw-text-lg tw-font-semibold tw-leading-tight tw-text-iron-50"
    : "tw-block tw-mb-0 tw-max-w-full tw-line-clamp-2 tw-text-lg tw-font-semibold tw-leading-tight tw-text-iron-50";

  return (
    <div className="tw-flex tw-flex-1 tw-flex-col tw-gap-y-3">
      <div className="tw-flex tw-flex-wrap tw-items-center tw-justify-between tw-gap-x-4 tw-gap-y-2">
        <div className="tw-min-w-0 tw-flex-1">
          {nameHref ? (
            <a
              href={nameHref}
              onClick={(event) => {
                event.preventDefault();
                event.stopPropagation();
                setState?.(GroupCardState.IDLE);
              }}
              className={`${nameClasses} tw-no-underline tw-transition tw-duration-200 tw-ease-out desktop-hover:hover:tw-text-iron-300`}
              title={groupName}
            >
              {groupName}
            </a>
          ) : (
            <span className={nameClasses} title={groupName}>
              {groupName}
            </span>
          )}
        </div>
        {!!connectedProfile?.handle && setState && (
          <div className="tw-flex tw-flex-shrink-0 tw-flex-wrap tw-items-center tw-justify-end tw-gap-2">
            <button
              type="button"
              disabled={haveActiveGroupVoteAll}
              className={`${baseButtonClasses} ${buttonPaddingClasses} ${
                haveActiveGroupVoteAll
                  ? disabledButtonClasses
                  : activeButtonClasses
              }`}
              onClick={(event) => {
                event.stopPropagation();
                setState(GroupCardState.REP);
              }}
            >
              Rep all
            </button>
            <button
              type="button"
              disabled={haveActiveGroupVoteAll}
              className={`${baseButtonClasses} ${buttonPaddingClasses} ${
                haveActiveGroupVoteAll
                  ? disabledButtonClasses
                  : activeButtonClasses
              }`}
              onClick={(event) => {
                event.stopPropagation();
                setState(GroupCardState.NIC);
              }}
            >
              NIC all
            </button>
          </div>
        )}
      </div>
      <GroupCardConfigs group={group} />
    </div>
  );
}
