"use client";

import Link from "next/link";
import type { ApiGroupFull } from "@/generated/models/ApiGroupFull";
import { getTimeAgo } from "@/helpers/Helpers";
import { useContext } from "react";
import { AuthContext } from "@/components/auth/Auth";
import GroupCardEditActions from "./actions/GroupCardEditActions";
import { getScaledImageUri, ImageScale } from "@/helpers/image.helpers";
import {
  isAutoGeneratedHandle,
  isEthereumAddress,
} from "@/helpers/AllowlistToolHelpers";

export default function GroupCardHeader({
  group,
  onEditClick,
  userPlaceholder,
}: {
  readonly group?: ApiGroupFull | undefined;
  readonly onEditClick?:
    | ((group: ApiGroupFull) => void)
    | undefined
    | undefined;
  readonly userPlaceholder?: string | undefined;
}) {
  const { connectedProfile, activeProfileProxy } = useContext(AuthContext);
  const timeAgo = group
    ? getTimeAgo(new Date(group.created_at ?? "").getTime())
    : "";

  const rawCreatorHandle = group?.created_by?.handle;
  const fallbackHandle = userPlaceholder ?? "";
  const hasCreatorHandle = Boolean(rawCreatorHandle);
  const creatorHandle = hasCreatorHandle ? rawCreatorHandle! : fallbackHandle;
  const profileHref = hasCreatorHandle
    ? `/${rawCreatorHandle}`
    : fallbackHandle;
  const shouldTruncateHandle =
    creatorHandle !== userPlaceholder &&
    (isEthereumAddress(creatorHandle) || isAutoGeneratedHandle(creatorHandle));

  return (
    <div className="tw-flex tw-flex-wrap tw-items-start tw-justify-between tw-gap-x-3 tw-gap-y-2.5">
      <div className="tw-flex tw-items-center tw-gap-x-2.5">
        <div className="tw-relative tw-h-9 tw-w-9 tw-flex-shrink-0 tw-overflow-hidden tw-rounded-lg tw-ring-1 tw-ring-white/10 tw-shadow-inner tw-shadow-black/40">
          {group?.created_by.pfp ? (
            <img
              src={getScaledImageUri(
                group.created_by.pfp,
                ImageScale.W_AUTO_H_50
              )}
              alt={
                group?.created_by.handle
                  ? `${group.created_by.handle} profile picture`
                  : "Group creator profile picture"
              }
              className="tw-h-full tw-w-full tw-object-cover tw-bg-white/5"
              loading="lazy"
              decoding="async"
            />
          ) : (
            <div className="tw-h-full tw-w-full tw-bg-white/5" />
          )}
        </div>
        <div className="tw-flex tw-flex-col tw-gap-y-1">
          <Link
            onClick={(e) => e.stopPropagation()}
            href={profileHref}
            className="tw-relative tw-z-30 tw-inline-flex tw-items-center tw-gap-x-1 tw-text-white tw-no-underline tw-transition tw-duration-300 tw-ease-out desktop-hover:hover:tw-text-iron-400"
          >
            <span
              className={`tw-inline-block tw-text-sm tw-font-semibold ${
                shouldTruncateHandle ? "tw-max-w-[8rem] tw-truncate" : ""
              }`}
            >
              {creatorHandle}
            </span>
          </Link>
          {timeAgo && (
            <span className="tw-text-xs tw-font-medium tw-text-iron-400">
              Created {timeAgo}
            </span>
          )}
        </div>
      </div>
      <div className="tw-flex tw-items-center tw-gap-x-3">
        {!!connectedProfile?.handle &&
          !activeProfileProxy &&
          onEditClick &&
          group && (
            <GroupCardEditActions group={group} onEditClick={onEditClick} />
          )}
      </div>
    </div>
  );
}
