"use client";

import Image from "next/image";
import Link from "next/link";
import type { ApiGroupFull } from "@/generated/models/ApiGroupFull";
import {
  isAutoGeneratedHandle,
  isEthereumAddress,
} from "@/helpers/AllowlistToolHelpers";
import { getTimeAgo } from "@/helpers/Helpers";
import { getScaledImageUri, ImageScale } from "@/helpers/image.helpers";

export default function GroupCardCreator({
  group,
  userPlaceholder,
}: {
  readonly group?: ApiGroupFull | undefined;
  readonly userPlaceholder?: string | undefined;
}) {
  const timeAgo = group ? getTimeAgo(new Date(group.created_at).getTime()) : "";
  const rawCreatorHandle = group?.created_by.handle;
  const fallbackHandle = userPlaceholder ?? "";
  const creatorHandle = rawCreatorHandle ?? fallbackHandle;
  const shouldTruncateHandle =
    creatorHandle !== userPlaceholder &&
    (isEthereumAddress(creatorHandle) || isAutoGeneratedHandle(creatorHandle));

  return (
    <div className="tw-flex tw-items-center tw-gap-x-2">
      <div className="tw-relative tw-size-7 tw-flex-shrink-0 tw-overflow-hidden tw-rounded-md tw-bg-white/5 tw-shadow-inner tw-shadow-black/40 tw-ring-1 tw-ring-white/10">
        {group?.created_by.pfp ? (
          <Image
            src={getScaledImageUri(
              group.created_by.pfp,
              ImageScale.W_AUTO_H_50
            )}
            alt={
              group.created_by.handle
                ? `${group.created_by.handle} profile picture`
                : "Group creator profile picture"
            }
            fill
            sizes="28px"
            unoptimized
            className="tw-object-cover"
          />
        ) : null}
      </div>
      <div className="tw-min-w-0 tw-flex-1">
        {rawCreatorHandle ? (
          <Link
            onClick={(event) => event.stopPropagation()}
            href={`/${rawCreatorHandle}`}
            className="tw-relative tw-z-30 tw-inline-flex tw-max-w-full tw-items-center tw-text-xs tw-font-semibold tw-text-iron-200 tw-no-underline tw-transition tw-duration-300 tw-ease-out desktop-hover:hover:tw-text-iron-400"
          >
            <span
              className={`tw-inline-block ${
                shouldTruncateHandle ? "tw-max-w-[8rem] tw-truncate" : ""
              }`}
            >
              {creatorHandle}
            </span>
          </Link>
        ) : (
          <span
            className={`tw-inline-block tw-text-xs tw-font-semibold tw-text-iron-200 ${
              shouldTruncateHandle ? "tw-max-w-[8rem] tw-truncate" : ""
            }`}
          >
            {creatorHandle}
          </span>
        )}
        {timeAgo && (
          <>
            <span
              aria-hidden="true"
              className="tw-mx-1.5 tw-text-[11px] tw-font-medium tw-text-iron-600"
            >
              ·
            </span>
            <span className="tw-text-[11px] tw-font-medium tw-text-iron-500">
              Created {timeAgo}
            </span>
          </>
        )}
      </div>
    </div>
  );
}
