"use client";

import { useContext } from "react";
import { AuthContext } from "@/components/auth/Auth";
import Button from "@/components/utils/button/Button";
import type { ApiGroupFull } from "@/generated/models/ApiGroupFull";
import {
  isAutoGeneratedHandle,
  isEthereumAddress,
} from "@/helpers/AllowlistToolHelpers";
import { GroupCardState } from "./GroupCard";
import GroupCardConfigs from "./GroupCardConfigs";

export default function GroupCardContent({
  group,
  haveActiveGroupVoteAll,
  setState,
  titlePlaceholder,
}: {
  readonly group?: ApiGroupFull | undefined;
  readonly haveActiveGroupVoteAll: boolean;
  readonly setState?: ((state: GroupCardState) => void) | undefined;
  readonly titlePlaceholder?: string | undefined;
}) {
  const { connectedProfile } = useContext(AuthContext);

  const groupName = group?.name ?? titlePlaceholder ?? "";
  const nameHref = group ? `/network?page=1&group=${group.id}` : undefined;
  const containsAddress = groupName
    .split(/\s+/)
    .some((token) => isEthereumAddress(token) || isAutoGeneratedHandle(token));
  const nameClasses = containsAddress
    ? "tw-block tw-mb-0 tw-max-w-full tw-truncate tw-text-lg tw-font-semibold tw-leading-tight tw-text-iron-50"
    : "tw-block tw-mb-0 tw-max-w-full tw-line-clamp-2 tw-text-lg tw-font-semibold tw-leading-tight tw-text-iron-50";

  return (
    <div className="tw-flex tw-flex-1 tw-flex-col tw-gap-y-3">
      <div className="tw-flex tw-flex-wrap tw-items-center tw-justify-between tw-gap-x-4 tw-gap-y-2">
        <div className="tw-min-w-0 tw-flex-1">
          {nameHref ? (
            <a
              href={nameHref}
              onClick={(event) => {
                event.preventDefault();
                event.stopPropagation();
                setState?.(GroupCardState.IDLE);
              }}
              className={`${nameClasses} tw-no-underline tw-transition tw-duration-200 tw-ease-out desktop-hover:hover:tw-text-iron-300`}
              title={groupName}
            >
              {groupName}
            </a>
          ) : (
            <span className={nameClasses} title={groupName}>
              {groupName}
            </span>
          )}
          <p className="tw-mt-1 tw-text-xs tw-text-iron-400">
            Source: filters + optional manual list
          </p>
        </div>
        {!!connectedProfile?.handle && setState && (
          <div className="tw-flex tw-flex-shrink-0 tw-flex-wrap tw-items-center tw-justify-end tw-gap-2">
            <Button
              disabled={haveActiveGroupVoteAll}
              variant="tertiary"
              size="xs"
              className="tw-relative tw-z-30"
              onClick={(event) => {
                event.stopPropagation();
                setState(GroupCardState.REP);
              }}
            >
              Rep all
            </Button>
            <Button
              disabled={haveActiveGroupVoteAll}
              variant="tertiary"
              size="xs"
              className="tw-relative tw-z-30"
              onClick={(event) => {
                event.stopPropagation();
                setState(GroupCardState.NIC);
              }}
            >
              NIC all
            </Button>
          </div>
        )}
      </div>
      <GroupCardConfigs group={group} />
    </div>
  );
}
