import { render, screen } from '@testing-library/react';
import React from 'react';

jest.mock('next/link', () => ({ __esModule: true, default: ({ href, children }: any) => <a href={href}>{children}</a> }));
jest.mock('../../../../components/utils/CommonTimeAgo', () => ({ __esModule: true, default: ({ timestamp }: any) => <span data-testid="time">{timestamp}</span> }));
jest.mock('../../../../components/user/utils/user-cic-type/UserCICTypeIcon', () => ({ __esModule: true, default: () => <span data-testid="cic" /> }));
jest.mock('../../../../components/user/utils/level/UserLevel', () => ({ __esModule: true, default: () => <div data-testid="level" /> }));
jest.mock('../../../../helpers/Helpers', () => ({
  formatNumberWithCommasOrDash: (n: number) => `f${n}`,
  cicToType: (c: number) => c,
}));
jest.mock('../../../../helpers/AllowlistToolHelpers', () => ({
  isEthereumAddress: () => false,
  isAutoGeneratedHandle: () => false,
}));
jest.mock('../../../../helpers/image.helpers', () => ({
  ImageScale: { W_AUTO_H_50: '50' },
  getScaledImageUri: (u: string) => u,
}));

import CommunityMembersMobileCard from '../../../../components/community/members-table/CommunityMembersMobileCard';

const member = {
  display: 'Alice',
  detail_view_key: 'alice',
  level: 1,
  tdh: 100,
  rep: 50,
  cic: 1,
  pfp: 'url',
  last_activity: 10,
  wallet: '0x1',
} as any;

describe('CommunityMembersMobileCard', () => {
  it('renders member info and link', () => {
    render(<CommunityMembersMobileCard member={member} rank={2} />);
    expect(screen.getByText('#2')).toBeInTheDocument();
    expect(screen.getByText('Alice')).toBeInTheDocument();
    expect(screen.getByText('f100')).toBeInTheDocument();
    expect(screen.getByText('f50')).toBeInTheDocument();
    expect(screen.getByTestId('cic')).toBeInTheDocument();
    expect(screen.getByRole('link')).toHaveAttribute('href', '/alice');
  });
});
