import CommunityMembersMobileCard from "@/components/community/members-table/CommunityMembersMobileCard";
import type { ApiCommunityMemberOverview } from "@/generated/models/ApiCommunityMemberOverview";
import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import type { ReactNode } from "react";

jest.mock("next/link", () => ({
  __esModule: true,
  default: ({ href, children }: { href: string; children: ReactNode }) => (
    <a href={href}>{children}</a>
  ),
}));
jest.mock("@/components/user/utils/level/UserLevel", () => ({
  __esModule: true,
  default: () => <div data-testid="level" />,
}));
jest.mock("@/components/user/utils/user-cic-type/UserCICTypeIcon", () => ({
  __esModule: true,
  default: () => <div data-testid="cic-icon" />,
}));
jest.mock("@/helpers/Helpers", () => ({
  formatNumberWithCommasOrDash: (n: number) => `f${n}`,
  formatLargeNumber: (n: number) => `${n}M`,
  getTimeAgoShort: () => "2d",
}));
jest.mock("@/helpers/AllowlistToolHelpers", () => ({
  isEthereumAddress: (val: string) => val.startsWith("0x"),
  isAutoGeneratedHandle: () => false,
}));
jest.mock("@/helpers/image.helpers", () => ({
  ImageScale: { W_AUTO_H_50: "50" },
  getScaledImageUri: (u: string) => u,
}));

const baseMember: ApiCommunityMemberOverview = {
  display: "Alice",
  detail_view_key: "alice",
  level: 1,
  tdh: 100,
  tdh_rate: 10,
  xtdh: 55,
  xtdh_rate: 5,
  combined_tdh: 150,
  combined_tdh_rate: 15,
  rep: 60,
  cic: 1,
  pfp: "url",
  last_activity: 10,
  wallet: "0x1",
  xtdh_outgoing: 0,
  xtdh_incoming: 0,
};

describe("CommunityMembersMobileCard", () => {
  describe("rendering", () => {
    it("renders rank badge and profile link", () => {
      render(<CommunityMembersMobileCard member={baseMember} rank={2} />);

      expect(screen.getByText("#2")).toBeInTheDocument();
      expect(screen.getByRole("link")).toHaveAttribute("href", "/alice");
    });

    it("renders member display name", () => {
      render(<CommunityMembersMobileCard member={baseMember} rank={1} />);

      expect(screen.getByText("Alice")).toBeInTheDocument();
    });

    it("renders level and CIC icon", () => {
      render(<CommunityMembersMobileCard member={baseMember} rank={1} />);

      expect(screen.getByTestId("level")).toBeInTheDocument();
      expect(screen.getByTestId("cic-icon")).toBeInTheDocument();
    });

    it("renders all stat labels", () => {
      render(<CommunityMembersMobileCard member={baseMember} rank={1} />);

      expect(screen.getByText("TDH")).toBeInTheDocument();
      expect(screen.getByText("xTDH")).toBeInTheDocument();
      expect(screen.getByText("REP")).toBeInTheDocument();
      expect(screen.getByText("NIC")).toBeInTheDocument();
    });
  });

  describe("TDH/xTDH formatting", () => {
    it("formats large numbers correctly", () => {
      render(<CommunityMembersMobileCard member={baseMember} rank={1} />);

      expect(screen.getByText("100M")).toBeInTheDocument();
      expect(screen.getByText("55M")).toBeInTheDocument();
    });

    it("handles zero values with dash", () => {
      const zeroMember: ApiCommunityMemberOverview = {
        ...baseMember,
        tdh: 0,
        xtdh: 0,
      };
      render(<CommunityMembersMobileCard member={zeroMember} rank={1} />);

      const dashValues = screen.getAllByText("-");
      expect(dashValues).toHaveLength(2);
    });
  });

  describe("last activity", () => {
    it("renders Last Seen when last_activity is present", () => {
      render(<CommunityMembersMobileCard member={baseMember} rank={1} />);

      expect(screen.getByText("Last Seen")).toBeInTheDocument();
    });

    it("does not render Last Seen when last_activity is null", () => {
      const noActivityMember: ApiCommunityMemberOverview = {
        ...baseMember,
        last_activity: null,
      };
      render(<CommunityMembersMobileCard member={noActivityMember} rank={1} />);

      expect(screen.queryByText("Last Seen")).not.toBeInTheDocument();
    });
  });

  describe("profile type branches", () => {
    it("renders with ethereum address as detail_view_key", () => {
      const ethMember: ApiCommunityMemberOverview = {
        ...baseMember,
        detail_view_key: "0xabc123",
        display: "0xabc123",
      };
      render(<CommunityMembersMobileCard member={ethMember} rank={1} />);

      expect(screen.getByRole("link")).toHaveAttribute("href", "/0xabc123");
    });
  });

  describe("keyboard accessibility", () => {
    it("link can receive focus via keyboard", async () => {
      const user = userEvent.setup();
      render(<CommunityMembersMobileCard member={baseMember} rank={1} />);

      await user.tab();

      const link = screen.getByRole("link");
      expect(link).toHaveFocus();
    });
  });
});
