import { render, screen } from '@testing-library/react';

jest.mock('next/link', () => ({ __esModule: true, default: ({ href, children }: any) => <a href={href}>{children}</a> }));
jest.mock('@/components/user/utils/UserCICAndLevel', () => ({
  __esModule: true,
  default: () => <div data-testid="level" />,
  UserCICAndLevelSize: { SMALL: 'small' },
}));
jest.mock('@/helpers/Helpers', () => ({
  formatNumberWithCommasOrDash: (n: number) => `f${n}`,
  getTimeAgoShort: () => '2d',
}));
jest.mock('@/helpers/AllowlistToolHelpers', () => ({
  isEthereumAddress: () => false,
  isAutoGeneratedHandle: () => false,
}));
jest.mock('@/helpers/image.helpers', () => ({
  ImageScale: { W_AUTO_H_50: '50' },
  getScaledImageUri: (u: string) => u,
}));

import CommunityMembersMobileCard from '@/components/community/members-table/CommunityMembersMobileCard';

const member = {
  display: 'Alice',
  detail_view_key: 'alice',
  level: 1,
  tdh: 100,
  tdh_rate: 10,
  xtdh: 55,
  xtdh_rate: 5,
  combined_tdh: 150,
  combined_tdh_rate: 15,
  xtdh_incoming: 20,
  xtdh_outgoing: 10,
  rep: 60,
  cic: 1,
  pfp: 'url',
  last_activity: 10,
  wallet: '0x1',
} as any;

describe('CommunityMembersMobileCard', () => {
  it('renders member info and link', () => {
    render(<CommunityMembersMobileCard member={member} rank={2} />);
    expect(screen.getByText('#2')).toBeInTheDocument();
    expect(screen.getByText('Alice')).toBeInTheDocument();
    expect(screen.getByText('f100')).toBeInTheDocument();
    expect(screen.getByText('f55')).toBeInTheDocument();
    expect(screen.getByTestId('level')).toBeInTheDocument();
    expect(screen.getByRole('link')).toHaveAttribute('href', '/alice');
    expect(screen.getByText('REP:')).toBeInTheDocument();
    expect(screen.getByText('NIC:')).toBeInTheDocument();
    expect(screen.getByText('xTDH Grants')).toBeInTheDocument();
    expect(screen.getByText('In:')).toBeInTheDocument();
    expect(screen.getByText('Out:')).toBeInTheDocument();
  });
});
