"use client";

import XTDHCard from "../ui/XTDHCard";
import XTDHHeaderStats from "../header/XTDHHeaderStats";
import type { ApiIdentity } from "@/generated/models/ApiIdentity";
import NextActions from "./NextActions";

export default function XTDHOverview({ profile }: { readonly profile: ApiIdentity }) {
  return (
    <div className="tw-flex tw-flex-col tw-gap-4">
      <XTDHHeaderStats profile={profile} />

      <NextActions profile={profile} />

      <XTDHCard title="What is xTDH?">
        <div className="tw-text-iron-300 tw-text-sm tw-space-y-2">
          <p>
            Base TDH is generated by Memes & Gradients and is predictable. xTDH is a multiplier-based
            capacity you can allocate to external targets.
          </p>
          <p>
            Allocating xTDH reduces your own accrual; totals remain capped by Base TDH. Grants are
            reversible and adjust pro‑rata if your Base TDH changes.
          </p>
        </div>
      </XTDHCard>
    </div>
  );
}
