name: Build and Upload to S3

on: workflow_dispatch

jobs:
  build-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build
        env:
          NODE_ENV: "production"
          API_ENDPOINT: "https://api.seize.io"
          ALLOWLIST_API_ENDPOINT: "https://allowlist-api.seize.io"
          BASE_ENDPOINT: "https://seize.io"
          LOAD_S3: "true"
          VERSION: ${{ github.sha }}
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
        run: npm run build

      - name: Build Target
        run: |
          mkdir -p target/_next
          cp -r .next/static target/_next/
          zip -r package.zip . -x '*.git*' 'node_modules/*' 'target/*'
          mv package.zip target/

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload assets to S3
        run: aws s3 sync target s3://6529bucket/web_build/${{ github.sha }}/
