name: Build and Upload to S3

on: workflow_dispatch

env:
  AWS_BUCKET: "seize-web"
  COMMIT_SHA: "${{ github.sha }}"
  AWS_REGION: "us-east-1"
  BEANSTALK_APP_NAME: "seize app"
  BEANSTACK_ENV_NAME: "Seizeapp-env"

jobs:
  build-upload-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build App
        env:
          NODE_ENV: "production"
          API_ENDPOINT: "https://api.seize.io"
          ALLOWLIST_API_ENDPOINT: "https://allowlist-api.seize.io"
          BASE_ENDPOINT: "https://seize.io"
          LOAD_S3: "true"
          VERSION: ${{ env.COMMIT_SHA }}
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
        run: npm run build

      - name: Build Target
        run: |
          mkdir -p target/_next
          cp -r .next/static target/_next/
          zip -r package.zip . -x '*.git*' 'node_modules/*' 'target/*'
          mv package.zip target/

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload assets to S3
        run: aws s3 sync target s3://${{ env.AWS_BUCKET }}/web_build/${{ env.COMMIT_SHA }}/

      - name: Create new ElasticBeanstalk Application Version
        run: |
          export DESCRIPTION=$(git show -s --format=%s)
          aws elasticbeanstalk create-application-version \
          --application-name "${{ env.BEANSTALK_APP_NAME }}" \
          --source-bundle S3Bucket="${{ env.AWS_BUCKET }}",S3Key="web_build/${{ env.COMMIT_SHA }}/package.zip" \
          --version-label "${{ env.COMMIT_SHA }}" \
          --description "${DESCRIPTION:0:100}"

      - name: Deploy new Version to ElasticBeanstalk
        run: |
          aws elasticbeanstalk update-environment \
          --application-name "${{ env.BEANSTALK_APP_NAME }}" \
          --environment-name "${{ env.BEANSTACK_ENV_NAME }}" \
          --version-label "${{ env.COMMIT_SHA }}"

      - name: Check Elastic Beanstalk status
        run: |
          MAX_RETRIES=30
          COUNTER=0
          while [[ "$(aws elasticbeanstalk describe-environments --environment-names $ENV_NAME --query 'Environments[].Status' --output text)" != "Ready" && ${COUNTER} -lt ${MAX_RETRIES} ]]; do 
            COUNTER=$[$COUNTER +1]
            echo "Environment update still in progress... Attempt: $COUNTER" 
            sleep 30 
          done
          if [[ ${COUNTER} -eq ${MAX_RETRIES} ]]; then
            echo "Failed to update the environment within the expected time." 
            exit 1
          fi
          echo "Environment update complete!"
